;const ACCEPTANCE_REGRESSION_SEEDS=['1234567','987654','424242'],ACCEPTANCE_FIVE_MINUTE_DAYS=2400,ACCEPTANCE_THIRTY_MINUTE_DAYS=14400,ACCEPTANCE_GENERATION_LIMIT_MS=10000;
const ACCEPTANCE_DISASTER_TYPES=new Set(['drought','fire','plague-outbreak','plague-spread','plague-toll','dragon-raid','flood','earthquake']);
const ACCEPTANCE_INCIDENT_TYPES=new Set([...ACCEPTANCE_DISASTER_TYPES,'food-shortage','rebellion','war-declared','battle','siege','peace','bandit-camp','bandit-ambush','bandit-king','quarantine']);
function acceptanceNow(){return typeof performance!=='undefined'&&performance.now?performance.now():Date.now()}
function acceptanceBlankCounters(){return{namedCharacterEvents:0,incidents:0,growthEvents:0,successions:0,wars:0,battles:0,peace:0,disasters:0}}
function acceptanceBlankFirstDays(){return{namedCharacterEvent:null,incident:null,growth:null,succession:null,war:null,battle:null,peace:null,disaster:null}}
function acceptanceState(){return world.acceptanceState||(world.acceptanceState={active:false})}
function acceptanceMark(state,key,firstKey,day){state.counters[key]++;if(state.firstDays[firstKey]===null)state.firstDays[firstKey]=Math.floor(day)}
function acceptanceCharacterTokens(){initCharacters();let tokens=new Set();for(const c of characterState().registry){tokens.add(String(c.id));tokens.add(String(c.name))}return tokens}
function acceptanceEventHasCharacter(ev){let tokens=acceptanceCharacterTokens(),text=String(ev.metadata?.chronicle?.text||'');return(ev.participants||[]).some(p=>tokens.has(String(p)))||[...tokens].some(token=>token.length>3&&text.includes(token))}
function startAcceptanceTracking(){initEconomy();initCharacters();initThreats();let startedDay=Math.floor(clock.day),state={active:true,startedDay,initialSeason:world.season,seenSeasons:[world.season],initialChronicleTotal:stabilityState().chronicleTotal,initialBuildingCount:world.buildings.length,lastBuildingCount:world.buildings.length,initialReign:annalsState().reign,initialWarsCompleted:warState().completed,counters:acceptanceBlankCounters(),firstDays:acceptanceBlankFirstDays(),fiveMinute:null,thirtyMinute:null};world.acceptanceState=state;return acceptanceSummary()}
function acceptanceRecordEvent(ev){let state=world.acceptanceState;if(!state?.active||ev.day<state.startedDay)return;let type=ev.type;if(acceptanceEventHasCharacter(ev))acceptanceMark(state,'namedCharacterEvents','namedCharacterEvent',ev.day);if(ACCEPTANCE_INCIDENT_TYPES.has(type))acceptanceMark(state,'incidents','incident',ev.day);if(type==='succession')acceptanceMark(state,'successions','succession',ev.day);if(type==='war-declared')acceptanceMark(state,'wars','war',ev.day);if(type==='battle')acceptanceMark(state,'battles','battle',ev.day);if(type==='peace')acceptanceMark(state,'peace','peace',ev.day);if(ACCEPTANCE_DISASTER_TYPES.has(type))acceptanceMark(state,'disasters','disaster',ev.day)}
const acceptanceBaseEmitWorldEvent=emitWorldEvent;
emitWorldEvent=function(type,details={}){let ev=acceptanceBaseEmitWorldEvent(type,details);acceptanceRecordEvent(ev);return ev};
function acceptanceFiveMinuteResult(state=acceptanceState()){let elapsed=Math.max(0,Math.floor(clock.day-state.startedDay)),chronicleEntries=Math.max(0,stabilityState().chronicleTotal-state.initialChronicleTotal),checks={seasonChange:state.seenSeasons.length>1,chronicleEntries:chronicleEntries>=8,namedCharacterEvent:state.counters.namedCharacterEvents>0,visibleIncident:state.counters.incidents>0,visibleGrowth:state.counters.growthEvents>0},complete=elapsed>=ACCEPTANCE_FIVE_MINUTE_DAYS;return{windowDays:ACCEPTANCE_FIVE_MINUTE_DAYS,elapsedDays:elapsed,complete,passed:complete&&Object.values(checks).every(Boolean),checks,evidence:{seasons:[...state.seenSeasons],chronicleEntries,namedCharacterEvents:state.counters.namedCharacterEvents,incidents:state.counters.incidents,growthEvents:state.counters.growthEvents,buildingsAdded:Math.max(0,world.buildings.length-state.initialBuildingCount),firstDays:{...state.firstDays}}}}
function acceptanceThirtyMinuteResult(state=acceptanceState(),five=state.fiveMinute||acceptanceFiveMinuteResult(state)){let elapsed=Math.max(0,Math.floor(clock.day-state.startedDay)),checks={fiveMinutePassed:!!five.passed,successionOrWar:state.counters.successions>0||state.counters.wars>0},complete=elapsed>=ACCEPTANCE_THIRTY_MINUTE_DAYS;return{windowDays:ACCEPTANCE_THIRTY_MINUTE_DAYS,elapsedDays:elapsed,complete,passed:complete&&Object.values(checks).every(Boolean),checks,evidence:{successions:state.counters.successions,wars:state.counters.wars,battles:state.counters.battles,peace:state.counters.peace,disasters:state.counters.disasters,growthEvents:state.counters.growthEvents,reignsAdded:Math.max(0,annalsState().reign-state.initialReign),warsCompleted:Math.max(0,warState().completed-state.initialWarsCompleted),firstDays:{...state.firstDays}}}}
function acceptanceObserveDay(){let state=world.acceptanceState;if(!state?.active)return;if(!state.seenSeasons.includes(world.season))state.seenSeasons.push(world.season);if(world.buildings.length>state.lastBuildingCount){let added=world.buildings.length-state.lastBuildingCount;state.counters.growthEvents+=added;if(state.firstDays.growth===null)state.firstDays.growth=Math.floor(clock.day);state.lastBuildingCount=world.buildings.length}if(!state.fiveMinute&&clock.day-state.startedDay>=ACCEPTANCE_FIVE_MINUTE_DAYS)state.fiveMinute=acceptanceFiveMinuteResult(state);if(!state.thirtyMinute&&clock.day-state.startedDay>=ACCEPTANCE_THIRTY_MINUTE_DAYS)state.thirtyMinute=acceptanceThirtyMinuteResult(state,state.fiveMinute||acceptanceFiveMinuteResult(state))}
const acceptanceBaseTick=tick;
tick=function(){acceptanceBaseTick();acceptanceObserveDay()};
function acceptanceSummary(){let state=acceptanceState();if(!state.active)return{active:false,seed:world.seed,knownSeeds:[...ACCEPTANCE_REGRESSION_SEEDS],windows:{fiveMinuteDays:ACCEPTANCE_FIVE_MINUTE_DAYS,thirtyMinuteDays:ACCEPTANCE_THIRTY_MINUTE_DAYS}};let five=state.fiveMinute||acceptanceFiveMinuteResult(state),thirty=state.thirtyMinute||acceptanceThirtyMinuteResult(state,five);return{active:true,seed:world.seed,knownSeed:ACCEPTANCE_REGRESSION_SEEDS.includes(String(world.seed)),startedDay:state.startedDay,currentDay:Math.floor(clock.day),counters:{...state.counters},fiveMinute:five,thirtyMinute:thirty,knownSeeds:[...ACCEPTANCE_REGRESSION_SEEDS],windows:{fiveMinuteDays:ACCEPTANCE_FIVE_MINUTE_DAYS,thirtyMinuteDays:ACCEPTANCE_THIRTY_MINUTE_DAYS}}}
function runAcceptanceSuite(seed,days=ACCEPTANCE_THIRTY_MINUTE_DAYS){let requestedDays=Math.max(1,Math.floor(days)),started=acceptanceNow(),generationStarted=acceptanceNow();try{clock={day:1,speed:8,acc:0};director={queue:[],until:0,suspend:0};world=makeWorld(String(seed));let generationMs=Math.round((acceptanceNow()-generationStarted)*10)/10;world.headless=true;firstEntries();startAcceptanceTracking();for(let i=0;i<requestedDays;i++){tick();director.queue.length=0}let summary=acceptanceSummary();clock.speed=0;let durationMs=Math.round((acceptanceNow()-started)*10)/10,generation={durationMs:generationMs,limitMs:ACCEPTANCE_GENERATION_LIMIT_MS,passed:generationMs<=ACCEPTANCE_GENERATION_LIMIT_MS};return{seed:String(seed),knownSeed:ACCEPTANCE_REGRESSION_SEEDS.includes(String(seed)),requestedDays,durationMs,generation,passed:generation.passed&&(requestedDays>=ACCEPTANCE_THIRTY_MINUTE_DAYS?summary.thirtyMinute.passed:requestedDays>=ACCEPTANCE_FIVE_MINUTE_DAYS?summary.fiveMinute.passed:true),fiveMinute:summary.fiveMinute,thirtyMinute:summary.thirtyMinute,counters:summary.counters,stability:stabilitySummary(),knownSeeds:[...ACCEPTANCE_REGRESSION_SEEDS],windows:summary.windows}}catch(error){return{seed:String(seed),knownSeed:ACCEPTANCE_REGRESSION_SEEDS.includes(String(seed)),requestedDays,durationMs:Math.round((acceptanceNow()-started)*10)/10,generation:{durationMs:Math.round((acceptanceNow()-generationStarted)*10)/10,limitMs:ACCEPTANCE_GENERATION_LIMIT_MS,passed:false},passed:false,error:String(error?.stack||error?.message||error),knownSeeds:[...ACCEPTANCE_REGRESSION_SEEDS],windows:{fiveMinuteDays:ACCEPTANCE_FIVE_MINUTE_DAYS,thirtyMinuteDays:ACCEPTANCE_THIRTY_MINUTE_DAYS}}}}
