const CHARACTER_LIMIT=48;
const CHARACTER_ROLES=['monarch','heir','noble','commander','merchant','clergy'];
const CHARACTER_SURNAMES='Vale Thornmere Ashford Raven Holt Fenwick Stonebridge Alder Merewatch'.split(' ');
function characterState(){return world.characterState||(world.characterState={nextId:1,registry:[]})}
function characterName(){return`${pick(hisR,ANNAL_NAMES)} ${pick(hisR,CHARACTER_SURNAMES)}`}
function createCharacter(role,home,houseId=null,age=irnd(hisR,18,62),status='alive'){let state=characterState();if(state.registry.length>=CHARACTER_LIMIT)return null;let c={id:`${world.seed}:c${state.nextId++}`,name:characterName(),age:clamp(age,0,100),role,status,homeId:(home&&home.id)??0,houseId:Number.isInteger(houseId)?houseId:null,bornDay:Math.floor(clock.day-age*360),statusDay:Math.floor(clock.day)};state.registry.push(c);return c}
function initCharacters(){let state=characterState();if(state.registry.length)return state.registry;let cap=world.settlements[0],monarch=createCharacter('monarch',cap,0,irnd(hisR,34,58)),heir=createCharacter('heir',cap,0,irnd(hisR,16,30));for(let i=1;i<world.houses.length;i++)createCharacter(i%2?'noble':'commander',world.settlements[world.houses[i].seatSettlement],i,irnd(hisR,24,64));createCharacter('merchant',world.settlements.find(s=>s.site.harbour)||world.settlements[1]||cap,null,irnd(hisR,28,61));createCharacter('clergy',cap,null,irnd(hisR,30,72));world.story.monarchId=monarch.id;world.story.heirId=heir.id;return state.registry}
function characterById(id){return characterState().registry.find(c=>c.id===id)||null}
function characterForRole(role,status='alive'){return characterState().registry.find(c=>c.role===role&&(!status||c.status===status))||null}
function charactersAt(settlementId){return characterState().registry.filter(c=>c.homeId===settlementId)}
function characterHome(c){return world.settlements[c.homeId]||world.settlements[0]}
function characterHouse(c){return Number.isInteger(c.houseId)?world.houses[c.houseId]:null}
function characterSummary(c){return{id:c.id,name:c.name,age:c.age,role:c.role,status:c.status,home:characterHome(c).name,house:characterHouse(c)?.name||null,bornDay:c.bornDay,statusDay:c.statusDay}}
function setCharacterStatus(c,status,reason){if(!c||c.status===status)return c;c.status=status;c.statusDay=Math.floor(clock.day);let home=characterHome(c);eventChronicle('character-status',status==='dead'?9:7,home,`${c.name}, ${c.role} of ${home.name}, was declared ${status}; ${reason}.`,{class:status==='dead'?'fate':'crown',kind:status,causes:[reason],consequences:[`${c.name} remains ${status}`],participants:[c.id,c.name],source:'character-system'});return c}
function appointCharacter(c,role,home=characterHome(c)){if(!c)return null;c.role=role;c.homeId=home.id;c.status='alive';c.statusDay=Math.floor(clock.day);eventChronicle('appointment',7,home,`${c.name} was appointed ${role} at ${home.name}; the office thereafter carried a known face.`,{class:'crown',kind:'appointment',causes:['office required a named holder'],consequences:[`${c.name} became ${role}`],participants:[c.id,c.name],source:'character-system'});return c}
function birthCharacter(home,houseId=null){let c=createCharacter('noble',home,houseId,0);if(c)eventChronicle('birth',6,home,`${c.name} was born in ${home.name}; the household entered the child among the living heirs of memory.`,{class:'fate',kind:'birth',causes:['birth'],consequences:['a named life entered the record'],participants:[c.id,c.name],source:'character-system'});return c}
