const DYNASTY_LIMIT=12,REIGN_LIMIT=64;
function dynastyState(){return world.dynastyState||(world.dynastyState={nextId:1,registry:[],reigns:[]})}
function familyInit(c){c.parentIds=c.parentIds||[];c.childIds=c.childIds||[];c.siblingIds=c.siblingIds||[];c.spouseId=c.spouseId||null;c.dynastyId=c.dynastyId||null;c.claimStrength=Number.isFinite(c.claimStrength)?c.claimStrength:0;c.legitimacy=Number.isFinite(c.legitimacy)?c.legitimacy:50;return c}
function linkParent(parent,child){if(!parent||!child)return;familyInit(parent);familyInit(child);if(!parent.childIds.includes(child.id))parent.childIds.push(child.id);if(!child.parentIds.includes(parent.id))child.parentIds.push(parent.id);for(const id of parent.childIds){if(id===child.id)continue;let sib=characterById(id);if(sib&&!child.siblingIds.includes(id))child.siblingIds.push(id);if(sib&&!sib.siblingIds.includes(child.id))sib.siblingIds.push(child.id)}}
function linkSpouses(a,b){if(a&&b){familyInit(a);familyInit(b);a.spouseId=b.id;b.spouseId=a.id}}
function createDynasty(name,founder){let s=dynastyState();if(s.registry.length>=DYNASTY_LIMIT)return null;let d={id:`${world.seed}:dyn${s.nextId++}`,name,status:'ruling',founderId:founder.id,memberIds:[],reignIds:[],createdDay:Math.floor(clock.day),displacedDay:null,extinctDay:null};s.registry.push(d);return d}
function addToDynasty(d,c,claim=40,legitimacy=60){if(!d||!c)return;c=familyInit(c);c.dynastyId=d.id;c.claimStrength=claim;c.legitimacy=legitimacy;if(!d.memberIds.includes(c.id))d.memberIds.push(c.id)}
function dynastyById(id){return dynastyState().registry.find(d=>d.id===id)||null}
function initDynasties(){initCharacters();let s=dynastyState();if(s.registry.length)return s.registry;let monarch=characterById(world.story.monarchId),heir=characterById(world.story.heirId),cap=world.settlements[0],d=createDynasty(`House ${monarch.name.split(' ').slice(-1)[0]}`,monarch),spouse=createCharacter('noble',cap,0,irnd(hisR,28,55)),younger=createCharacter('noble',cap,0,irnd(hisR,8,20));addToDynasty(d,monarch,100,90);addToDynasty(d,heir,82,84);if(spouse){addToDynasty(d,spouse,28,70);linkSpouses(monarch,spouse);linkParent(monarch,heir);linkParent(spouse,heir)}if(younger){addToDynasty(d,younger,55,76);linkParent(monarch,younger);if(spouse)linkParent(spouse,younger)}for(const c of characterState().registry.filter(c=>c.houseId>0)){let nd=s.registry.find(x=>x.name===world.houses[c.houseId].name)||createDynasty(world.houses[c.houseId].name,c);if(nd){nd.status='noble';addToDynasty(nd,c,35+irnd(hisR,0,24),50+irnd(hisR,0,29))}}return s.registry}
function familyTerm(a,b){if(!a||!b)return null;familyInit(a);familyInit(b);if(a.spouseId===b.id)return a.status==='dead'?'widow':'spouse';if(a.parentIds.includes(b.id))return'child';if(a.childIds.includes(b.id))return'parent';if(a.siblingIds.includes(b.id))return'sibling';let child=a.childIds.map(characterById).find(c=>{if(!c)return false;familyInit(c);return c.childIds.includes(b.id)});return child?'grandparent':null}
function claimScore(c){let house=Number.isInteger(c.houseId)?world.houses[c.houseId]:null,home=characterHome(c);return c.claimStrength+c.legitimacy+(house?house.loyalty*.35:18)-home.unrest*.22+(c.age>=18?12:-20)}
function successionCandidates(){initDynasties();return characterState().registry.filter(c=>c.status==='alive'&&['heir','noble','commander'].includes(c.role)).map(c=>({c,score:claimScore(c)})).sort((a,b)=>b.score-a.score||a.c.id.localeCompare(b.c.id))}
function recordReign(monarch,predecessor,basis,contested,claim){let s=dynastyState(),r={id:`${world.seed}:reign${s.reigns.length+1}`,monarchId:monarch.id,predecessorId:predecessor&&predecessor.id||null,dynastyId:monarch.dynastyId,basis,contested,claim,startDay:Math.floor(clock.day)};s.reigns.push(r);if(s.reigns.length>REIGN_LIMIT)s.reigns.shift();let d=dynastyById(monarch.dynastyId);if(d&&!d.reignIds.includes(r.id))d.reignIds.push(r.id);return r}
function dynastySummary(d){return{id:d.id,name:d.name,status:d.status,founderId:d.founderId,memberIds:[...d.memberIds],reignIds:[...d.reignIds],createdDay:d.createdDay,displacedDay:d.displacedDay,extinctDay:d.extinctDay}}
