const ECONOMY_GOODS=['grain','fish','timber','ore','tools','cloth','wine'],TRADE_LIMIT=48;
function economyState(){return world.economyState||(world.economyState={treasury:900,taxRate:.08,nextTradeId:1,trades:[],completed:0,taxCollected:0})}
function initSettlementEconomy(s){s.stores=s.stores||{};s.prices=s.prices||{};let near=world.resources.filter(r=>Math.hypot(r.x-s.x,r.z-s.z)<650),count=t=>near.filter(r=>r.type===t).length,capital=s.type==='capital';let initial={grain:s.stores.grain??Math.max(120,s.pop*.55+count('farmland')*90),fish:s.stores.fish??Math.max(40,s.pop*.12+count('fishing')*55),timber:80+count('forest')*55,ore:35+count('ore')*50,tools:capital?90:35,cloth:capital?100:25,wine:capital?75:18};for(const g of ECONOMY_GOODS){s.stores[g]=clamp(Number.isFinite(s.stores[g])?s.stores[g]:initial[g],0,Math.max(300,s.pop*1.8));s.prices[g]=1}s.economy={lastShortageDay:-999,lastTradeDay:-999,produced:{},consumed:{}};return s}
function initEconomy(){let state=economyState();for(const s of world.settlements)if(!s.economy)initSettlementEconomy(s);return state}
function goodNeed(s,g){let rates={grain:.075,fish:.018,timber:.004,ore:.0015,tools:.0025,cloth:.002,wine:.0015};return Math.max(1,s.pop*rates[g])}
function productionFor(s){let rs=s.site.resources||[],capital=s.type==='capital',rain=world.weather==='Rain'?1.12:world.weather==='Storm'?.78:1,dry=world.drought?.52:1;return{grain:s.pop*.014*s.fert*rain*dry+(rs.includes('farmland')?18:0),fish:s.pop*.003*(s.site.waterAccess!=='none'?1.6:.35)+(rs.includes('fishing')?12:0),timber:(rs.includes('forest')?16:2)+s.pop*.001,ore:(rs.includes('ore')?12:1)+s.pop*.0005,tools:Math.min(s.stores.ore*.035,s.stores.timber*.02)+(capital?4:1),cloth:capital?5+s.pop*.0015:s.type==='town'?2:0,wine:capital?3+s.pop*.001:0}}
function updatePrices(s){for(const g of ECONOMY_GOODS){let need=goodNeed(s,g)*25,ratio=s.stores[g]/Math.max(1,need);s.prices[g]=Math.round(clamp(2.4-ratio,0.35,3.5)*100)/100}}
function roadBetween(a,b){return world.roads.find(r=>(r.a===a.id&&r.b===b.id)||(r.a===b.id&&r.b===a.id))||null}
function bestTrade(){let best=null;for(const from of world.settlements)for(const to of world.settlements){if(from===to)continue;let road=roadBetween(from,to);if(!road)continue;for(const good of ECONOMY_GOODS){let surplus=from.stores[good]-goodNeed(from,good)*18,deficit=goodNeed(to,good)*14-to.stores[good],spread=to.prices[good]-from.prices[good];if(surplus<=4||deficit<=4||spread<.22)continue;let score=Math.min(surplus,deficit)*spread/(1+road.pts.length*.02);if(!best||score>best.score)best={from,to,good,road,score,amount:clamp(Math.floor(Math.min(surplus,deficit,40+score)),5,120)}}}return best}
function launchTrade(candidate){if(!candidate)return null;let state=economyState(),{from,to,good,road,amount}=candidate;from.stores[good]=clamp(from.stores[good]-amount,0,from.pop*1.8);let reversed=road.a!==from.id,points=(reversed?[...road.pts].reverse():road.pts).map(p=>({x:p.x,y:p.y,z:p.z})),trade={id:`${world.seed}:trade${state.nextTradeId++}`,fromId:from.id,toId:to.id,good,amount,departDay:Math.floor(clock.day),arrivalDay:Math.floor(clock.day+Math.max(8,points.length*.7)),points,progress:0,status:'travelling'};state.trades.push(trade);if(state.trades.length>TRADE_LIMIT)state.trades.shift();from.economy.lastTradeDay=clock.day;eventChronicle('trade-caravan',6,from,`${amount} measures of ${good} left ${from.name} for ${to.name}, because the price gap made the road worth guarding.`,{class:'trade',kind:'trade',participants:[from.name,to.name],causes:[`${good} surplus at ${from.name}`,`${good} deficit at ${to.name}`],consequences:['a caravan entered the road'],source:'economy-system'});return trade}
function completeTrades(){let state=economyState();for(const t of state.trades){if(t.status!=='travelling')continue;t.progress=clamp((clock.day-t.departDay)/Math.max(1,t.arrivalDay-t.departDay),0,1);if(t.progress<1)continue;let to=world.settlements[t.toId],value=t.amount*(to.prices[t.good]||1),tax=value*state.taxRate;t.status='arrived';to.stores[t.good]=clamp(to.stores[t.good]+t.amount,0,to.pop*1.8);state.treasury=clamp(state.treasury+tax,0,100000);state.taxCollected+=tax;state.completed++;eventChronicle('trade-arrival',7,to,`${t.amount} measures of ${t.good} reached ${to.name}; the delivery eased scarcity and paid ${tax.toFixed(1)} crowns in customs.`,{class:'trade',kind:'trade',participants:[world.settlements[t.fromId].name,to.name],causes:['a price-driven caravan completed its road'],consequences:['local stores increased','crown treasury increased'],source:'economy-system'})}}
function economyDay(){initEconomy();let state=economyState();for(const s of world.settlements){let prod=productionFor(s);s.economy.produced=prod;for(const g of ECONOMY_GOODS){let use=goodNeed(s,g),made=prod[g]||0;s.stores[g]=clamp(s.stores[g]+made-use,0,Math.max(300,s.pop*1.8));s.economy.consumed[g]=use}updatePrices(s);let foodDays=(s.stores.grain+.8*s.stores.fish)/Math.max(1,goodNeed(s,'grain')+goodNeed(s,'fish'));if(foodDays<4){s.hunger=clamp(s.hunger+.45*(4-foodDays),0,100);s.unrest=clamp(s.unrest+.25*(4-foodDays),0,100);if(clock.day-s.economy.lastShortageDay>90){s.economy.lastShortageDay=clock.day;eventChronicle('market-shortage',8,s,`${s.name} held fewer than ${foodDays.toFixed(1)} days of food; prices rose, hunger followed, and the lesser households began to leave.`,{class:'trade',kind:'famine',causes:['grain and fish below local need'],consequences:['food prices increased','hunger and unrest increased'],participants:[s.name],source:'economy-system'})}}}completeTrades();if(Math.floor(clock.day)%18===0&&state.trades.filter(t=>t.status==='travelling').length<6)launchTrade(bestTrade());state.treasury=clamp(state.treasury-.08*world.settlements.length,0,100000)}
const economyBaseTick=tick,economyBaseAct=act;
tick=function(){economyBaseTick();economyDay()};
act=function(a){economyBaseAct(a);if(a==='grain'){let s=pressure(),state=economyState(),cost=Math.min(state.treasury,s.pop*.025);state.treasury=clamp(state.treasury-cost,0,100000);s.stores.grain=clamp(s.stores.grain+cost*3,0,s.pop*1.8)}};
function economySummary(){initEconomy();let state=economyState();return{goods:[...ECONOMY_GOODS],treasury:Math.round(state.treasury*100)/100,taxRate:state.taxRate,tradeLimit:TRADE_LIMIT,trades:state.trades.length,travelling:state.trades.filter(t=>t.status==='travelling').length,completed:state.completed,taxCollected:Math.round(state.taxCollected*100)/100,settlements:world.settlements.map(s=>({id:s.id,name:s.name,stores:Object.fromEntries(ECONOMY_GOODS.map(g=>[g,Math.round(s.stores[g]*10)/10])),prices:{...s.prices},hunger:Math.round(s.hunger*10)/10,unrest:Math.round(s.unrest*10)/10}))}}
