;const LIFE_ARC_LIMIT=16,LIFE_ARC_HISTORY_LIMIT=48,LIFE_ARC_GENERIC_EPITHETS=new Set(['the Steadfast','the Ledger-Keeper','the Far-Seeing','the Remembered']);
const LIFE_ARC_EPITHETS={battle:'the Battle-Born','dragon-raid':'the Wyrm-Witness',fire:'the Ash-Marked',flood:'the Flood-Warden',earthquake:'the Stone-Survivor','plague-outbreak':'the Fever-Wise','plague-spread':'the Fever-Wise','grain-relief':'the Open-Handed',festival:'the Bell-Keeper',drought:'the Rainless','contested-succession':'the Crown-Contested'};
function lifeArcState(){return world.lifeArcState||(world.lifeArcState={initialized:false,initialLiving:0,nextArcId:1,nextMarriageId:1,nextBirthId:1,nextInheritanceId:1,arcs:[],marriages:[],births:[],inheritances:[],epithets:[],hazardDeaths:{age:0,battle:0,plague:0,assassination:0,disaster:0},nextMarriageDay:180,nextBirthDay:540,nextGrudgeDay:360,inSuccession:false,forcedHazard:false})}
function lifeArcPush(list,item,limit=LIFE_ARC_HISTORY_LIMIT){list.push(item);if(list.length>limit)list.splice(0,list.length-limit);return item}
function lifeArcLiving(){return characterState().registry.filter(c=>c.status==='alive')}
function lifeArcCloseFamily(a,b){familyInit(a);familyInit(b);return a.id===b.id||a.parentIds.includes(b.id)||a.childIds.includes(b.id)||a.siblingIds.includes(b.id)}
function lifeArcMarriageEligible(c){return c&&c.status==='alive'&&c.age>=18&&c.age<=62&&!c.spouseId&&['monarch','heir','noble','commander','merchant','clergy','high priest','master of coin','smith','prophet'].includes(c.role)}
function lifeArcMarriageScore(a,b){if(lifeArcCloseFamily(a,b))return-Infinity;let ah=characterHouse(a),bh=characterHouse(b),cross=ah&&bh&&ah.id!==bh.id,claim=Math.min(30,((a.claimStrength||0)+(b.claimStrength||0))*.12),age=Math.max(0,18-Math.abs(a.age-b.age)*.3),alliance=cross?58:ah||bh?12:6,pressure=(ah?100-ah.loyalty:0)+(bh?100-bh.loyalty:0);return alliance+claim+age+pressure*.12}
function lifeArcMarriagePairs(){let people=lifeArcLiving().filter(lifeArcMarriageEligible),pairs=[];for(let i=0;i<people.length;i++)for(let j=i+1;j<people.length;j++){let score=lifeArcMarriageScore(people[i],people[j]);if(Number.isFinite(score))pairs.push({a:people[i],b:people[j],score})}return pairs.sort((x,y)=>y.score-x.score||x.a.id.localeCompare(y.a.id)||x.b.id.localeCompare(y.b.id))}
function arrangeAllianceMarriage(force=false){initDynasties();let state=lifeArcState(),pair=lifeArcMarriagePairs()[0];if(!pair||(!force&&pair.score<28))return null;let {a,b,score}=pair;linkSpouses(a,b);let ah=characterHouse(a),bh=characterHouse(b),cross=ah&&bh&&ah.id!==bh.id;if(ah){ah.loyalty=clamp(ah.loyalty+(cross?5:2),0,100);ah.allianceHouseIds=ah.allianceHouseIds||[];if(bh&&!ah.allianceHouseIds.includes(bh.id))ah.allianceHouseIds.push(bh.id)}if(bh){bh.loyalty=clamp(bh.loyalty+(cross?5:2),0,100);bh.allianceHouseIds=bh.allianceHouseIds||[];if(ah&&!bh.allianceHouseIds.includes(ah.id))bh.allianceHouseIds.push(ah.id)}a.grudges=(a.grudges||[]).filter(g=>g.characterId!==b.id);b.grudges=(b.grudges||[]).filter(g=>g.characterId!==a.id);let marriage=lifeArcPush(state.marriages,{id:`${world.seed}:marriage${state.nextMarriageId++}`,day:Math.floor(clock.day),aId:a.id,bId:b.id,houseIds:[a.houseId,b.houseId].filter(Number.isInteger),score:Math.round(score),lastBirthDay:null});eventChronicle('marriage-alliance',8,characterHome(a),`${a.name} and ${b.name} were joined in marriage; ${cross?`${ah.name} and ${bh.name} gained a living bond where loyalty had previously rested only on oaths.`:'their household joined claims, property and succession.'}`,{class:'crown',kind:'marriage',participants:[a.id,a.name,b.id,b.name,ah?.name,bh?.name].filter(Boolean),causes:[cross?'alliance value between great houses':'household succession required a settled union'],consequences:['two notable families were linked',cross?'house loyalty improved':'a household claim strengthened'],source:'life-arc-system',metadata:{marriageId:marriage.id}});return marriage}
function lifeArcDynasticParent(a,b){return [a,b].sort((x,y)=>claimScore(y)-claimScore(x)||x.id.localeCompare(y.id))[0]}
function recordAllianceBirth(force=false){initDynasties();let state=lifeArcState(),choices=state.marriages.map(m=>({m,a:characterById(m.aId),b:characterById(m.bId)})).filter(x=>x.a?.status==='alive'&&x.b?.status==='alive'&&Math.min(x.a.age,x.b.age)<=52&&(x.a.childIds||[]).length<4&&(x.b.childIds||[]).length<4&&clock.day-(x.m.lastBirthDay||x.m.day)>=270);if(!choices.length||characterState().registry.length>=NOTABLE_LIMIT)return null;let choice=choices.sort((x,y)=>(x.m.lastBirthDay||x.m.day)-(y.m.lastBirthDay||y.m.day))[0];if(!force&&hisR()>.48)return null;let {m,a,b}=choice,parent=lifeArcDynasticParent(a,b),home=characterHome(parent),child=createCharacter('noble',home,parent.houseId,0);if(!child)return null;familyInit(child);linkParent(a,child);linkParent(b,child);let dynasty=dynastyById(parent.dynastyId);if(dynasty)addToDynasty(dynasty,child,clamp(30+(a.houseId!==b.houseId?15:5),0,100),68);child.agenda='secure the succession';m.lastBirthDay=Math.floor(clock.day);let birth=lifeArcPush(state.births,{id:`${world.seed}:alliance-birth${state.nextBirthId++}`,day:Math.floor(clock.day),childId:child.id,parentIds:[a.id,b.id],marriageId:m.id,dynastyId:child.dynastyId});eventChronicle('alliance-birth',7,home,`${child.name} was born to the union of ${a.name} and ${b.name}; the child joined two remembered households and widened the succession.`,{class:'crown',kind:'birth',participants:[child.id,child.name,a.id,a.name,b.id,b.name].filter(Boolean),causes:['a recorded marriage produced an heir'],consequences:['a named child entered both family rolls','the succession widened'],source:'life-arc-system',metadata:{birthId:birth.id,marriageId:m.id}});return birth}
function lifeArcHeir(c){familyInit(c);let children=c.childIds.map(characterById).filter(x=>x?.status==='alive').sort((a,b)=>claimScore(b)-claimScore(a));if(children.length)return children[0];let spouse=c.spouseId&&characterById(c.spouseId);if(spouse?.status==='alive')return spouse;return c.siblingIds.map(characterById).find(x=>x?.status==='alive')||null}
function recordInheritance(c){if(!c||c.inheritanceRecorded||c.role==='monarch')return null;let heir=lifeArcHeir(c);if(!heir)return null;c.inheritanceRecorded=true;familyInit(heir);let transfer=Math.max(6,Math.round((c.claimStrength||20)*.22));heir.claimStrength=clamp((heir.claimStrength||0)+transfer,0,100);if(c.agenda&&(!heir.agenda||heir.agenda==='secure the succession'))heir.agenda=c.agenda;let state=lifeArcState(),entry=lifeArcPush(state.inheritances,{id:`${world.seed}:inheritance${state.nextInheritanceId++}`,day:Math.floor(clock.day),fromId:c.id,toId:heir.id,claimTransferred:transfer,role:c.role});eventChronicle('inheritance',7,characterHome(heir),`${heir.name} inherited the remembered claims of ${c.name}; property, obligations and an unfinished agenda passed with the household record.`,{class:'crown',kind:'inheritance',participants:[c.id,c.name,heir.id,heir.name],causes:[`${c.name} died`],consequences:[`${heir.name} gained ${transfer} claim strength`],source:'life-arc-system',metadata:{inheritanceId:entry.id}});return entry}
function lifeArcDeathCategory(reason=''){let text=String(reason).toLowerCase();if(/age|old|long account/.test(text))return'age';if(/battle|skirmish|wounds|war/.test(text))return'battle';if(/plague|fever|pestilence/.test(text))return'plague';if(/assassin|murder|poison|grudge/.test(text))return'assassination';if(/fire|flood|earthquake|storm|dragon|disaster|drought/.test(text))return'disaster';return null}
function lifeArcAssignEpithet(c,type){if(!c)return null;let epithet=LIFE_ARC_EPITHETS[type];if(!epithet)return null;if(c.epithet&&!LIFE_ARC_GENERIC_EPITHETS.has(c.epithet))return c.epithet;c.epithet=epithet;let state=lifeArcState();lifeArcPush(state.epithets,{day:Math.floor(clock.day),characterId:c.id,type,epithet},LIFE_ARC_HISTORY_LIMIT);return epithet}
function lifeArcEventCharacters(ev){let out=[];for(const p of ev.participants||[]){let c=characterById(p)||characterState().registry.find(x=>x.name===String(p));if(c&&!out.some(x=>x.id===c.id))out.push(c)}return out}
function observeLifeArcEvent(ev){if(!ev)return;let chars=lifeArcEventCharacters(ev),type=ev.type;if(!chars.length&&LIFE_ARC_EPITHETS[type]){let cls=ev.metadata?.chronicle?.class||annalClass(type),home=world.settlements.find(s=>s.id===ev.location?.entityId)||world.settlements.find(s=>s.name===ev.location?.name)||world.settlements[0],c=notableByNeed(cls,home);if(c){chars=[c];if(!ev.participants.includes(c.id))ev.participants.push(c.id,c.name)}}for(const c of chars){c.lifeEventIds=c.lifeEventIds||[];if(!c.lifeEventIds.includes(ev.id)){c.lifeEventIds.push(ev.id);if(c.lifeEventIds.length>24)c.lifeEventIds.shift();c.appearances=(c.appearances||0)+1}lifeArcAssignEpithet(c,type)}let arcId=ev.metadata?.arcId;if(arcId){let arc=lifeArcState().arcs.find(a=>a.id===arcId);if(arc&&!arc.eventIds.includes(ev.id))arc.eventIds.push(ev.id)}}
const lifeArcBaseEmitWorldEvent=emitWorldEvent;
emitWorldEvent=function(type,details={}){let ev=lifeArcBaseEmitWorldEvent(type,details);observeLifeArcEvent(ev);return ev};
function lifeArcCreateStory(){let state=lifeArcState();if(state.arcs.length>=LIFE_ARC_LIMIT)return state.arcs[0]||null;let candidates=lifeArcLiving().filter(c=>['master of coin','merchant','smith','high priest'].includes(c.role)&&c.age<58).sort((a,b)=>a.age-b.age||a.id.localeCompare(b.id)),anchor=candidates[0]||lifeArcLiving().filter(c=>c.role!=='monarch'&&c.role!=='heir').sort((a,b)=>a.age-b.age)[0];if(!anchor)return null;anchor.arcProtectedUntil=Math.floor(clock.day)+1800;let arc={id:`${world.seed}:arc${state.nextArcId++}`,characterId:anchor.id,theme:anchor.role==='master of coin'||anchor.role==='merchant'?'the realm ledger':anchor.role==='smith'?'the rebuilding of the realm':'the interpretation of omens',startedDay:Math.floor(clock.day),stage:0,eventIds:[],completedDay:null};state.arcs.push(arc);return arc}
function lifeArcEmitStage(arc,stage){let c=characterById(arc.characterId);if(!c||c.status!=='alive')return false;let home=characterHome(c),econ=economyState(),pressureTown=pressure(),texts=[`${c.name}, ${c.role} of ${home.name}, was charged to keep ${arc.theme}; the office tied one named life to the realm's changing fortunes.`,`${c.name} returned to the council with the second account of ${arc.theme}; treasury stood at ${Math.round(econ.treasury)} crowns while ${pressureTown.name} carried the greatest hunger and unrest.`,`${c.name} closed the third account of ${arc.theme}; the Chronicle had followed the same life from appointment through consequence, and thereafter called ${c.name} the Realm-Keeper.`];if(stage===2){c.epithet='the Realm-Keeper';lifeArcPush(lifeArcState().epithets,{day:Math.floor(clock.day),characterId:c.id,type:'life-arc',epithet:c.epithet})}eventChronicle(`life-arc-${stage===0?'charge':stage===1?'reckoning':'legacy'}`,stage===2?8:7,home,texts[stage],{class:stage===1?'trade':'crown',kind:'life-arc',participants:[c.id,c.name],causes:[stage===0?'a named office received a continuing charge':'the earlier charge remained unresolved'],consequences:[stage===2?'a recurring life arc reached a remembered outcome':'the same notable remained connected to the same concern'],source:'life-arc-system',metadata:{arcId:arc.id,arcStage:stage,theme:arc.theme}});arc.stage=stage+1;if(stage===2)arc.completedDay=Math.floor(clock.day);return true}
function initLifeArcs(){initDynasties();let state=lifeArcState();if(state.initialized)return state;state.initialized=true;state.initialLiving=lifeArcLiving().length;let arc=lifeArcCreateStory();if(arc)lifeArcEmitStage(arc,0);return state}
function advanceLifeArcStory(){let state=initLifeArcs(),arc=state.arcs[0];if(!arc||arc.stage>=3)return;let elapsed=clock.day-arc.startedDay;if(arc.stage===1&&elapsed>=720)lifeArcEmitStage(arc,1);if(arc.stage===2&&elapsed>=1440)lifeArcEmitStage(arc,2)}
function evolveLifeArcGrudges(){for(const c of lifeArcLiving()){c.grudges=(c.grudges||[]).filter(g=>characterById(g.characterId));for(const g of c.grudges){let other=characterById(g.characterId);if(!other)continue;let allied=c.spouseId===other.id||Number.isInteger(c.houseId)&&characterHouse(c)?.allianceHouseIds?.includes(other.houseId);g.strength=clamp(g.strength+(allied?-8:hisR()<.45?3:-1),0,100)}c.grudges=c.grudges.filter(g=>g.strength>5)}}
function applyNotableHazard(c,category,context={},force=false){if(!c||c.status!=='alive')return false;let state=lifeArcState();if(c.arcProtectedUntil>clock.day&&!force)return false;let chance={age:.35,battle:.28,plague:clamp((context.rate||.04)*1.8,.03,.25),assassination:.14,disaster:.12}[category]||0;if(!force&&hisR()>chance)return false;let home=characterHome(c),reason={age:'age closed the long account',battle:`wounds received in battle near ${context.place||home.name}`,plague:`plague carried along the road into ${home.name}`,assassination:`assassination after ${context.reason||'a bitter grudge'}`,disaster:`${context.type||'a sudden disaster'} struck the household at ${home.name}`}[category]||'an unknown hazard';state.forcedHazard=force;try{setCharacterStatus(c,'dead',reason)}finally{state.forcedHazard=false}return c.status==='dead'}
function advanceLifeArcHazards(){let state=initLifeArcs();if(Math.floor(clock.day)%30===0){for(const s of world.settlements){let rate=s.disease?s.disease.infected/Math.max(1,s.pop):0;if(rate<.025)continue;let candidates=charactersAt(s.id).filter(c=>c.status==='alive'&&c.role!=='monarch'&&c.role!=='heir');if(candidates.length)applyNotableHazard(pick(hisR,candidates),'plague',{rate})}}if(Math.floor(clock.day)%90===0){let plots=[];for(const source of lifeArcLiving())for(const g of source.grudges||[]){let target=characterById(g.characterId);if(target?.status==='alive'&&g.strength>=68&&target.role!=='monarch'&&target.role!=='heir')plots.push({source,target,g})}if(plots.length&&hisR()<.08){let p=plots.sort((a,b)=>b.g.strength-a.g.strength)[0];applyNotableHazard(p.target,'assassination',{reason:p.g.reason})}}if(clock.day>=state.nextMarriageDay){arrangeAllianceMarriage(state.marriages.length===0);state.nextMarriageDay+=720}if(clock.day>=state.nextBirthDay){recordAllianceBirth(state.births.length===0);state.nextBirthDay+=360}if(clock.day>=state.nextGrudgeDay){evolveLifeArcGrudges();state.nextGrudgeDay+=360}}
const lifeArcBaseSetStatus=setCharacterStatus,lifeArcBaseChangeReign=changeReign;
changeReign=function(){let state=lifeArcState();state.inSuccession=true;try{return lifeArcBaseChangeReign()}finally{state.inSuccession=false}};
setCharacterStatus=function(c,status,reason){let state=lifeArcState();if(c&&status==='dead'&&c.arcProtectedUntil>clock.day&&!state.forcedHazard)return c;let wasAlive=c?.status==='alive',wasMonarch=wasAlive&&c.id===world.story.monarchId,result=lifeArcBaseSetStatus(c,status,reason);if(wasAlive&&result?.status==='dead'&&!result.lifeArcDeathRecorded){result.lifeArcDeathRecorded=true;let category=lifeArcDeathCategory(reason);result.deathCategory=category;if(category)state.hazardDeaths[category]=(state.hazardDeaths[category]||0)+1;lifeArcAssignEpithet(result,category==='battle'?'battle':category==='disaster'?'fire':category==='plague'?'plague-outbreak':null);recordInheritance(result);if(wasMonarch&&!state.inSuccession)changeReign()}return result};
const lifeArcBaseAct=act;
act=function(kind){let target=pressure(),result=lifeArcBaseAct(kind);if(['fire','drought'].includes(kind)){let candidates=charactersAt(target.id).filter(c=>c.status==='alive'&&c.role!=='monarch'&&c.role!=='heir');if(candidates.length)applyNotableHazard(pick(hisR,candidates),'disaster',{type:kind==='fire'?'a great fire':'the long drought'})}return result};
const lifeArcBaseFirstEntries=firstEntries;
firstEntries=function(){lifeArcBaseFirstEntries();initLifeArcs()};
const lifeArcBaseTick=tick;
tick=function(){lifeArcBaseTick();advanceLifeArcStory();advanceLifeArcHazards()};
function lifeArcSummary(){let state=initLifeArcs(),people=characterState().registry.map(characterSummary),arcs=state.arcs.map(a=>({...a,character:characterById(a.characterId)?.name||a.characterId,eventCount:a.eventIds.length}));return{initialLiving:state.initialLiving,living:people.filter(c=>c.status==='alive').length,registry:people.length,limit:NOTABLE_LIMIT,marriages:state.marriages.map(x=>({...x})),births:state.births.map(x=>({...x})),inheritances:state.inheritances.map(x=>({...x})),hazardDeaths:{...state.hazardDeaths},epithets:state.epithets.map(x=>({...x})),arcs,recurringArcs:arcs.filter(a=>a.eventCount>=3),familyCoverage:people.filter(c=>c.spouseId||c.parentIds.length||c.childIds.length).length,roles:people.reduce((out,c)=>(out[c.role]=(out[c.role]||0)+1,out),{})}}
function runNotableAcceptance(seed,days=ACCEPTANCE_THIRTY_MINUTE_DAYS){clock={day:1,speed:8,acc:0};director={queue:[],until:0,suspend:0};world=makeWorld(String(seed));world.headless=true;firstEntries();let initial=lifeArcSummary();for(let i=0;i<Math.max(1,Math.floor(days));i++){tick();director.queue.length=0}let final=lifeArcSummary();return{seed:String(seed),days:Math.floor(days),initialLiving:initial.initialLiving,final,passed:initial.initialLiving>=100&&initial.initialLiving<=140&&final.recurringArcs.length>0&&final.marriages.length>0&&final.births.length>0&&annalsState().reign>1}}
function runNotableHazardMatrix(seed){clock={day:1,speed:8,acc:0};director={queue:[],until:0,suspend:0};world=makeWorld(String(seed));world.headless=true;firstEntries();let categories=['age','battle','plague','assassination','disaster'],candidates=lifeArcLiving().filter(c=>c.role!=='monarch'&&c.role!=='heir'&&c.id!==lifeArcState().arcs[0]?.characterId).slice(0,categories.length),results=[];categories.forEach((category,index)=>{let c=candidates[index];results.push({category,characterId:c?.id||null,applied:applyNotableHazard(c,category,{place:characterHome(c||candidates[0]).name,reason:'a deliberately exercised grudge',type:'a test disaster'},true),deathCategory:c?.deathCategory||null})});return{seed:String(seed),results,hazardDeaths:{...lifeArcState().hazardDeaths},passed:results.length===categories.length&&results.every(x=>x.applied&&x.deathCategory===x.category)}}
if(typeof window!=='undefined'){window.ANNALS_DEBUG.lifeArcs=lifeArcSummary;window.ANNALS_DEBUG.runNotableAcceptance=runNotableAcceptance;window.ANNALS_DEBUG.runNotableHazardMatrix=runNotableHazardMatrix;window.ANNALS_DEBUG.arrangeAllianceMarriage=()=>arrangeAllianceMarriage(true);window.ANNALS_DEBUG.recordAllianceBirth=()=>recordAllianceBirth(true)}