const MEMORY_LIMIT=180;
const MEMORY_MAJOR_TYPES=['fire','rebellion','drought','food-shortage','succession','character-status','scar-restoration','scar-memorial','omen-site','dragon','war'];
function memoryState(){return world.memoryState||(world.memoryState={nextId:1,registry:[]})}
function memoryName(type,location,participants=[]){let place=location&&location.name?location.name:'the realm',who=participants.map(p=>characterById&&characterById(p)).find(Boolean);if(type==='fire')return`The Burning of ${place}`;if(type==='rebellion'||type==='war')return`The Rising at ${place}`;if(type==='drought'||type==='food-shortage')return`The Lean Season of ${place}`;if(type==='succession')return`The Crowning of ${who?who.name:place}`;if(type==='character-status')return`The Passing of ${who?who.name:place}`;if(type==='scar-restoration')return`The Rebuilding of ${place}`;if(type==='scar-memorial')return`The Memorial of ${place}`;if(type==='omen-site')return`The Sign at ${place}`;return`${String(type).replace(/-/g,' ')} at ${place}`.replace(/^./,c=>c.toUpperCase())}
function memorySummary(m){return{id:m.id,eventId:m.eventId,name:m.name,type:m.type,day:m.day,location:{...m.location},scarId:m.scarId,participants:[...m.participants],houses:[...m.houses],causes:[...m.causes],consequences:[...m.consequences],relatedMemoryIds:[...m.relatedMemoryIds],strength:m.strength,state:m.state,lastRecalledDay:m.lastRecalledDay}}
function memoryHouses(parts=[]){let names=new Set(world.houses.map(h=>h.name)),out=[];for(const p of parts){let c=typeof characterById==='function'?characterById(p):null,h=c&&typeof characterHouse==='function'?characterHouse(c):null;if(h)out.push(h.name);else if(names.has(p))out.push(p)}return[...new Set(out)].slice(0,6)}
function memoryScore(m,type,details){let score=0,loc=eventTarget(details.location),parts=details.participants||[],cons=details.consequences||[],houses=memoryHouses(parts);if(m.location.entityId&&m.location.entityId===loc.entityId)score+=5;else if(m.location.name&&m.location.name===loc.name)score+=4;else if(Math.hypot(m.location.x-loc.x,m.location.z-loc.z)<180)score+=2;if(m.type===type)score+=2;score+=m.participants.some(p=>parts.includes(p))?4:0;score+=m.houses.some(h=>houses.includes(h))?4:0;score+=m.consequences.some(c=>cons.includes(c))?3:0;return score*(m.strength/100)}
function relevantMemory(type,details={}){let ranked=memoryState().registry.map(m=>({m,score:memoryScore(m,type,details)})).filter(x=>x.score>=2).sort((a,b)=>b.score-a.score||b.m.day-a.m.day);return ranked[0]?.m||null}
function recordMemory(ev){if(ev.severity<7&&!MEMORY_MAJOR_TYPES.includes(ev.type))return null;let state=memoryState(),m={id:`${world.seed}:memory${state.nextId++}`,eventId:ev.id,name:memoryName(ev.type,ev.location,ev.participants),type:ev.type,day:ev.day,location:{...ev.location},scarId:ev.metadata&&ev.metadata.scarId||null,participants:[...ev.participants],houses:memoryHouses(ev.participants),causes:[...ev.causes],consequences:[...ev.consequences],relatedMemoryIds:[],strength:100,state:'active',lastRecalledDay:null};state.registry.unshift(m);if(state.registry.length>MEMORY_LIMIT)state.registry.length=MEMORY_LIMIT;return m}
function decayMemories(){for(const m of memoryState().registry){let age=clock.day-m.day;m.strength=clamp(100-Math.floor(age/36),20,100);m.state=m.strength<40?'faded':m.strength<70?'remembered':'active'}}
const memoryBaseEmitWorldEvent=emitWorldEvent;
emitWorldEvent=function(type,details={}){let prior=relevantMemory(type,details),copy={...details,metadata:details.metadata&&typeof details.metadata==='object'?{...details.metadata}:{}};if(prior&&copy.metadata.chronicle){copy.metadata.chronicle={...copy.metadata.chronicle,text:`${copy.metadata.chronicle.text} The chroniclers compared it with ${prior.name}.`};copy.metadata.memoryRefId=prior.id;prior.lastRecalledDay=Math.floor(clock.day);prior.strength=clamp(prior.strength+8,20,100)}let ev=memoryBaseEmitWorldEvent(type,copy),current=recordMemory(ev);if(prior&&current){current.relatedMemoryIds.push(prior.id);prior.relatedMemoryIds.push(current.id);prior.relatedMemoryIds=prior.relatedMemoryIds.slice(-12)}return ev}
function memoryById(id){return memoryState().registry.find(m=>m.id===id)||null}
