const NOTABLE_LIMIT=128;
const NOTABLE_TRAITS='brave cautious ambitious pious shrewd loyal cruel generous patient proud'.split(' ');
const NOTABLE_AGENDAS=['secure the succession','increase house influence','protect local trade','strengthen the faith','command the royal host','enrich the treasury','avenge an old slight','restore a damaged settlement'];
const NOTABLE_ROLES=['noble','commander','merchant','clergy','high priest','master of coin','smith','prophet','bandit king'];
const notableBaseCreateCharacter=createCharacter,notableBaseInitCharacters=initCharacters,notableBaseSummary=characterSummary;
function enrichNotable(c){if(!c)return c;c.traits=c.traits||[pick(hisR,NOTABLE_TRAITS),pick(hisR,NOTABLE_TRAITS)].filter((v,i,a)=>a.indexOf(v)===i);c.agenda=c.agenda||pick(hisR,NOTABLE_AGENDAS);c.grudges=c.grudges||[];c.epithet=c.epithet||null;c.appearances=c.appearances||0;c.deathCause=c.deathCause||null;c.parentIds=c.parentIds||[];c.childIds=c.childIds||[];c.spouseId=c.spouseId||null;return c}
createCharacter=function(role,home,houseId=null,age=irnd(hisR,18,62),status='alive'){let state=characterState();if(state.registry.length>=NOTABLE_LIMIT)return null;let c={id:`${world.seed}:c${state.nextId++}`,name:characterName(),age:clamp(age,0,100),role,status,homeId:(home&&home.id)??0,houseId:Number.isInteger(houseId)?houseId:null,bornDay:Math.floor(clock.day-age*360),statusDay:Math.floor(clock.day)};state.registry.push(c);return enrichNotable(c)};
function seedGrudges(){let living=characterState().registry.filter(c=>c.status==='alive');for(let i=0;i<Math.min(18,living.length-1);i++){let a=living[i],b=living[(i*7+5)%living.length];if(a!==b&&!a.grudges.some(g=>g.characterId===b.id))a.grudges.push({characterId:b.id,reason:pick(hisR,['a disputed inheritance','an insult before the court','rival claims to office','a broken trade oath']),strength:irnd(hisR,25,70)})}}
initCharacters=function(){let state=characterState();if(!state.registry.length)notableBaseInitCharacters();for(const c of state.registry)enrichNotable(c);let homes=world.settlements,desired=108+irnd(hisR,0,20);while(state.registry.length<desired){let i=state.registry.length,home=homes[i%homes.length],house=world.houses.length?i%world.houses.length:null,role=NOTABLE_ROLES[i%NOTABLE_ROLES.length];createCharacter(role,home,house,irnd(hisR,16,74))}seedGrudges();return state.registry};
characterSummary=function(c){let base=notableBaseSummary(c);return{...base,traits:[...(c.traits||[])],agenda:c.agenda||null,grudges:(c.grudges||[]).map(g=>({...g})),epithet:c.epithet||null,spouseId:c.spouseId||null,parentIds:[...(c.parentIds||[])],childIds:[...(c.childIds||[])],appearances:c.appearances||0,deathCause:c.deathCause||null}}
function notableByNeed(kind,home){let alive=characterState().registry.filter(c=>c.status==='alive'),preferred=kind==='war'?['commander','noble']:kind==='trade'?['merchant','master of coin','smith']:kind==='fate'?['clergy','high priest','prophet']:[];return alive.find(c=>c.homeId===home.id&&preferred.includes(c.role))||alive.find(c=>preferred.includes(c.role))||alive[0]||null}
function addGrudge(a,b,reason,strength=40){if(!a||!b||a.id===b.id)return;let existing=(a.grudges||[]).find(g=>g.characterId===b.id);if(existing)existing.strength=clamp(existing.strength+10,0,100);else{a.grudges=a.grudges||[];a.grudges.push({characterId:b.id,reason,strength});if(a.grudges.length>6)a.grudges.shift()}}
