const SCAR_LIMIT=80;
const SCAR_TYPES=['battlefield','fire-scar','ruined-structure','abandoned-settlement','plague-marker','omen-site'];
function scarState(){return world.scarState||(world.scarState={nextId:1,registry:[]})}
function scarTarget(target){if(target&&Number.isFinite(target.x)&&Number.isFinite(target.z))return{x:target.x,y:Number.isFinite(target.y)?target.y:hWorld(target.x,target.z),z:target.z,entityId:target.id??target.lotId??null,settlementId:Number.isInteger(target.settlementId)?target.settlementId:Number.isInteger(target.id)&&world.settlements[target.id]===target?target.id:null};return{x:0,y:hWorld(0,0),z:0,entityId:null,settlementId:null}}
function scarLabel(type,target){let placeName=target&&target.name?target.name:'the recorded place',labels={'battlefield':'Battlefield','fire-scar':'Burned Quarter','ruined-structure':'Ruined Structure','abandoned-settlement':'Abandoned Settlement','plague-marker':'Plague Stone','omen-site':'Omen Site'};return`${labels[type]||'Historical Scar'} of ${placeName}`}
function createHistoricalScar(type,target,cause,options={}){let state=scarState(),kind=SCAR_TYPES.includes(type)?type:'omen-site';if(state.registry.length>=SCAR_LIMIT)return null;let pos=scarTarget(target),scar={id:`${world.seed}:scar${state.nextId++}`,name:options.name||scarLabel(kind,target),type:kind,x:pos.x,y:pos.y,z:pos.z,entityId:pos.entityId,settlementId:pos.settlementId,createdDay:Math.floor(clock.day),cause:String(cause||'an event entered the record'),state:options.state||'marked',stateDay:Math.floor(clock.day),relatedEventIds:[],history:[{day:Math.floor(clock.day),state:options.state||'marked',note:String(cause||'created')}],erased:false};state.registry.unshift(scar);if(typeof refreshScarMarkers==='function')refreshScarMarkers();return scar}
function scarById(id){return scarState().registry.find(s=>s.id===id)||null}
function scarsNear(target,radius=220){return scarState().registry.filter(s=>!s.erased&&Math.hypot(s.x-target.x,s.z-target.z)<=radius)}
function scarSummary(s){return{id:s.id,name:s.name,type:s.type,state:s.state,createdDay:s.createdDay,stateDay:s.stateDay,cause:s.cause,x:Math.round(s.x),y:Math.round(s.y),z:Math.round(s.z),settlementId:s.settlementId,relatedEventIds:[...s.relatedEventIds],history:s.history.map(h=>({...h}))}}
function setScarState(scar,state,note){if(!scar||scar.erased||scar.state===state)return scar;scar.state=state;scar.stateDay=Math.floor(clock.day);scar.history.push({day:Math.floor(clock.day),state,note:String(note||state)});if(scar.history.length>12)scar.history.shift();if(typeof refreshScarMarkers==='function')refreshScarMarkers();return scar}
function linkScarEvent(scar,eventId){if(!scar||!eventId)return;if(!scar.relatedEventIds.includes(eventId))scar.relatedEventIds.push(eventId);if(scar.relatedEventIds.length>16)scar.relatedEventIds.shift()}
