;const STABILITY_ARCHIVE_LIMIT=256,STABILITY_RECENT_DEAD=24,STABILITY_CHECKPOINT_LIMIT=32;
function stabilityState(){return world.stabilityState||(world.stabilityState={notableArchive:[],eventTotals:{},chronicleByYear:{},chronicleKinds:{},chronicleTotal:0,lastChronicleDay:0,narrativeLast:{},suppressedNarrative:{},interventions:{population:0,treasury:0,relief:0,unrest:0,drought:0,plague:0,warCompaction:0,notableCompaction:0,notableRecovery:0,territoryRecovery:0,banditPatrols:0},droughtStart:null,checkpoints:[]})}
const stabilityBaseChron=chron;
chron=function(cls,priority,target,text,meta={}){let ev=stabilityBaseChron(cls,priority,target,text,meta),state=stabilityState(),year=Math.floor((clock.day-1)/360)+1,kind=meta.kind||cls;state.chronicleTotal++;state.lastChronicleDay=Math.floor(clock.day);state.chronicleByYear[year]=(state.chronicleByYear[year]||0)+1;state.chronicleKinds[kind]=(state.chronicleKinds[kind]||0)+1;let years=Object.keys(state.chronicleByYear).map(Number).sort((a,b)=>a-b);while(years.length>220){delete state.chronicleByYear[years.shift()]}return ev};
const stabilityBaseEmitWorldEvent=emitWorldEvent;
emitWorldEvent=function(type,details={}){let ev=stabilityBaseEmitWorldEvent(type,details),state=stabilityState();state.eventTotals[type]=(state.eventTotals[type]||0)+1;return ev};
const stabilityBaseEventChronicle=eventChronicle;
function allowStabilityNarrative(type){let cooldown={"food-shortage":120,"market-shortage":180}[type];if(!cooldown||clock.day<1800)return true;let state=stabilityState(),last=state.narrativeLast[type]??-Infinity;if(clock.day-last<cooldown){state.suppressedNarrative[type]=(state.suppressedNarrative[type]||0)+1;return false}state.narrativeLast[type]=Math.floor(clock.day);return true}
eventChronicle=function(type,severity,location,text,details={}){if(allowStabilityNarrative(type))return stabilityBaseEventChronicle(type,severity,location,text,details);return emitWorldEvent(type,{severity,location,causes:details.causes||[],consequences:details.consequences||[],participants:details.participants||[],metadata:{source:details.source||'simulation',director:false,suppressedChronicle:true,suppressedKind:details.kind||type}})};
const stabilityBaseCharacterById=characterById;
characterById=function(id){return stabilityBaseCharacterById(id)||stabilityState().notableArchive.find(c=>c.id===id)||null};
function compactNotableHistory(){let state=characterState(),stable=stabilityState(),living=state.registry.filter(c=>c.status==='alive'),dead=state.registry.filter(c=>c.status!=='alive').sort((a,b)=>(b.statusDay||0)-(a.statusDay||0));if(state.registry.length<NOTABLE_LIMIT-4&&living.length>=92)return;let retained=dead.slice(0,STABILITY_RECENT_DEAD),archived=dead.slice(STABILITY_RECENT_DEAD);if(!archived.length)return;for(const c of archived)stable.notableArchive.push({...c,traits:[...(c.traits||[])],grudges:(c.grudges||[]).map(g=>({...g})),parentIds:[...(c.parentIds||[])],childIds:[...(c.childIds||[])]});if(stable.notableArchive.length>STABILITY_ARCHIVE_LIMIT)stable.notableArchive.splice(0,stable.notableArchive.length-STABILITY_ARCHIVE_LIMIT);state.registry=[...living,...retained].slice(0,NOTABLE_LIMIT);stable.interventions.notableCompaction+=archived.length}
function recoverNotables(){compactNotableHistory();let state=characterState(),living=state.registry.filter(c=>c.status==='alive').length,born=0;while(living<96&&state.registry.length<NOTABLE_LIMIT&&born<2){let home=pick(hisR,world.settlements),house=world.houses.length?irnd(hisR,0,world.houses.length-1):null,c=birthCharacter(home,house);if(!c)break;living++;born++}if(born)stabilityState().interventions.notableRecovery+=born}
function compactWarHistory(){let state=warState(),active=state.campaigns.filter(c=>c.status!=='ended'),ended=state.campaigns.filter(c=>c.status==='ended').sort((a,b)=>(b.endDay||0)-(a.endDay||0)).slice(0,6),keep=[...active,...ended],ids=new Set(keep.map(c=>c.id)),before=state.armies.length;state.campaigns=keep.sort((a,b)=>a.startDay-b.startDay);state.armies=state.armies.filter(a=>ids.has(a.campaignId));for(const c of active){let armies=state.armies.filter(a=>a.campaignId===c.id);if(c.status==='marching'&&clock.day-c.startDay>240&&armies.length<2)endWar(c,'status-quo',armies[0]||null);if(c.status==='siege'&&clock.day-(c.siege?.startDay||c.startDay)>180)endWar(c,'status-quo',armies[0]||null)}if(before!==state.armies.length)stabilityState().interventions.warCompaction+=before-state.armies.length}
function settlementCarryingCapacity(s){let base=s.type==='capital'?6800:s.type==='town'?4200:2200;return base*(.72+.45*clamp(s.fert,0,1.5))}
function settlementPopulationFloor(s){return s.type==='capital'?500:s.type==='town'?240:90}
function rebalancePopulation(){let state=stabilityState();for(const s of world.settlements){let cap=settlementCarryingCapacity(s),floor=settlementPopulationFloor(s),rate=s.disease?s.disease.infected/Math.max(1,s.pop):0;if(s.pop>cap){s.pop=Math.max(cap,s.pop-(s.pop-cap)*.08);state.interventions.population++}else if(s.pop<floor&&s.hunger<68&&rate<.04){s.pop=Math.min(floor,s.pop+Math.max(2,(floor-s.pop)*.04));state.interventions.population++}if(s.hunger>72&&economyState().treasury>120){let cost=Math.min(220,Math.max(20,s.pop*.018));economyState().treasury=clamp(economyState().treasury-cost,0,100000);s.stores.grain=clamp(s.stores.grain+cost*2.4,0,Math.max(300,s.pop*1.8));s.hunger=clamp(s.hunger-7,0,100);s.unrest=clamp(s.unrest-3,0,100);state.interventions.relief++}if(s.unrest>88&&!warState().campaigns.some(c=>c.status!=='ended')){s.unrest=clamp(s.unrest-5,0,100);state.interventions.unrest++}if(s.disease&&s.disease.infected>0&&s.disease.infected<Math.max(1,s.pop*.001)){s.disease.recovered+=s.disease.infected;s.disease.infected=0;s.disease.quarantined=false;state.interventions.plague++}}}
function rebalanceTreasury(){let econ=economyState(),state=stabilityState();if(econ.treasury>40000){let spend=Math.max(100,(econ.treasury-40000)*.08);econ.treasury=clamp(econ.treasury-spend,0,100000);let boost=spend/Math.max(1,world.settlements.length)/900;for(const s of world.settlements){s.prosperity=clamp(s.prosperity+boost,0,100);s.unrest=clamp(s.unrest-boost*.45,0,100)}state.interventions.treasury++}else if(econ.treasury<60){econ.treasury=clamp(econ.treasury+20+world.settlements.reduce((n,s)=>n+s.prosperity,0)*.03,0,100000);state.interventions.treasury++}}
function resolveLongDrought(){let state=stabilityState();if(world.drought&&!state.droughtStart)state.droughtStart=Math.floor(clock.day);if(world.drought&&clock.day-state.droughtStart>720){world.drought=false;state.droughtStart=null;state.interventions.drought++;let s=pressure();eventChronicle('drought-ended',7,s,`Rain returned after the long drought; wells rose, fields reopened and the realm began a slower recovery.`,{class:'trade',kind:'harvest',participants:[s.name],causes:['the drought cycle ended'],consequences:['grain production recovered'],source:'stability-system'})}if(!world.drought)state.droughtStart=null}
function patrolBandits(){let threats=threatState(),active=threats.banditCamps.filter(c=>c.status==='active');threats.banditCamps=threats.banditCamps.filter(c=>c.status==='active'||clock.day-(c.clearedDay||clock.day)<360);if(active.length<3||economyState().treasury<500)return;let camp=active.sort((a,b)=>a.createdDay-b.createdDay)[0];camp.status='cleared';camp.clearedDay=Math.floor(clock.day);economyState().treasury=clamp(economyState().treasury-180,0,100000);stabilityState().interventions.banditPatrols++;eventChronicle('bandit-patrol',7,camp,`A royal patrol broke the oldest road camp; trade resumed where the thieves had once collected their own toll.`,{class:'war',kind:'bandits',participants:[camp.kingId,camp.id].filter(Boolean),causes:['bandit pressure remained high'],consequences:['one road camp was cleared'],source:'stability-system'})}
function recoverTerritories(){let owners=new Set(world.settlements.map(s=>s.owner));if(owners.size>=2||world.houses.length<2)return;let house=world.houses.slice(1).sort((a,b)=>b.loyalty-a.loyalty)[0],seat=world.settlements[house.seatSettlement];if(!seat)return;seat.owner=house.id;house.loyalty=clamp(house.loyalty+18,0,100);house.rebellious=false;stabilityState().interventions.territoryRecovery++;eventChronicle('territory-restored',8,seat,`${house.name} recovered its ancestral seat at ${seat.name}; the map again held more than one living centre of power.`,{class:'crown',kind:'peace',participants:[house.name,seat.name],causes:['one house had absorbed every settlement'],consequences:['a second territorial power returned'],source:'stability-system'})}
function stabilityQuarter(){if(clock.day<1800)return;resolveLongDrought();rebalancePopulation();rebalanceTreasury();if(Math.floor(clock.day)%180===0)recoverNotables();if(Math.floor(clock.day)%360===0){compactWarHistory();patrolBandits()}if(Math.floor(clock.day)%3600===0)recoverTerritories()}
const stabilityBaseTick=tick;
tick=function(){stabilityBaseTick();if(Math.floor(clock.day)%90===0)stabilityQuarter()};
function stabilityFiniteValues(){let values=[clock.day,economyState().treasury,economyState().taxCollected,...world.settlements.flatMap(s=>[s.pop,s.prosperity,s.hunger,s.unrest,...ECONOMY_GOODS.flatMap(g=>[s.stores[g],s.prices[g]])]),...world.houses.flatMap(h=>[h.loyalty,h.might||0]),...warState().armies.flatMap(a=>[a.strength,a.morale,a.supply,a.progress]),...characterState().registry.flatMap(c=>[c.age,c.bornDay,c.statusDay])];return values.every(Number.isFinite)}
function recentChronicleRate(years=20){let state=stabilityState(),year=Math.floor((clock.day-1)/360)+1,total=0;for(let y=Math.max(1,year-years+1);y<=year;y++)total+=state.chronicleByYear[y]||0;return Math.round(total/Math.max(1,Math.min(year,years))*100)/100}
function stabilitySnapshot(){initEconomy();initCharacters();initThreats();let state=stabilityState(),chars=characterState(),all=[...chars.registry,...state.notableArchive],population=world.settlements.reduce((n,s)=>n+s.pop,0),activeWars=warState().campaigns.filter(c=>c.status!=='ended').length,disasters=Object.entries(state.eventTotals).filter(([k])=>['drought','fire','plague-outbreak','plague-spread','plague-toll','dragon-raid'].includes(k)).reduce((n,[,v])=>n+v,0);return{day:Math.floor(clock.day),year:Math.floor((clock.day-1)/360)+1,finite:stabilityFiniteValues(),population:Math.round(population),populationMin:Math.round(Math.min(...world.settlements.map(s=>s.pop))),populationMax:Math.round(Math.max(...world.settlements.map(s=>s.pop))),treasury:Math.round(economyState().treasury*100)/100,settlements:world.settlements.length,houses:world.houses.length,distinctOwners:new Set(world.settlements.map(s=>s.owner)).size,rebelliousHouses:world.houses.filter(h=>h.rebellious).length,livingNotables:chars.registry.filter(c=>c.status==='alive').length,notableRegistry:chars.registry.length,notableArchive:state.notableArchive.length,deaths:all.filter(c=>c.status==='dead').length,reigns:annalsState().reign,warsCompleted:warState().completed,activeWars,campaigns:warState().campaigns.length,armies:warState().armies.length,disasters,chronicleTotal:state.chronicleTotal,chronicleRate:recentChronicleRate(),lastChronicleDay:state.lastChronicleDay,chronicleKinds:{...state.chronicleKinds},eventTotals:{...state.eventTotals},suppressedNarrative:{...state.suppressedNarrative},trades:economyState().trades.length,banditCamps:threatState().banditCamps.length,dragonRaids:threatState().dragon.raids.length,worldEvents:worldEventState().registry.length,scars:world.scarState?.registry?.length||0,memories:world.memoryState?.registry?.length||0,interventions:{...state.interventions}}}
function stabilitySummary(){return stabilitySnapshot()}
