;const PRODUCT_TABS=['time','rates','acts','world','houses'];
const PRODUCT_ACT_LABELS={grain:'Release grain',festival:'Proclaim festival',drought:'Declare drought',fire:'Start great fire'};
const PRODUCT_RATE_LIMITS={productionRate:[.5,1.5],tradeLoadRate:[.5,2],chronicleRate:[.5,2]};
function productUiState(){
  let state=world.productUiState||(world.productUiState={});
  if(!PRODUCT_TABS.includes(state.tab))state.tab='time';
  if(!Number.isFinite(state.productionRate))state.productionRate=1;
  if(!Number.isFinite(state.tradeLoadRate))state.tradeLoadRate=1;
  if(!Number.isFinite(state.chronicleRate))state.chronicleRate=1;
  if(!Object.prototype.hasOwnProperty.call(state,'pendingAct'))state.pendingAct=null;
  return state;
}
function setDrawerTab(tab){productUiState().tab=PRODUCT_TABS.includes(tab)?tab:'time';drawer()}
function setTaxRate(value){let rate=clamp(Number(value)/100,0,.3),state=economyState();state.taxRate=rate;for(const h of world.houses.slice(1))h.loyalty=clamp(h.loyalty-(rate-.08)*1.5,0,100);hud();drawer()}
function setProductRate(name,value){let bounds=PRODUCT_RATE_LIMITS[name];if(!bounds)return false;productUiState()[name]=clamp(Number(value)/100,bounds[0],bounds[1]);if(typeof document!=='undefined'&&!world.headless){hud();drawer()}return true}
function uiPopulation(){return Math.round(world.settlements.reduce((n,s)=>n+s.pop,0))}
function uiMonarch(){return characterById(world.story.monarchId)||characterState().registry.find(c=>c.role==='monarch'&&c.status==='alive')||null}
function sigilBadge(house,className='house-sigil'){return house?`<img class="${className}" data-sigil="${safeName(house.sigil?.signature||'')}" src="${houseSigilDataUrl(house)}" alt="Sigil of ${safeName(house.name)}" title="${safeName(house.sigil?.charge||'house')} · ${safeName(house.motto||'')}">`:''}
function settlementById(id){return world.settlements.find(s=>String(s.id)===String(id))||null}
function nearestSettlement(target){if(!target||!world.settlements.length)return null;if(Number.isInteger(target))return settlementById(target);if(target.kind==='settlement'&&target.settlement)return target.settlement;if(target.building)return settlementById(target.building.settlementId);if(target.settlementId!==undefined)return settlementById(target.settlementId);if(target.homeSettlementId!==undefined)return settlementById(target.homeSettlementId);if(Number.isFinite(target.x)&&Number.isFinite(target.z))return world.settlements.slice().sort((a,b)=>Math.hypot(a.x-target.x,a.z-target.z)-Math.hypot(b.x-target.x,b.z-target.z))[0]||null;return null}
function refreshProductUi(){if(typeof document==='undefined'||world.headless)return;renderChronicle();hud();drawer()}
const productBaseProductionFor=productionFor;
productionFor=function(s){let p=productBaseProductionFor(s),rate=productUiState().productionRate;for(const good of ['grain','fish','timber','ore','cloth','wine'])if(Number.isFinite(p[good]))p[good]=Math.max(0,p[good]*rate);return p};
const productBaseLaunchTrade=launchTrade;
launchTrade=function(candidate){if(!candidate)return productBaseLaunchTrade(candidate);let amount=clamp(Math.round((candidate.amount||0)*productUiState().tradeLoadRate),1,240);return productBaseLaunchTrade({...candidate,amount})};
const productBaseTick=tick;
tick=function(){let state=annalsState(),scheduled=state.nextEntry;productBaseTick();if(scheduled<=clock.day&&state.nextEntry>clock.day){let interval=Math.max(18,state.nextEntry-clock.day);state.nextEntry=clock.day+Math.max(18,Math.round(interval/productUiState().chronicleRate))}};
const productBaseAct=act;
function performTargetedAct(action,target){let s=nearestSettlement(target)||pressure();if(!s)return false;if(action==='fire'&&typeof startUrbanFire==='function'){let fire=startUrbanFire(s);refreshProductUi();return !!fire}if(action==='grain'){let state=typeof economyCompletionState==='function'?economyCompletionState():economyState(),cost=Math.min(state.treasury,s.pop*.025),beforeHunger=s.hunger;state.treasury=clamp(state.treasury-cost,0,100000);if(state.spending)state.spending.relief+=cost;s.stores.grain=clamp(s.stores.grain+.18*s.pop+cost*3,0,Math.max(300,s.pop*1.8));s.hunger=clamp(s.hunger-14,0,100);s.unrest=clamp(s.unrest-3,0,100);eventChronicle('grain-relief',7,s,`The crown released grain directly to ${s.name}; hunger fell from ${Math.round(beforeHunger)} to ${Math.round(s.hunger)}, and ${Math.round(cost)} crowns left the treasury to steady the town.`,{class:'trade',kind:'trade',source:'manual-act',causes:['the player targeted a royal grain release'],consequences:['grain stores increased','hunger and unrest fell','treasury spending increased'],participants:[s.name]});refreshProductUi();return true}if(action==='festival'){let before=s.unrest;s.unrest=clamp(s.unrest-15,0,100);s.prosperity=clamp(s.prosperity+2,0,100);eventChronicle('festival',6,s,`A royal festival was proclaimed in ${s.name}; unrest fell from ${Math.round(before)} to ${Math.round(s.unrest)}, and market trade briefly prospered beneath the lanterns.`,{class:'crown',kind:'festival',source:'manual-act',causes:['the player targeted a public festival'],consequences:['unrest fell','prosperity increased'],participants:[s.name]});refreshProductUi();return true}if(action==='drought'){world.drought=true;s.hunger=clamp(s.hunger+2,0,100);eventChronicle('drought',9,s,`Drought measures were declared first at ${s.name}; the decree recognised failing wells there, while reduced grain growth spread the consequence across the realm.`,{class:'fate',kind:'disaster',source:'manual-act',causes:['the player targeted a drought declaration'],consequences:['realm-wide grain growth reduced',`${s.name} received immediate hunger pressure`],participants:[s.name]});refreshProductUi();return true}return productBaseAct(action)}
act=function(action,target){return target?performTargetedAct(action,target):productBaseAct(action)};
function ensureActTargetingBanner(){if(typeof document==='undefined')return null;let el=document.getElementById('act-targeting');if(!el){el=document.createElement('div');el.id='act-targeting';el.className='panel';document.body.appendChild(el)}return el}
function renderActTargeting(){if(typeof document==='undefined')return;let state=productUiState(),el=ensureActTargetingBanner();if(!state.pendingAct){document.body.classList.remove('targeting-act');el.style.display='none';return}document.body.classList.add('targeting-act');el.style.display='flex';el.innerHTML=`<b>${safeName(PRODUCT_ACT_LABELS[state.pendingAct])}</b><span>Click a settlement, building, road subject or place in the realm. Esc cancels.</span><button onclick="cancelTargetedAct()">Cancel</button>`}
function beginTargetedAct(action){if(!PRODUCT_ACT_LABELS[action])return false;productUiState().pendingAct=action;director.suspend=clock.day+30;renderActTargeting();drawer();return true}
function cancelTargetedAct(redraw=true){let state=productUiState(),had=!!state.pendingAct;state.pendingAct=null;renderActTargeting();if(redraw&&typeof document!=='undefined'&&!world.headless)drawer();return had}
function pointerSettlement(event){if(!renderer?.domElement||!camera)return null;let rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height*2-1)),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);let hit=ray.intersectObjects(pickables,true)[0];if(hit){let node=hit.object;while(node&&!node.userData.pick)node=node.parent;let chosen=nearestSettlement(node?.userData?.pick);if(chosen)return chosen}let point=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);if(ray.ray.intersectPlane(plane,point))return nearestSettlement(point);return null}
const productBaseHandlePick=handlePick;
handlePick=function(event){let action=productUiState().pendingAct;if(!action)return productBaseHandlePick(event);let settlement=pointerSettlement(event);if(!settlement)return;cancelTargetedAct(false);performTargetedAct(action,settlement);fly(settlement,460,1400);showInspector({kind:'settlement',settlement});renderActTargeting()};
function closeInspector(){let el=document.getElementById('inspect');if(el)el.style.display='none'}
function showProductInspector(html){let el=document.getElementById('inspect');if(!el)return;el.style.display='block';el.innerHTML=`<button class="inspector-close" onclick="closeInspector()">×</button>${html}`;director.suspend=clock.day+20}
function inspectTrade(id){let t=economyState().trades.find(x=>x.id===id);if(!t)return;let from=settlementById(t.fromId),to=settlementById(t.toId),mode=t.mode==='cog'?'Coastal cog':'Road caravan';showProductInspector(`<h3 class="inspector-title">${safeName(t.good)} ${t.mode==='cog'?'cog':'caravan'}</h3><div class="kv"><b>Mode</b><span>${mode}</span><b>Route</b><span>${safeName(from?.name)} → ${safeName(to?.name)}</span><b>Cargo</b><span>${Math.round(t.amount)} ${safeName(t.good)}</span><b>Status</b><span>${safeName(t.status)}</span><b>Progress</b><span>${Math.round((t.progress||0)*100)}%</span><b>Arrival</b><span>${dt(t.arrivalDay)}</span><b>Stable ID</b><span>${safeName(t.id)}</span></div>`)}
function inspectArmy(id){let a=warState().armies.find(x=>x.id===id);if(!a)return;let commander=characterById(a.commanderId),house=world.houses[a.houseId];showProductInspector(`<div class="inspector-heraldry">${sigilBadge(house)}<h3 class="inspector-title">${safeName(a.side)} army</h3></div><div class="kv"><b>House</b><span>${safeName(house?.name)}</span><b>Commander</b><span>${safeName(commander?.name)}</span><b>Strength</b><span>${Math.round(a.strength)}</span><b>Supply</b><span>${Math.round(a.supply)}</span><b>Morale</b><span>${Math.round(a.morale)}</span><b>Status</b><span>${safeName(a.status)}</span><b>Stable ID</b><span>${safeName(a.id)}</span></div>`)}
function inspectBandit(id){let c=threatState().banditCamps.find(x=>x.id===id);if(!c)return;let king=characterById(c.kingId);showProductInspector(`<h3 class="inspector-title">Road camp</h3><div class="kv"><b>Strength</b><span>${Math.round(c.strength)}</span><b>Ambushes</b><span>${c.ambushes}</span><b>Status</b><span>${safeName(c.status)}</span><b>Leader</b><span>${safeName(king?`${king.name} ${king.epithet||''}`:'No crowned leader')}</span><b>Stable ID</b><span>${safeName(c.id)}</span></div>`)}
function inspectDragon(){let d=threatState().dragon,r=d.raids.at(-1),s=r&&settlementById(r.settlementId);showProductInspector(`<h3 class="inspector-title">The dragon</h3><div class="kv"><b>State</b><span>${d.awake?'Awake':'Absent'}</span><b>Last raid</b><span>${r?dt(r.day):'None recorded'}</span><b>Target</b><span>${safeName(s?.name||'—')}</span><b>Tribute</b><span>${r?Math.round(r.tribute)+' crowns':'—'}</span><b>Myth</b><span>${safeName(threatState().myth)}</span></div>`)}
function inspectSettlementById(id){let s=settlementById(id);if(s)showInspector({kind:'settlement',settlement:s})}
function inspectBuildingById(id){let b=world.buildings.find(x=>x.id===id);if(!b)return;let s=settlementById(b.settlementId),lot=s?.layout?.lots?.find(x=>x.id===b.lotId);if(lot)showInspector({kind:'building',building:b,lot})}
function houseSuccession(house,limit=4){if(typeof characterState!=='function')return[];return characterState().registry.filter(c=>c.status==='alive'&&c.houseId===house.id).map(c=>({character:c,score:typeof claimScore==='function'?claimScore(c):(c.claimStrength||0)+(c.legitimacy||0)})).sort((a,b)=>b.score-a.score||a.character.id.localeCompare(b.character.id)).slice(0,limit)}
function houseGrudges(house){let grudges=[];if(house.rebellious)grudges.push('The Crown — open rebellion');if(typeof warState==='function')for(const campaign of warState().campaigns||[]){if(![campaign.attackerHouseId,campaign.defenderHouseId].includes(house.id))continue;let other=campaign.attackerHouseId===house.id?campaign.defenderHouseId:campaign.attackerHouseId,name=world.houses[other]?.name;if(name&&!grudges.some(g=>g.startsWith(name)))grudges.push(`${name} — ${campaign.status==='ended'?'unsettled war memory':'active campaign'}`)}if(house.id!==0&&house.loyalty<45&&!grudges.some(g=>g.startsWith('The Crown')))grudges.push('The Crown — levies and neglected petitions');return grudges.slice(0,3)}
function inspectHouse(id){let house=world.houses.find(h=>String(h.id)===String(id));if(!house)return;let seat=settlementById(house.seatSettlement),succession=houseSuccession(house),grudges=houseGrudges(house);showProductInspector(`<div class="inspector-heraldry">${sigilBadge(house)}<h3 class="inspector-title">${safeName(house.name)}</h3></div><div class="kv"><b>Seat</b><span>${safeName(seat?.name||'—')}</span><b>Loyalty</b><span>${Math.round(house.loyalty)}</span><b>Might</b><span>${Math.round(house.might||0)}</span><b>Status</b><span>${house.rebellious?'Rebellious':'Sworn'}</span><b>Grudges</b><span>${grudges.map(safeName).join('<br>')||'No active grudge recorded'}</span><b>Succession</b><span>${succession.map((x,i)=>`${i+1}. ${safeName(x.character.name)} · ${Math.round(x.score)}`).join('<br>')||'No living claimant recorded'}</span></div>`)}
function productTabButton(id,label){return`<button class="${productUiState().tab===id?'active':''}" onclick="setDrawerTab('${id}')">${label}</button>`}
function timePanel(){return`<div class="section"><b>Time</b><p class="small">Simulation speed changes how quickly days pass; camera and rendering continue smoothly.</p><div class="grid"><button onclick="clock.speed=0">Pause</button><button onclick="clock.speed=.5">1×</button><button onclick="clock.speed=2">4×</button><button onclick="clock.speed=8">16×</button><button onclick="clock.speed=30">60×</button><button onclick="toggleWatchMode()">Watch mode</button></div></div>`}
function rateSlider(id,label,value,min,max,description,oninput){return`<label class="rate-control" for="${id}"><span>${label}<b>${Math.round(value)}%</b></span><input id="${id}" type="range" min="${min}" max="${max}" step="5" value="${Math.round(value)}" oninput="${oninput}"><small>${description}</small></label>`}
function ratesPanel(){let e=economyState(),state=productUiState();return`<div class="section"><b>Rates</b><p class="small">Every control below changes a live, inspectable simulation value. Values reset when the realm is reloaded.</p>${rateSlider('tax-rate','Trade and harvest tax',e.taxRate*100,0,30,'Raises treasury receipts while increasing unrest and loyalty pressure.','setTaxRate(this.value)')}${rateSlider('production-rate','Harvest and extraction',state.productionRate*100,50,150,'Scales daily grain, fish, timber, ore, cloth and wine production.',"setProductRate('productionRate',this.value)")}${rateSlider('trade-load-rate','Caravan and cog loads',state.tradeLoadRate*100,50,200,'Scales the cargo committed to every newly launched trade journey.',"setProductRate('tradeLoadRate',this.value)")}${rateSlider('chronicle-rate','Chronicle pace',state.chronicleRate*100,50,200,'Changes the interval between background annalist entries without consuming the generation RNG.',"setProductRate('chronicleRate',this.value)")}<div class="kv"><b>Treasury</b><span>${Math.round(e.treasury)} crowns</span><b>Tax collected</b><span>${Math.round(e.taxCollected)} crowns</span><b>New trade load</b><span>${Math.round(state.tradeLoadRate*100)}%</span><b>Production</b><span>${Math.round(state.productionRate*100)}%</span></div></div>`}
function actsPanel(){let state=productUiState(),s=pressure(),pending=state.pendingAct;return`<div class="section"><b>Acts</b><p class="small">Choose an Act, then click its settlement or location in the realm. The current pressure point is <b>${safeName(s.name)}</b>, but placement is no longer forced there.</p><div class="grid"><button class="${pending==='grain'?'active':''}" onclick="beginTargetedAct('grain')">Release grain</button><button class="${pending==='festival'?'active':''}" onclick="beginTargetedAct('festival')">Proclaim festival</button><button class="${pending==='drought'?'active':''}" onclick="beginTargetedAct('drought')">Declare drought</button><button class="${pending==='fire'?'active':''}" onclick="beginTargetedAct('fire')">Start great fire</button></div>${pending?`<p class="targeting-copy"><b>Placement active:</b> ${safeName(PRODUCT_ACT_LABELS[pending])}. Click the world or <button onclick="cancelTargetedAct()">cancel</button>.</p>`:''}<p class="small">Every act records its cause and consequences in the Chronicle.</p></div>`}
function worldPanel(){let trades=economyState().trades.filter(t=>t.status==='travelling').slice(0,6),armies=warState().armies.filter(a=>a.status!=='destroyed').slice(0,5),camps=threatState().banditCamps.filter(c=>c.status==='active').slice(0,4),people=characterState().registry.filter(c=>c.status==='alive').slice(0,6),scars=typeof scarState==='function'?scarState().registry.filter(s=>!s.erased).slice(0,5):[],ruins=world.buildings.filter(b=>b.state==='ruin'||b.state==='rebuilding').slice(0,5);return`<div class="section"><b>World</b><div class="kv"><b>Seed</b><span>${safeName(world.seed)}</span><b>Culture</b><span>${safeName(world.culture?.label||'—')}</span><b>Realm</b><span>${safeName(world.title)}</span><b>Population</b><span>${uiPopulation().toLocaleString()}</span><b>Settlements</b><span>${world.settlements.length}</span><b>Buildings</b><span>${world.buildings.length}</span><b>LOD</b><span>${typeof atmosphereState==='function'?safeName(atmosphereState().band):'—'}</span></div></div><div class="section"><b>Inspect settlements</b><div class="button-flow">${world.settlements.map(s=>`<button onclick="inspectSettlementById('${s.id}')">${safeName(s.name)}</button>`).join('')}</div></div><div class="section"><b>Moving subjects</b><div class="button-flow">${trades.map(t=>`<button onclick="inspectTrade('${t.id}')">${safeName(t.good)} ${t.mode==='cog'?'cog':'caravan'}</button>`).join('')||'<span class="small">No trade journey is currently travelling.</span>'}${armies.map(a=>`<button onclick="inspectArmy('${a.id}')">${safeName(a.side)} army</button>`).join('')}${camps.map(c=>`<button onclick="inspectBandit('${c.id}')">Bandit camp</button>`).join('')}<button onclick="inspectDragon()">Dragon</button></div></div><div class="section"><b>People, ruins and scars</b><div class="button-flow">${people.map(c=>`<button onclick="showCharacter('${c.id}')">${safeName(c.name)}</button>`).join('')}${ruins.map(b=>`<button onclick="inspectBuildingById('${b.id}')">${safeName(b.type)} · ${safeName(b.state)}</button>`).join('')}${scars.map(s=>`<button onclick="showScar('${s.id}')">${safeName(s.name)}</button>`).join('')}</div></div><div class="section"><button onclick="location.hash='s='+Date.now();location.reload()">Reforge</button> <button onclick="copySeedLink()">Copy link</button> <button onclick="exportChronicle()">Export Chronicle</button></div>`}
function housesPanel(){return`<div class="section"><b>Great Houses</b><p class="small">Sigils, loyalties, grudges and succession are read from the live realm rather than decorative placeholders.</p>${world.houses.map(h=>{let seat=settlementById(h.seatSettlement),dyn=typeof dynastyForHouse==='function'?dynastyForHouse(h.id):null,grudges=houseGrudges(h),succession=houseSuccession(h,3);return`<button class="house-card" onclick="inspectHouse('${h.id}')">${sigilBadge(h)}<span class="house-copy"><b>${safeName(h.name)}</b><small>${safeName(h.sigil?.charge||'device')} on ${safeName(h.sigil?.division||'field')} · “${safeName(h.motto||'')}”</small><small>Seat ${safeName(seat?.name||'—')} · loyalty ${Math.round(h.loyalty)} · might ${Math.round(h.might||0)}${h.rebellious?' · REBELLIOUS':''}</small><span class="bar"><span style="width:${clamp(h.loyalty,0,100)}%"></span></span><small>Grudge: ${safeName(grudges[0]||'none recorded')}</small><small>Succession: ${succession.map(x=>safeName(x.character.name)).join(' → ')||'no living claimant'}</small><small>${dyn?`${safeName(dyn.name)} · ${safeName(dyn.status)}`:'Dynasty not recorded'}</small></span></button>`}).join('')}</div>`}
function toggleWatchMode(){cancelTargetedAct(false);document.body.classList.toggle('watch');return document.body.classList.contains('watch')}
async function copySeedLink(){let url=location.href;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url);return true}let input=document.createElement('textarea');input.value=url;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();let copied=document.execCommand('copy');input.remove();return copied}catch(error){console.warn('Copy link failed',error);return false}}
const productBaseDrawer=drawer;
drawer=function(){let tabs=`<div class="ui-tabs">${productTabButton('time','Time')}${productTabButton('rates','Rates')}${productTabButton('acts','Acts')}${productTabButton('world','World')}${productTabButton('houses','Houses')}</div>`,content={time:timePanel,rates:ratesPanel,acts:actsPanel,world:worldPanel,houses:housesPanel}[productUiState().tab]();document.getElementById('drawer').innerHTML=`<b>ANNALS ${safeName(world.version)}</b>${tabs}${content}<p class="small hotkey-help">Hotkeys: Space pause · 1–4 speed · H hide UI · C Watch · Esc deselect or cancel placement.</p>`;renderActTargeting()};
const productBaseHud=hud;
hud=function(){let monarch=uiMonarch(),ruling=world.houses[monarch?.houseId??0]||world.houses[0],e=economyState(),cam=typeof cinematicState==='function'?cinematicState():{mode:'director'},pop=uiPopulation(),pending=productUiState().pendingAct;meta.innerHTML=`<span class="chip">${dt(clock.day)}</span><span class="chip">${world.season} · ${world.weather}${world.drought?' · Drought':''}</span><span class="chip herald-chip">${sigilBadge(ruling,'hud-sigil')} ♛ ${safeName(monarch?.name||annalsState().monarch)}</span><span class="chip">Treasury ${Math.round(e.treasury)}</span><span class="chip">Population ${pop.toLocaleString()}</span><span class="chip">Camera ${safeName(cam.mode)}</span>${pending?`<span class="chip act-chip">Place ${safeName(PRODUCT_ACT_LABELS[pending])}</span>`:''}`;document.querySelectorAll('#speed button').forEach(b=>b.classList.toggle('active',+b.dataset.speed===clock.speed))};
if(typeof document!=='undefined'){let style=document.createElement('style');style.textContent='.ui-tabs{display:flex;flex-wrap:wrap;gap:4px;margin:9px 0}.ui-tabs button{padding:4px 7px}.house-card{display:flex;width:100%;gap:10px;border:0;border-top:1px solid #7d6a5244;border-radius:0;padding:10px 0;background:transparent;text-align:left}.house-card:hover{background:#fff4}.house-copy{display:flex;min-width:0;flex:1;flex-direction:column;gap:3px}.house-copy small{font-weight:400;line-height:1.3}.house-sigil{display:block;width:42px;height:42px;image-rendering:auto;border:1px solid #3b2c1d;border-radius:4px;background:#eadcc0}.hud-sigil{width:18px;height:18px;border:1px solid #3b2c1d;border-radius:3px;vertical-align:-5px;margin-right:3px}.inspector-heraldry{display:flex;align-items:center;gap:9px}.inspector-heraldry .inspector-title{margin:0}.inspector-close{float:right}.herald-chip{display:inline-flex;align-items:center}.rate-control{display:block;margin-top:12px}.rate-control>span{display:flex;justify-content:space-between;gap:8px;font-weight:700}.rate-control input{width:100%;accent-color:#9b7518}.rate-control small{display:block;color:#584934;line-height:1.35}.button-flow{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.button-flow button{font-size:11px}.targeting-copy{padding:7px;border:1px solid #9b7518;background:#fff4d6}.act-chip{background:#c9a227;color:#241b0b}';document.head.appendChild(style)}
if(typeof window!=='undefined'){window.setDrawerTab=setDrawerTab;window.setTaxRate=setTaxRate;window.setProductRate=setProductRate;window.beginTargetedAct=beginTargetedAct;window.cancelTargetedAct=cancelTargetedAct;window.inspectTrade=inspectTrade;window.inspectArmy=inspectArmy;window.inspectBandit=inspectBandit;window.inspectDragon=inspectDragon;window.inspectSettlementById=inspectSettlementById;window.inspectBuildingById=inspectBuildingById;window.inspectHouse=inspectHouse;window.closeInspector=closeInspector;window.toggleWatchMode=toggleWatchMode;window.copySeedLink=copySeedLink;addEventListener('keydown',event=>{if(world&&['Escape','KeyC','KeyH'].includes(event.code)&&productUiState().pendingAct)cancelTargetedAct()})}
