;function productUiState(){return world.productUiState||(world.productUiState={tab:'time'})}
function setDrawerTab(tab){productUiState().tab=['time','rates','acts','world','houses'].includes(tab)?tab:'time';drawer()}
function setTaxRate(value){let rate=clamp(Number(value)/100,0,0.3),state=economyState();state.taxRate=rate;for(const h of world.houses.slice(1)){h.loyalty=clamp(h.loyalty-(rate-.08)*1.5,0,100)}hud();drawer()}
function uiPopulation(){return Math.round(world.settlements.reduce((n,s)=>n+s.pop,0))}
function uiMonarch(){return characterById(world.story.monarchId)||characterState().registry.find(c=>c.role==='monarch'&&c.status==='alive')||null}
function inspectTrade(id){let t=economyState().trades.find(x=>x.id===id);if(!t)return;let from=world.settlements[t.fromId],to=world.settlements[t.toId];showProductInspector(`<h3 class="inspector-title">${safeName(t.good)} caravan</h3><div class="kv"><b>Route</b><span>${safeName(from.name)} → ${safeName(to.name)}</span><b>Cargo</b><span>${Math.round(t.amount)} ${safeName(t.good)}</span><b>Status</b><span>${safeName(t.status)}</span><b>Progress</b><span>${Math.round((t.progress||0)*100)}%</span><b>Arrival</b><span>${dt(t.arrivalDay)}</span></div>`)}
function inspectArmy(id){let a=warState().armies.find(x=>x.id===id);if(!a)return;let commander=characterById(a.commanderId),house=world.houses[a.houseId];showProductInspector(`<h3 class="inspector-title">${safeName(a.side)} army</h3><div class="kv"><b>House</b><span>${safeName(house?.name)}</span><b>Commander</b><span>${safeName(commander?.name)}</span><b>Strength</b><span>${Math.round(a.strength)}</span><b>Supply</b><span>${Math.round(a.supply)}</span><b>Morale</b><span>${Math.round(a.morale)}</span><b>Status</b><span>${safeName(a.status)}</span></div>`)}
function inspectBandit(id){let c=threatState().banditCamps.find(x=>x.id===id);if(!c)return;let king=characterById(c.kingId);showProductInspector(`<h3 class="inspector-title">Road camp</h3><div class="kv"><b>Strength</b><span>${Math.round(c.strength)}</span><b>Ambushes</b><span>${c.ambushes}</span><b>Status</b><span>${safeName(c.status)}</span><b>Leader</b><span>${safeName(king?`${king.name} ${king.epithet||''}`:'No crowned leader')}</span><b>Stable ID</b><span>${safeName(c.id)}</span></div>`)}
function inspectDragon(){let d=threatState().dragon,r=d.raids.at(-1),s=r&&world.settlements[r.settlementId];showProductInspector(`<h3 class="inspector-title">The dragon</h3><div class="kv"><b>State</b><span>${d.awake?'Awake':'Absent'}</span><b>Last raid</b><span>${r?dt(r.day):'None recorded'}</span><b>Target</b><span>${safeName(s?.name||'—')}</span><b>Tribute</b><span>${r?Math.round(r.tribute)+' crowns':'—'}</span><b>Myth</b><span>${safeName(threatState().myth)}</span></div>`)}
function showProductInspector(html){let el=document.getElementById('inspect');el.style.display='block';el.innerHTML=`<button style="float:right" onclick="closeInspector()">×</button>${html}`;director.suspend=clock.day+20}
function closeInspector(){let el=document.getElementById('inspect');if(el)el.style.display='none'}
function productTabButton(id,label){return`<button class="${productUiState().tab===id?'active':''}" onclick="setDrawerTab('${id}')">${label}</button>`}
function timePanel(){return`<div class="section"><b>Time</b><p class="small">Simulation speed changes how quickly days pass; camera and rendering continue smoothly.</p><div class="grid"><button onclick="clock.speed=0">Pause</button><button onclick="clock.speed=.5">1×</button><button onclick="clock.speed=2">4×</button><button onclick="clock.speed=8">16×</button><button onclick="clock.speed=30">60×</button><button onclick="document.body.classList.toggle('watch')">Watch mode</button></div></div>`}
function ratesPanel(){let e=economyState();return`<div class="section"><b>Rates</b><label class="small" for="tax-rate">Trade tax <b>${Math.round(e.taxRate*100)}%</b></label><input id="tax-rate" type="range" min="0" max="30" step="1" value="${Math.round(e.taxRate*100)}" onchange="setTaxRate(this.value)"><p class="small">Higher customs increase treasury receipts but apply immediate loyalty pressure to non-ruling houses.</p><div class="kv"><b>Treasury</b><span>${Math.round(e.treasury)} crowns</span><b>Tax collected</b><span>${Math.round(e.taxCollected)} crowns</span></div></div>`}
function actsPanel(){let s=pressure();return`<div class="section"><b>Acts</b><p class="small">These working royal acts target the realm's current pressure point: <b>${safeName(s.name)}</b>.</p><div class="grid"><button onclick="act('grain')">Release grain</button><button onclick="act('festival')">Proclaim festival</button><button onclick="act('drought')">Declare drought</button><button onclick="act('fire')">Start great fire</button></div><p class="small">Every act records its cause and consequences in the Chronicle.</p></div>`}
function worldPanel(){let trades=economyState().trades.filter(t=>t.status==='travelling').slice(0,5),armies=warState().armies.filter(a=>a.status!=='destroyed').slice(0,5),camps=threatState().banditCamps.filter(c=>c.status==='active');return`<div class="section"><b>World</b><div class="kv"><b>Seed</b><span>${safeName(world.seed)}</span><b>Population</b><span>${uiPopulation().toLocaleString()}</span><b>Settlements</b><span>${world.settlements.length}</span><b>Buildings</b><span>${world.buildings.length}</span><b>LOD</b><span>${typeof atmosphereState==='function'?safeName(atmosphereState().band):'—'}</span></div></div><div class="section"><b>Moving subjects</b><p class="small">${trades.map(t=>`<button onclick="inspectTrade('${t.id}')">${safeName(t.good)} caravan</button>`).join(' ')||'No caravan is currently travelling.'}</p><p class="small">${armies.map(a=>`<button onclick="inspectArmy('${a.id}')">${safeName(a.side)} army</button>`).join(' ')||'No army is currently active.'}</p><p class="small">${camps.map(c=>`<button onclick="inspectBandit('${c.id}')">Bandit camp</button>`).join(' ')||'No active bandit camp.'}</p><button onclick="inspectDragon()">Inspect dragon</button></div><div class="section"><button onclick="location.hash='s='+Date.now();location.reload()">Reforge</button> <button onclick="navigator.clipboard&&navigator.clipboard.writeText(location.href)">Copy link</button> <button onclick="exportChronicle()">Export Chronicle</button></div>`}
function housesPanel(){return`<div class="section"><b>Great Houses</b>${world.houses.map((h,i)=>{let seat=world.settlements[h.seatSettlement],dyn=typeof dynastyForHouse==='function'?dynastyForHouse(i):null;return`<div class="house-card"><span class="house-sigil" style="background:${safeName(h.colour)}"></span><b>${safeName(h.name)}</b><p class="small">Seat ${safeName(seat?.name||'—')} · loyalty ${Math.round(h.loyalty)} · might ${Math.round(h.might||0)}${h.rebellious?' · REBELLIOUS':''}</p><span class="bar"><span style="width:${clamp(h.loyalty,0,100)}%"></span></span><p class="small">${dyn?`${safeName(dyn.name)} · ${safeName(dyn.status)}`:'Dynasty not recorded'}</p></div>`}).join('')}</div>`}
const productBaseDrawer=drawer;
drawer=function(){let tabs=`<div class="ui-tabs">${productTabButton('time','Time')}${productTabButton('rates','Rates')}${productTabButton('acts','Acts')}${productTabButton('world','World')}${productTabButton('houses','Houses')}</div>`,content={time:timePanel,rates:ratesPanel,acts:actsPanel,world:worldPanel,houses:housesPanel}[productUiState().tab]();document.getElementById('drawer').innerHTML=`<b>ANNALS ${safeName(world.version)}</b>${tabs}${content}<p class="small">Hotkeys: Space pause · 1–4 speed · H hide UI · C Watch · Esc deselect.</p>`};
const productBaseHud=hud;
hud=function(){let monarch=uiMonarch(),e=economyState(),cam=typeof cinematicState==='function'?cinematicState():{mode:'director'},pop=uiPopulation();meta.innerHTML=`<span class="chip">${dt(clock.day)}</span><span class="chip">${world.season} · ${world.weather}${world.drought?' · Drought':''}</span><span class="chip">♛ ${safeName(monarch?.name||annalsState().monarch)}</span><span class="chip">Treasury ${Math.round(e.treasury)}</span><span class="chip">Population ${pop.toLocaleString()}</span><span class="chip">Camera ${safeName(cam.mode)}</span>`;document.querySelectorAll('#speed button').forEach(b=>b.classList.toggle('active',+b.dataset.speed===clock.speed))};
if(typeof document!=='undefined'){let style=document.createElement('style');style.textContent='.ui-tabs{display:flex;flex-wrap:wrap;gap:4px;margin:9px 0}.ui-tabs button{padding:4px 7px}.house-card{border-top:1px solid #7d6a5244;padding:8px 0}.house-sigil{display:inline-block;width:12px;height:12px;border:1px solid #3b2c1d;margin-right:5px;vertical-align:-1px}input[type=range]{width:100%;accent-color:#9b7518}';document.head.appendChild(style)}
if(typeof window!=='undefined'){window.setDrawerTab=setDrawerTab;window.setTaxRate=setTaxRate;window.inspectTrade=inspectTrade;window.inspectArmy=inspectArmy;window.inspectBandit=inspectBandit;window.inspectDragon=inspectDragon;window.closeInspector=closeInspector}
