function riverFrom(x,z,target){let pts=[];for(let i=0;i<120;i++){let h=hWorld(x,z);pts.push({x,z,y:h});if(h<3||Math.abs(x)>2880||Math.abs(z)>2880||(target&&dist({x,z},target)<100))break;let best,score=1e9;for(let a=0;a<TAU;a+=.63){let nx=x+90*Math.cos(a),nz=z+90*Math.sin(a),cost=hWorld(nx,nz)-h+(target?dist({x:nx,z:nz},target)/130:Math.max(Math.abs(nx),Math.abs(nz))/850)+16*signed(terrainSpec.seed+i,nx/380,nz/380);if(cost<score){best={x:nx,z:nz};score=cost}}x=best.x;z=best.z}return pts}
function hydrology(){let highs=[];for(let i=0;i<140;i++){let x=rnd(genR,-2600,2600),z=rnd(genR,-2600,2600),h=hWorld(x,z);if(h>250)highs.push({x,z,h})}highs.sort((a,b)=>b.h-a.h);let paths=[],starts=[];for(const s of highs){if(paths.length>=3)break;if(starts.some(p=>dist(p,s)<950))continue;let p=riverFrom(s.x,s.z);if(p.length>18){paths.push(p);starts.push(s)}}if(!paths.length)paths.push(riverFrom(0,-1200));let main=paths[0];for(let i=1;i<3;i++){let j=main[Math.min(main.length-4,Math.floor(main.length*(.3+.18*i)))],p=riverFrom(j.x+rnd(genR,-1200,1200),j.z+rnd(genR,-1200,1200),j);if(p.length>12)paths.push(p)}let lakes=[];for(const p of paths)for(let i=8;i<p.length-8;i+=13)if(Math.abs(p[i-2].y-p[i+2].y)<8&&p[i].y<120&&genR()<.35)lakes.push({x:p[i].x,z:p[i].z,r:rnd(genR,110,240)});return{paths,lakes:lakes.slice(0,4),mouth:main.at(-1)}}
function resources(h){let out=[],add=(type,x,z,val=1)=>{if(out.length<120&&(hWorld(x,z)>2||type==='fishing'))out.push({type,x,z,y:hWorld(x,z),val})};for(let i=0;i<220;i++){let x=rnd(genR,-2700,2700),z=rnd(genR,-2700,2700),b=biome(x,z),hh=hWorld(x,z),r=nearRiver(h.paths,x,z);if((b==='farmland'||hh<160&&moisture(x,z)>.42)&&r<650)add('farmland',x,z,1.2);else if(b==='forest'&&genR()<.45)add('forest',x,z);else if(hh>250&&slope(x,z)>.12&&genR()<.25)add('ore',x,z,1.3)}for(const p of h.paths)for(let i=5;i<p.length;i+=10)add('fishing',p[i].x+rnd(genR,-90,90),p[i].z+rnd(genR,-90,90),1.1);if(terrainSpec.coast.active){for(let i=0;i<300;i++){let x=rnd(genR,-2850,2850),z=rnd(genR,-2850,2850),hh=hWorld(x,z),d=coastDist(x,z);if(d>-140&&d<290&&hh>3&&hh<180&&slope(x,z)<.5)add('harbour',x,z,1.7)}if(!out.some(x=>x.type==='harbour'))add('harbour',0,0,1.2)}return out}
function scoreSite(x,z,h,res,force=0){let y=hWorld(x,z),r=nearRiver(h.paths,x,z),near=res.filter(q=>Math.hypot(q.x-x,q.z-z)<560),harbour=force||near.some(q=>q.type==='harbour')||terrainSpec.coast.active&&coastDist(x,z)>-180&&coastDist(x,z)<320&&y>2&&y<160,flat=clamp(1-3.8*slope(x,z),0,1),defence=clamp(y/8+45*slope(x,z)+(r<260?8:0),0,70),value=near.reduce((a,q)=>a+({harbour:24,farmland:18,ore:12,fishing:10,forest:8}[q.type]||5)*q.val,0),sc=value+(r<360?44:harbour?36:0)+46*flat+.65*defence-(y<5||y>560||flat<.2?999:0)+(force?90:0);return{x,z,y,score:sc,valid:sc>-100,waterAccess:r<360?'river':harbour?'coast':'none',harbour:!!harbour,resources:[...new Set(near.map(q=>q.type))],biome:biome(x,z),defence,flat}}
function settlements(h,res){let c=[];for(let i=0;i<900;i++){let q=scoreSite(rnd(genR,-2550,2550),rnd(genR,-2550,2550),h,res);if(q.valid)c.push(q)}c.sort((a,b)=>b.score-a.score);let out=[],ok=(q,d)=>out.every(o=>dist(o,q)>d),cap=c.find(q=>q.y>130&&q.y<420&&q.defence>36)||c[0];cap.type='capital';out.push(cap);let har=res.filter(q=>q.type==='harbour').map(q=>scoreSite(q.x,q.z,h,res,1)).sort((a,b)=>b.score-a.score)[0];if(terrainSpec.coast.active&&har){har.type='town';out.push(har)}for(const q of c){if(out.length>=9)break;if(ok(q,out.length<4?720:560)){q.type=out.length<4?'town':'village';out.push(q)}}return out.slice(0,9).map((q,i)=>({id:i,name:place(genR),type:q.type,x:q.x,z:q.z,y:q.y,pop:q.type==='capital'?irnd(genR,2200,3200):q.type==='town'?irnd(genR,700,1400):irnd(genR,170,460),fert:clamp(.7+.72*moisture(q.x,q.z)+(q.resources.includes('farmland')?.25:0)-(q.y>380?.18:0),.5,1.6),prosperity:irnd(genR,48,78)+Math.floor(q.score/45),hunger:irnd(genR,4,16),unrest:irnd(genR,8,24),owner:Math.min(i,5),site:q,stores:{grain:1000,fish:300},crisis:{short:0,last:-999},growth:{last:0,next:90+irnd(genR,0,80)}}))}
function route(a,b,h){let pts=[{x:a.x,z:a.z,y:a.y+3}],bridges=[],x=a.x,z=a.z,lastBridge=-99,max=Math.ceil(dist(a,b)/85)+80;for(let i=0;i<max;i++){if(Math.hypot(b.x-x,b.z-z)<95)break;let angle=Math.atan2(b.z-z,b.x-x),best,bc=1e9;for(let j=-3;j<=3;j++){let aa=angle+.33*j+.18*signed(terrainSpec.seed+i,x/420,z/420),nx=x+85*Math.cos(aa),nz=z+85*Math.sin(aa),cost=.018*Math.hypot(b.x-nx,b.z-nz)+210*slope(nx,nz)+(biome(nx,nz)==='forest'?18:0)+(hWorld(nx,nz)<2?400:0),rv=nearRiver(h.paths,nx,nz);cost+=rv<48&&i-lastBridge>5?65:rv<48?210:0;if(cost<bc){best={x:nx,z:nz,rv};bc=cost}}if(best.rv<48&&i-lastBridge>5){bridges.push({x:best.x,z:best.z,y:hWorld(best.x,best.z)+9});lastBridge=i}x=best.x;z=best.z;pts.push({x,z,y:hWorld(x,z)+4})}pts.push({x:b.x,z:b.z,y:b.y+3});return{a:a.id,b:b.id,pts,bridges}}
function directness(r){let l=0;for(let i=1;i<r.pts.length;i++)l+=Math.hypot(r.pts[i].x-r.pts[i-1].x,r.pts[i].z-r.pts[i-1].z);return l/Math.max(1,dist(world.settlements[r.a],world.settlements[r.b]))}
function streetPoint(s,ang,d){return{x:s.x+Math.cos(ang)*d,z:s.z+Math.sin(ang)*d,y:hWorld(s.x+Math.cos(ang)*d,s.z+Math.sin(ang)*d)+6}}
function settlementEntryAngles(s,roads){let a=[];for(const r of roads){if(r.a===s.id&&r.pts[1])a.push(angleTo(s,r.pts[1]));if(r.b===s.id&&r.pts[r.pts.length-2])a.push(angleTo(s,r.pts[r.pts.length-2]))}if(!a.length)a.push(rnd(genR,-Math.PI,Math.PI));return a.slice(0,5)}
function districtFor(s,ang,d,harbourAng){if(s.type==='village')return d<70?'market':(Math.abs(Math.sin(ang))>.72?'artisan':'residential');if(harbourAng!==null&&Math.abs(Math.atan2(Math.sin(ang-harbourAng),Math.cos(ang-harbourAng)))<.55)return'warehouse';if(d<100)return'market';if(s.type==='capital'&&d<180)return d<95?'keep':'old core';if(ang>1.0&&ang<2.4)return'temple';if(ang>-1.1&&ang<.6)return'artisan';return'residential'}
function typeForLot(s,district,i,d){if(district==='keep')return i%5?'tower':'keep';if(district==='old core')return i%9===0?'tower':i%6===0?'shop':'house';if(district==='market')return i%7===0?'tavern':i%3===0?'shop':i%5===0?'granary':'house';if(district==='artisan')return i%4===0?'smithy':i%6===0?'mill':i%3===0?'shop':'longhouse';if(district==='temple')return i%5===0?'temple':'house';if(district==='warehouse')return i%3?'warehouse':'granary';return d>170&&i%6===0?'longhouse':'house'}
function tierForLot(s,d){return s.type==='capital'&&d<220?'stone':s.type==='village'&&d>115?'hovel':s.prosperity>76||d<95?'stone':'timber'}
function buildingGoods(type,s){let g={};if(type==='granary'||type==='warehouse')g.grain=Math.round(s.stores.grain*(type==='granary'?.18:.11));if(type==='warehouse')g.fish=Math.round(s.stores.fish*.22);if(type==='shop'||type==='tavern')g.goods=irnd(genR,8,38);if(type==='smithy')g.ore=irnd(genR,5,18);return g}
function makeLot(s,i,x,z,ang,offset,district,type,tier,state='inhabited'){let lot={id:`${s.id}-${i}`,settlementId:s.id,x,z,y:hWorld(x,z)+7,angle:ang,distance:Math.hypot(x-s.x,z-s.z),district,type,tier,state,households:type==='house'?irnd(genR,1,tier==='stone'?4:2):type==='longhouse'?irnd(genR,3,8):0,stored:buildingGoods(type,s),birthDay:Math.floor(clock.day||1)};let b={id:'b-'+lot.id,lotId:lot.id,settlementId:s.id,type,tier,state,x,y:lot.y,z,angle:ang,district,households:lot.households,stored:lot.stored,ruinDay:null,rebuildDay:null};lot.building=b;world.buildings.push(b);return lot}
function addStreetLot(s,ang,d,side,i,district,type,tier){let off=side*(s.type==='village'?28:rnd(genR,32,58)),x=s.x+Math.cos(ang)*d+Math.cos(ang+Math.PI/2)*off,z=s.z+Math.sin(ang)*d+Math.sin(ang+Math.PI/2)*off;if(hWorld(x,z)<2)return null;return makeLot(s,s.layout.nextLotId++,x,z,ang,off,district,type||typeForLot(s,district,i,d),tier||tierForLot(s,d))}
function makeSettlementLayout(s,roads){let entry=settlementEntryAngles(s,roads),size=s.type==='capital'?340:s.type==='town'?230:135,streets=[],lots=[],market={x:s.x,z:s.z,y:s.y+8},harbourAng=s.site.harbour?angleTo(s,{x:s.x+(terrainSpec.coast.side==='west'?-1:terrainSpec.coast.side==='east'?1:0),z:s.z+(terrainSpec.coast.side==='north'?-1:terrainSpec.coast.side==='south'?1:0)}):null;
  s.layout={size,market,streets,lots,nextLotId:1,districts:[],entryAngles:entry,oldCore:s.type==='capital'};
  if(s.type==='village'){
    let a=entry[0],b=a+Math.PI/2;streets.push({kind:'crossroad',district:'market',pts:[streetPoint(s,a+Math.PI,size),streetPoint(s,a,size)]},{kind:'lane',district:'residential',pts:[streetPoint(s,b+Math.PI,size*.65),streetPoint(s,b,size*.65)]});
    let count=irnd(genR,11,18);for(let i=0;i<count;i++){let aa=i%3===0?b:a,d=rnd(genR,38,size*.9),side=i%2?1:-1,distc=districtFor(s,aa,d,harbourAng),type=i===0?'tavern':i===1?'granary':i===2?'mill':null,lot=addStreetLot(s,aa,d,side,i,distc,type);if(lot)lots.push(lot)}
  }else{
    let radial=[...entry];while(radial.length<(s.type==='capital'?8:6))radial.push(radial[radial.length-1]+TAU/(s.type==='capital'?8:6)+rnd(genR,-.18,.18));
    for(const a of radial)streets.push({kind:'radial',district:'mixed',pts:[streetPoint(s,a,-size*.18),streetPoint(s,a,size)]});
    for(const rr of (s.type==='capital'?[120,220,315]:[95,170])){let pts=[];for(let k=0;k<=32;k++){let a=TAU*k/32;pts.push(streetPoint(s,a,rr))}streets.push({kind:'ring',district:rr<130?'market':'residential',pts})}
    let count=s.type==='capital'?irnd(genR,190,235):irnd(genR,78,112);for(let i=0;i<count;i++){let a=radial[i%radial.length]+rnd(genR,-.11,.11),d=s.type==='capital'?rnd(genR,58,310):rnd(genR,48,205),side=i%2?1:-1,distc=districtFor(s,a,d,harbourAng),lot=addStreetLot(s,a,d,side,i,distc);if(lot)lots.push(lot)}
    if(s.type==='capital'){for(let k=0;k<18;k++){let a=TAU*k/18,p=streetPoint(s,a,size+12),type=k%6===0?'gate':'wall';lots.push(makeLot(s,s.layout.nextLotId++,p.x,p.z,a,0,'wall',type,'stone','fortified'))}}
  }
  s.layout.districts=[...new Set(lots.map(l=>l.district))];return s.layout}
function settlementLayouts(){world.buildings=[];for(const s of world.settlements)makeSettlementLayout(s,world.roads);return world.buildings}
function growSettlement(s){if(!s.layout||s.layout.lots.length>420||clock.day<s.growth.next)return;let pressure=(s.prosperity*.45+s.pop/80-s.hunger*.5-s.unrest*.35);if(pressure<42)return;s.growth.next=clock.day+80+irnd(hisR,0,90);let a=pick(hisR,s.layout.entryAngles),d=s.layout.size+rnd(hisR,25,90),district=s.site.harbour&&hisR()<.35?'warehouse':s.type==='village'?'residential':hisR()<.45?'residential':'artisan',type=typeForLot(s,district,s.layout.nextLotId,d),tier=tierForLot(s,d);let off=(hisR()<.5?-1:1)*rnd(hisR,34,62),x=s.x+Math.cos(a)*d+Math.cos(a+Math.PI/2)*off,z=s.z+Math.sin(a)*d+Math.sin(a+Math.PI/2)*off;if(hWorld(x,z)<2)return;let lot=makeLot(s,s.layout.nextLotId++,x,z,a,off,district,type,tier);s.layout.lots.push(lot);s.layout.districts=[...new Set(s.layout.lots.map(l=>l.district))];s.pop=clamp(s.pop+(type==='house'?lot.households:1)*4,30,9000);chron('trade',7,lot,`${s.name} cut lot ${lot.id} on the ${district} edge; prosperity and population pressure turned open ground into a ${tier} ${type}.`);refreshSettlementDetails()}
function markBuildingState(b,state){b.state=state;let s=world.settlements[b.settlementId],lot=s&&s.layout&&s.layout.lots.find(l=>l.id===b.lotId);if(lot){lot.state=state;lot.building=b}}
function damageBuildings(s,n=2,cause='fire'){let pool=s.layout?s.layout.lots.filter(l=>!['wall','gate','keep'].includes(l.type)&&l.building&&l.building.state==='inhabited'):[];for(let i=0;i<n&&pool.length;i++){let lot=pool.splice(irnd(hisR,0,pool.length-1),1)[0],b=lot.building;markBuildingState(b,'ruin');b.ruinDay=clock.day;chron('fate',8,lot,`A ${cause} left lot ${lot.id} in ${s.name} a ruin; the plot remains in the town record so rebuilding can follow the old street line.`)}refreshSettlementDetails()}
function rebuildTick(s){if(!s.layout)return;for(const lot of s.layout.lots){let b=lot.building;if(!b)continue;if(b.state==='ruin'&&clock.day-b.ruinDay>36&&s.prosperity>38&&food(s)>.06*s.pop){markBuildingState(b,'rebuilding');b.rebuildDay=clock.day;chron('trade',6,lot,`${s.name} reopened lot ${lot.id}; masons kept the old boundary while raising a new ${b.tier} ${b.type}.`);refreshSettlementDetails()}else if(b.state==='rebuilding'&&clock.day-b.rebuildDay>24){markBuildingState(b,'inhabited');refreshSettlementDetails()}}}
function makeWorld(seed){genR=rng(seed,'generation');hisR=rng(seed,'history');world=null;terrainSpec=makeTerrainSpec(seed);let hyd=hydrology(),res=resources(hyd),set=settlements(hyd,res),roads=[];for(let i=1;i<set.length;i++){roads.push(route(set[0],set[i],hyd));if(i<set.length-1&&i%2)roads.push(route(set[i],set[i+1],hyd))}world={seed,title:place(genR),version:'v0.8',terrainSpec,hydrology:hyd,riverPaths:hyd.paths,rivers:hyd.paths,resources:res,settlements:set,houses:[],buildings:[],roads,events:[],filter:'all',season:'Spring',weather:'Clear',drought:false,story:{last:0,drought:112+Math.floor(hisR()*29)}};for(let i=0;i<6;i++)world.houses.push({id:i,name:'House '+(i?pick(genR,BEAST)+' '+pick(genR,B):pick(genR,BEAST)),seatSettlement:Math.min(i,set.length-1),colour:['#8b1e2d','#235d86','#3d7b47','#8b6b23','#6f3c87','#7b3f22'][i],loyalty:i?irnd(genR,46,85):100,rebellious:false});settlementLayouts();return world}
