;const CAMERA_MODES=['free','follow','director'],CAMERA_COOLDOWN_DAYS=24;
function cinematicState(){return world.cinematicState||(world.cinematicState={mode:'director',follow:null,shot:null,lastCategory:{},manualUntil:0,shots:[],lowerThird:null,orbit:0,zoom:900})}
function setCameraMode(mode,target=null){let s=cinematicState();s.mode=CAMERA_MODES.includes(mode)?mode:'director';s.follow=target;camera.userData.fly=null;if(s.mode==='free')director.suspend=Math.max(director.suspend,clock.day+30);return s.mode}
function followTrade(id){let t=economyState().trades.find(x=>x.id===id);if(t)setCameraMode('follow',{kind:'trade',id:t.id,name:`${t.good} caravan`})}
function followArmy(id){let a=warState().armies.find(x=>x.id===id);if(a)setCameraMode('follow',{kind:'army',id:a.id,name:`${a.side} army`})}
function followDragon(){let d=threatState().dragon;if(d.awake&&d.raids.length)setCameraMode('follow',{kind:'dragon',id:'dragon',name:'the dragon'})}
function followTargetPosition(f){if(!f)return null;if(f.kind==='trade'){let t=economyState().trades.find(x=>x.id===f.id);if(!t||t.status!=='travelling')return null;let pts=t.points||[],n=Math.max(1,pts.length-1),v=clamp(t.progress,0,1)*n,i=Math.min(pts.length-1,Math.floor(v)),j=Math.min(pts.length-1,i+1),u=v-i,a=pts[i]||world.settlements[t.fromId],b=pts[j]||a;return{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u,z:a.z+(b.z-a.z)*u,heading:Math.atan2(b.x-a.x,b.z-a.z)}}if(f.kind==='army'){let a=warState().armies.find(x=>x.id===f.id);if(!a||a.status==='destroyed')return null;let p=armyPosition(a);return{...p,heading:0}}if(f.kind==='dragon'){let raid=threatState().dragon.raids.at(-1),s=raid&&world.settlements[raid.settlementId];return threatState().dragon.awake&&s?{x:s.x,y:s.y+150,z:s.z,heading:clock.day*.05}:null}return null}
function manualCameraInput(){let s=cinematicState();s.mode='free';s.manualUntil=clock.day+45;director.suspend=Math.max(director.suspend,s.manualUntil);camera.userData.fly=null}
function shotCategory(e){return e.kind||e.class||'idle'}
function shotGrammar(e){let k=shotCategory(e),p=e.pos||world.settlements[0];if(k==='war'||e.class==='war')return{type:'low tracking',target:p,alt:260,offset:520,duration:28};if(k==='dragon')return{type:'high reveal',target:p,alt:680,offset:820,duration:34};if(k==='plague'||k==='famine'||e.class==='fate')return{type:'slow orbit',target:p,alt:480,offset:620,duration:30};if(k==='trade'||e.class==='trade')return{type:'push-in',target:p,alt:360,offset:560,duration:24};if(e.header||e.class==='crown')return{type:'territory view',target:p,alt:820,offset:920,duration:32};return{type:'wide',target:p,alt:620,offset:760,duration:24}}
function beginShot(e){let s=cinematicState(),g=shotGrammar(e),cat=shotCategory(e);s.mode='director';s.shot={...g,category:cat,startDay:clock.day,priority:e.priority||5,angle:(world.seed+clock.day)%TAU};s.lastCategory[cat]=clock.day;s.lowerThird={title:safeName(e.location||world.title),text:safeName(e.text||cat),until:clock.day+8};s.shots.push({day:Math.floor(clock.day),category:cat,type:g.type,priority:e.priority||5});if(s.shots.length>80)s.shots.shift();director.until=clock.day+g.duration}
const cinematicBaseFly=fly;
fly=function(pos,alt=600,dur=2200){let s=cinematicState();s.mode='director';s.shot=null;return cinematicBaseFly(pos,Math.max(90,alt),dur)};
move=function(dt){let s=cinematicState(),target=camera.userData.target,desiredTarget=target.clone(),desiredPos=camera.position.clone();if(['KeyW','KeyA','KeyS','KeyD'].some(k=>keys[k]))manualCameraInput();if(s.mode==='free'){let sp=900*dt;if(keys.KeyW)desiredTarget.z-=sp;if(keys.KeyS)desiredTarget.z+=sp;if(keys.KeyA)desiredTarget.x-=sp;if(keys.KeyD)desiredTarget.x+=sp;desiredPos.set(desiredTarget.x,camera.position.y,desiredTarget.z+camera.position.y/Math.tan(.55))}else if(s.mode==='follow'){let p=followTargetPosition(s.follow);if(!p){s.mode='director';s.follow=null}else{let low=s.follow.kind==='dragon'?420:190,dist=s.follow.kind==='dragon'?720:390,ang=(p.heading||0)+Math.PI;desiredTarget.set(p.x,p.y+18,p.z);desiredPos.set(p.x+Math.sin(ang)*dist,Math.max(hWorld(p.x,p.z)+low,p.y+low),p.z+Math.cos(ang)*dist)}}else if(s.shot){let q=s.shot,u=clamp((clock.day-q.startDay)/Math.max(1,q.duration),0,1),ang=q.angle+(q.type==='slow orbit'?u*1.3:q.type==='territory view'?u*.35:0),curve=Math.sin(u*Math.PI),alt=q.alt-(q.type==='push-in'?curve*120:0);desiredTarget.set(q.target.x,hWorld(q.target.x,q.target.z)+20,q.target.z);desiredPos.set(q.target.x+Math.sin(ang)*q.offset,Math.max(hWorld(q.target.x,q.target.z)+90,alt),q.target.z+Math.cos(ang)*q.offset)}else{desiredPos.set(target.x,camera.position.y,target.z+camera.position.y/Math.tan(.55))}let terrainFloor=hWorld(desiredPos.x,desiredPos.z)+70;desiredPos.y=Math.max(desiredPos.y,terrainFloor);let stiffness=1-Math.exp(-4.5*dt);target.lerp(desiredTarget,stiffness);camera.position.lerp(desiredPos,stiffness);camera.position.y=Math.max(camera.position.y,hWorld(camera.position.x,camera.position.z)+55);camera.lookAt(target.x,Math.max(hWorld(target.x,target.z)+12,target.y),target.z);if(settlementDetailGroup)settlementDetailGroup.visible=camera.position.y<2500}
directorTick=function(){let s=cinematicState();if(s.mode==='free'&&clock.day<s.manualUntil)return;if(s.mode==='follow')return;if(director.queue.length&&clock.day>director.suspend){director.queue.sort((a,b)=>b.priority-a.priority||b.day-a.day);let idx=director.queue.findIndex(e=>(e.priority||0)>=9||clock.day-(s.lastCategory[shotCategory(e)]??-999)>CAMERA_COOLDOWN_DAYS);if(idx>=0){let e=director.queue.splice(idx,1)[0];if(!s.shot||(e.priority||0)>s.shot.priority||clock.day>director.until)beginShot(e)}}if((!s.shot||clock.day>director.until)&&clock.day>director.suspend){let p=pick(hisR,world.settlements);beginShot({pos:p,location:p.name,text:`Evening light moved across ${p.name}.`,kind:'idle',class:'trade',priority:3})}}
function cameraSummary(){let s=cinematicState();return{mode:s.mode,follow:s.follow?{...s.follow}:null,shot:s.shot?{type:s.shot.type,category:s.shot.category,priority:s.shot.priority}:null,manualUntil:s.manualUntil,shots:s.shots.slice(-20),terrainClearance:Math.round(camera?camera.position.y-hWorld(camera.position.x,camera.position.z):0)}}
if(typeof window!=='undefined'){window.addEventListener('wheel',e=>{if(!camera)return;manualCameraInput();camera.position.y=clamp(camera.position.y+e.deltaY*.7,90,4200)},{passive:true});window.addEventListener('pointerdown',e=>{if(e.target===renderer?.domElement&&e.button===1)manualCameraInput()});window.ANNALS_CAMERA={setMode:setCameraMode,followTrade,followArmy,followDragon,summary:cameraSummary}}
