;const CULTURE_PROFILES=[
{id:'valic',label:'Vale Cant',roots:'Vael Ael Mere Cor Thal Bren Ys Oren Sel Car'.split(' '),suffixes:'mere ford holt wyck haven field watch caster'.split(' '),male:'Edric Owyn Alaric Corren Bran Theon Osric Cael'.split(' '),female:'Alda Merewen Ysabet Elin Ravenna Thora Aelin Cerys'.split(' '),neutral:'Iven Saren Rowan Aster Vale'.split(' '),surnames:'Vale Thornmere Ashford Raven Holt Fenwick Stonebridge Alder Merewatch'.split(' '),houseSuffixes:'holt watch mere ward'.split(' ')},
{id:'fenward',label:'Fenward Speech',roots:'Fen Reed Marsh Dun Wren Grey Low Mire Bell Tern'.split(' '),suffixes:'wyck mere ford fen marsh haven ey watch'.split(' '),male:'Darel Fenric Oswin Toman Wulfren Beran Leof'.split(' '),female:'Eda Wenna Rhos Elswyn Mera Tilda Anwen'.split(' '),neutral:'Reed Wren Ash Tern Moss'.split(' '),surnames:'Reed Fenner Marsh Greybank Lowmere Wrenford Bellwater Dunwyck'.split(' '),houseSuffixes:'fen reed mere bank'.split(' ')},
{id:'northmarch',label:'Northern March Tongue',roots:'Oster Bran Skel Harth Durn Calder Rook Tor Grim Varn'.split(' '),suffixes:'holt gard ford fell watch caster barrow bridge'.split(' '),male:'Haldor Brand Eirik Torren Calder Varek Oswin Rorik'.split(' '),female:'Sigrid Astren Brynja Hesta Runa Elva Tova'.split(' '),neutral:'Rook Winter Storm Ashen North'.split(' '),surnames:'Harthson Rookfell Calderborn Skelgard Torwatch Osterholt Grimward'.split(' '),houseSuffixes:'gard fell holt ward'.split(' ')},
{id:'coastborn',label:'Coastborn Cadence',roots:'Cor Sel Mar Taran Lys Aven Pel Mor Eren Nym'.split(' '),suffixes:'haven port mere quay wyck mouth reef watch'.split(' '),male:'Taran Corin Merek Pelan Aven Orren Lysander'.split(' '),female:'Mara Selene Nerys Aveline Corra Elara Tressa'.split(' '),neutral:'Tide Haven Reef Lark Azure'.split(' '),surnames:'Saltmere Waveborn Corhaven Tidemark Pelwyck Reefward Morquay'.split(' '),houseSuffixes:'tide haven reef mark'.split(' ')},
{id:'highland',label:'Highland Register',roots:'Ald Cair Thorn Raven Stone High Glen Bryn Crag Ember'.split(' '),suffixes:'hold fell gate watch barrow caster bridge vale'.split(' '),male:'Bryn Cadoc Alwyn Garran Emric Toren Rhodri'.split(' '),female:'Eira Catrin Morwen Nesta Bronwen Eluned Seren'.split(' '),neutral:'Cair Rowan Ember Vale Sky'.split(' '),surnames:'Cairnward Thornvale Ravenhold Stonegate Glenwatch Emberfell'.split(' '),houseSuffixes:'hold crag gate cairn'.split(' ')}
];
const HERALDIC_CHARGES='stag tower wave oak wolf comet key sun'.split(' '),HERALDIC_DIVISIONS=['plain','per-pale','per-fess','bend','chevron'];
const HERALDIC_PALETTE=['#8b1e2d','#235d86','#3d7b47','#8b6b23','#6f3c87','#7b3f22','#355f66','#7a3048','#4f6030','#93562f'];
const HERALDIC_LIGHT=['#f1dfaa','#d9e1df','#e2c97a','#c9d7b8','#e7d0c4','#d6c9e8'];
let cultureSpec=null;
function cultureCapitalise(value){let text=String(value||'');return text?text[0].toUpperCase()+text.slice(1).toLowerCase():''}
function cultureJoin(root,suffix){root=String(root||'');suffix=String(suffix||'');if(root.toLowerCase().endsWith(suffix.toLowerCase()))return cultureCapitalise(root);let a=root,b=suffix;if(/[aeiouy]$/i.test(a)&&/^[aeiouy]/i.test(b))a=a.slice(0,-1);return cultureCapitalise(a+b)}
function cultureForSeed(seed){let r=rng(seed,'culture-profile'),profile=CULTURE_PROFILES[Math.floor(r()*CULTURE_PROFILES.length)%CULTURE_PROFILES.length],realmName=cultureJoin(pick(r,profile.roots),pick(r,profile.suffixes)),given=[...profile.male.map(name=>({name,gender:'male'})),...profile.female.map(name=>({name,gender:'female'})),...profile.neutral.map(name=>({name,gender:'neutral'}))];return{...profile,realmName,title:`The Annals of ${realmName}`,given}}
function culturePlaceName(r){let c=cultureSpec||CULTURE_PROFILES[0];return cultureJoin(pick(r,c.roots),pick(r,c.suffixes))}
function cultureCharacterIdentity(r,houseId=null,home=null){let c=cultureSpec||cultureForSeed(world?.seed||'0'),given=pick(r,c.given),freeSurname=pick(r,c.surnames),house=Number.isInteger(houseId)&&world?.houses?world.houses[houseId]:null,surname=house?.familyName||freeSurname;return{name:`${given.name} ${surname}`,givenName:given.name,surname,gender:given.gender}}
function cultureHouseSigil(seed,id,charge){let r=rng(`${seed}:${id}`,'sigil'),fieldOffset=xmur3(`${seed}:sigil-field`)()%HERALDIC_PALETTE.length,field=HERALDIC_PALETTE[(fieldOffset+id)%HERALDIC_PALETTE.length],secondary=HERALDIC_LIGHT[(id+Math.floor(r()*HERALDIC_LIGHT.length))%HERALDIC_LIGHT.length],division=HERALDIC_DIVISIONS[(id+Math.floor(r()*HERALDIC_DIVISIONS.length))%HERALDIC_DIVISIONS.length],chosen=charge||HERALDIC_CHARGES[(id+Math.floor(r()*HERALDIC_CHARGES.length))%HERALDIC_CHARGES.length],signature=`${division}:${field}:${secondary}:${chosen}`;return{field,secondary,charge:chosen,division,signature}}
function cultureHouseIdentity(r,seat,id,seed){let c=cultureSpec||cultureForSeed(seed),motif=pick(r,HERALDIC_CHARGES),form=id===0?'seat':pick(r,['seat','charge','cadence']),familyName,displayName;if(form==='seat'){familyName=seat.name;displayName=`House ${seat.name}`}else if(form==='charge'){familyName=cultureJoin(cultureCapitalise(motif),c.houseSuffixes[id%c.houseSuffixes.length]);displayName=`House ${familyName}`}else{let root=String(seat.name).replace(new RegExp(`(${c.suffixes.join('|')})$`,'i'),'')||seat.name;familyName=cultureJoin(root,c.houseSuffixes[id%c.houseSuffixes.length]);displayName=`House ${familyName}`}let sigil=cultureHouseSigil(seed,id,motif),motto=['Hold fast and remember','By road and river','The old roots endure','No crown without duty','From stone, resolve','Under one sign'][id%6];return{name:displayName,familyName,colour:sigil.field,secondaryColour:sigil.secondary,sigil,motto}}
function cultureSummaryData(){let c=cultureSpec||cultureForSeed(world?.seed||'0');return{id:c.id,label:c.label,realmName:c.realmName,title:c.title,roots:[...c.roots],suffixes:[...c.suffixes],male:[...c.male],female:[...c.female],neutral:[...c.neutral]}}
