;const ANNALS_RUNTIME_INFO=Object.freeze({
  name:'ANNALS',
  version:'v0.8',
  runtime:'single generated HTML file',
  language:'vanilla JavaScript',
  threeRevision:'128',
  sourceManifest:'src/manifest.txt',
  generatedBy:'scripts/build.py',
  persistence:'none',
  rngStreams:'generation, history, culture'
});
function annalsAssert(condition,message){if(!condition)throw new Error(`[ANNALS guard] ${message}`);return condition}
function annalsFinitePoint(point,label){annalsAssert(point&&Number.isFinite(point.x)&&Number.isFinite(point.z),`${label} has non-finite coordinates`);if('y'in point)annalsAssert(Number.isFinite(point.y),`${label} has a non-finite height`);return true}
function annalsUniqueIds(items,label){let ids=new Set();for(const item of items){annalsAssert(item&&item.id!==undefined&&item.id!==null,`${label} contains an item without an id`);annalsAssert(!ids.has(item.id),`${label} contains duplicate id ${item.id}`);ids.add(item.id)}return ids}
function annalsRngProbe(seed,tag,count=8){let stream=rng(String(seed),tag),values=[];for(let i=0;i<count;i++)values.push(Math.floor(stream()*4294967296)>>>0);return values}
function annalsDigest(values){let hash=2166136261>>>0;for(const value of values){hash^=value>>>0;hash=Math.imul(hash,16777619)>>>0}return hash.toString(16).padStart(8,'0')}
function assertRngStreams(seed){let generationA=annalsRngProbe(seed,'generation'),history=annalsRngProbe(seed,'history'),culture=annalsRngProbe(seed,'culture-profile'),generationB=annalsRngProbe(seed,'generation');annalsAssert(generationA.every((value,index)=>value===generationB[index]),'generation RNG is not reproducible');annalsAssert(generationA.some((value,index)=>value!==history[index]),'generation and history RNG streams are not separated');annalsAssert(culture.some((value,index)=>value!==generationA[index]),'culture and generation RNG streams are not separated');annalsAssert(culture.some((value,index)=>value!==history[index]),'culture and history RNG streams are not separated');return{generation:annalsDigest(generationA),history:annalsDigest(history),culture:annalsDigest(culture),reproducible:true,separated:true}}
function assertWorldShape(candidate){annalsAssert(candidate&&typeof candidate==='object','world was not created');annalsAssert(String(candidate.seed||'').length>0,'world seed is missing');annalsAssert(typeof candidate.title==='string'&&candidate.title.trim().length>0,'world title is missing');for(const [name,min] of [['settlements',3],['houses',2],['roads',1],['buildings',1],['resources',1],['riverPaths',1]])annalsAssert(Array.isArray(candidate[name])&&candidate[name].length>=min,`world ${name} collection is missing or too small`);annalsAssert(Array.isArray(candidate.events),'world Chronicle collection is missing');annalsAssert(candidate.hydrology&&candidate.hydrology.mouth,'world hydrology mouth is missing');annalsAssert(candidate.culture&&candidate.culture.id&&Array.isArray(candidate.culture.suffixes),'world culture profile is missing');let settlements=annalsUniqueIds(candidate.settlements,'settlements'),houses=annalsUniqueIds(candidate.houses,'houses');annalsUniqueIds(candidate.buildings,'buildings');candidate.settlements.forEach((item,index)=>annalsFinitePoint(item,`settlement ${index}`));candidate.resources.forEach((item,index)=>annalsFinitePoint(item,`resource ${index}`));candidate.buildings.forEach((item,index)=>annalsFinitePoint(item,`building ${index}`));candidate.roads.forEach((road,index)=>{annalsAssert(settlements.has(road.a)&&settlements.has(road.b),`road ${index} references an unknown settlement`);annalsAssert(Array.isArray(road.pts)&&road.pts.length>=2,`road ${index} has no usable path`);road.pts.forEach((point,pointIndex)=>annalsFinitePoint(point,`road ${index} point ${pointIndex}`))});candidate.settlements.forEach((settlement,index)=>annalsAssert(houses.has(settlement.owner),`settlement ${index} references an unknown house`));let signatures=new Set();for(const house of candidate.houses){annalsAssert(house.sigil&&house.sigil.field&&house.sigil.secondary&&house.sigil.charge&&house.sigil.signature,`house ${house.id} has no complete sigil`);annalsAssert(!signatures.has(house.sigil.signature),`house ${house.id} repeats another house sigil`);signatures.add(house.sigil.signature)}return{valid:true,settlements:candidate.settlements.length,houses:candidate.houses.length,roads:candidate.roads.length,buildings:candidate.buildings.length,resources:candidate.resources.length,culture:candidate.culture.id,sigils:signatures.size}}
function assertRuntimeDependencies(){annalsAssert(typeof THREE!=='undefined','Three.js did not load');annalsAssert(String(THREE.REVISION)===ANNALS_RUNTIME_INFO.threeRevision,`expected Three.js r${ANNALS_RUNTIME_INFO.threeRevision}, received r${THREE.REVISION}`);return{threeLoaded:true,threeRevision:String(THREE.REVISION)}}
function assertBootReady(){annalsAssert(world&&world.guardState?.world?.valid,'world guards did not complete');annalsAssert(scene&&camera&&renderer,'Three.js scene, camera or renderer is missing');annalsAssert(renderer.domElement&&renderer.domElement.tagName==='CANVAS','renderer canvas is missing');annalsAssert(Array.isArray(world.events)&&world.events.length>0,'initial Chronicle entries are missing');let people=typeof characterState==='function'?characterState().registry:[];annalsAssert(people.length>0,'named character registry is empty');world.guardState.boot={ready:true,chronicleEntries:world.events.length,characters:people.length};return world.guardState.boot}
function runtimeGuardSummary(){let dependencies={threeLoaded:typeof THREE!=='undefined',threeRevision:typeof THREE!=='undefined'?String(THREE.REVISION):null};return{runtime:{...ANNALS_RUNTIME_INFO},dependencies,rng:world?.guardState?.rng||null,world:world?.guardState?.world||null,boot:world?.guardState?.boot||null,seed:world?.seed||null,title:world?.title||null}}
if(typeof window!=='undefined')window.ANNALS_GUARDS={info:ANNALS_RUNTIME_INFO,summary:runtimeGuardSummary,assertRngStreams,assertWorldShape};
