;const LOD_BANDS={far:2600,mid:1400,near:650,bubble:260},AMBIENT_LIGHT_LIMIT=8,AMBIENT_PARTICLE_LIMIT=96;
let ambientRoot=null,farRoot=null,nearRoot=null,bubbleRoot=null,weatherRoot=null,ambientLights=[],ambientBand='far',ambientStamp='';
function lodBandForAltitude(y){return y>LOD_BANDS.far?'far':y>LOD_BANDS.mid?'mid':y>LOD_BANDS.near?'near':'bubble'}
function nearestSettlementToCamera(){if(!camera||!world?.settlements?.length)return null;return world.settlements.slice().sort((a,b)=>Math.hypot(a.x-camera.position.x,a.z-camera.position.z)-Math.hypot(b.x-camera.position.x,b.z-camera.position.z))[0]}
function seasonPalette(){return{Spring:{sky:0x9db8bd,fog:0xb7c9c4},Summer:{sky:0x9fb6c4,fog:0xb6c2bd},Autumn:{sky:0xb0a38f,fog:0xc3b5a1},Winter:{sky:0xb7c5cf,fog:0xcbd2d5}}[world.season]||{sky:0x9fb6c4,fog:0xb6c2bd}}
function clearGroup(g){if(!g)return;while(g.children.length){let c=g.children.pop();c.traverse?.(o=>o.geometry?.dispose?.())}}
function districtMasses(){clearGroup(farRoot);for(const s of world.settlements){let radius=s.type==='capital'?150:s.type==='town'?105:72,colour=world.houses[s.owner]?.colour||'#8c7655',count=Math.max(2,s.layout.districts.length);for(let i=0;i<count;i++){let a=i/count*TAU,r=radius*.58,m=new THREE.Mesh(new THREE.CylinderBufferGeometry(radius*.28,radius*.34,18,8),getMat(`district-${s.owner}-${i}`,colour));m.position.set(s.x+Math.cos(a)*r,s.y+10,s.z+Math.sin(a)*r);farRoot.add(m)}}}
function addNearProps(s){clearGroup(nearRoot);let market=s.layout.market;for(let i=0;i<6;i++){let g=new THREE.Group(),base=new THREE.Mesh(new THREE.BoxBufferGeometry(18,8,12),getMat('stall-base',0x6c4d32)),cloth=new THREE.Mesh(new THREE.BoxBufferGeometry(22,2,15),getMat(`stall-cloth-${i%3}`,[0xa9573f,0x577b6b,0xc0a34b][i%3]));base.position.y=4;cloth.position.y=13;g.add(base,cloth);g.position.set(market.x+(i-2.5)*24,market.y+2,market.z+28);nearRoot.add(g)}for(let i=0;i<4;i++){let cart=new THREE.Mesh(new THREE.BoxBufferGeometry(24,10,14),getMat('cart',0x704d2f));cart.position.set(market.x-45+i*30,market.y+6,market.z-34);nearRoot.add(cart)}}
function addBubbleLife(s){clearGroup(bubbleRoot);let market=s.layout.market;for(let i=0;i<18;i++){let p=new THREE.Mesh(new THREE.CylinderBufferGeometry(2.5,3.2,12,5),getMat(`citizen-${i%4}`,[0x6c3b35,0x335d6c,0x7b693f,0x4f4a67][i%4]));p.position.set(market.x+Math.sin(i*2.1)*55,market.y+6,market.z+Math.cos(i*1.7)*45);p.userData.phase=i*.7;bubbleRoot.add(p)}for(let i=0;i<8;i++){let sheep=new THREE.Mesh(new THREE.SphereBufferGeometry(5,8,6),getMat('sheep',0xd8d3c4));sheep.scale.set(1.5,.8,1);sheep.position.set(s.x+110+Math.sin(i)*42,s.y+7,s.z+90+Math.cos(i*1.3)*36);bubbleRoot.add(sheep)}for(let i=0;i<5;i++){let smoke=new THREE.Mesh(new THREE.SphereBufferGeometry(5+i,8,6),new THREE.MeshLambertMaterial({color:0x8b8b83,transparent:true,opacity:.22}));smoke.position.set(s.x+18,s.y+55+i*14,s.z+12);smoke.userData.smoke=true;smoke.userData.phase=i;bubbleRoot.add(smoke)}for(let i=0;i<7;i++){let bird=new THREE.Mesh(new THREE.ConeBufferGeometry(2,10,3),getMat('bird',0x2f2d29));bird.rotation.z=Math.PI/2;bird.position.set(s.x+Math.sin(i)*90,s.y+110+i*5,s.z+Math.cos(i)*85);bird.userData.bird=true;bird.userData.phase=i;bubbleRoot.add(bird)}}
function configureSettlementLights(s){for(const l of ambientLights)scene.remove(l);ambientLights=[];for(const lot of s.layout.lots.slice(0,AMBIENT_LIGHT_LIMIT)){let p=new THREE.PointLight(0xffb45c,.45,130,2);p.position.set(lot.building.x,lot.building.y+28,lot.building.z);scene.add(p);ambientLights.push(p)}}
function weatherParticles(){clearGroup(weatherRoot);let snow=world.season==='Winter',wet=['Rain','Storm'].includes(world.weather);if(!snow&&!wet)return;let count=Math.min(AMBIENT_PARTICLE_LIMIT,snow?72:48),positions=[];for(let i=0;i<count;i++)positions.push((hisR()-.5)*900,hisR()*500+100,(hisR()-.5)*900);let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));weatherRoot.add(new THREE.Points(g,new THREE.PointsMaterial({color:snow?0xffffff:0x8db7cf,size:snow?7:4,transparent:true,opacity:.7})))}
function setupAmbientWorld(){ambientRoot=new THREE.Group();farRoot=new THREE.Group();nearRoot=new THREE.Group();bubbleRoot=new THREE.Group();weatherRoot=new THREE.Group();ambientRoot.add(farRoot,nearRoot,bubbleRoot,weatherRoot);scene.add(ambientRoot);districtMasses();weatherParticles()}
const atmosphereBaseSetupScene=setupScene;setupScene=function(){atmosphereBaseSetupScene();setupAmbientWorld()};
function updateAmbientWorld(){if(!ambientRoot||!camera)return;let band=lodBandForAltitude(camera.position.y),s=nearestSettlementToCamera(),stamp=`${band}:${s?.id}:${world.season}:${world.weather}`;if(stamp!==ambientStamp){ambientStamp=stamp;ambientBand=band;let p=seasonPalette();scene.background=new THREE.Color(p.sky);scene.fog.color.setHex(p.fog);farRoot.visible=band==='far';settlementDetailGroup.visible=band!=='far';nearRoot.visible=band==='near'||band==='bubble';bubbleRoot.visible=band==='bubble';weatherRoot.visible=band!=='far';if(s&&(band==='near'||band==='bubble'))addNearProps(s);if(s&&band==='bubble'){addBubbleLife(s);configureSettlementLights(s)}else{clearGroup(bubbleRoot);for(const l of ambientLights)scene.remove(l);ambientLights=[]}weatherParticles()}if(bubbleRoot.visible){let t=performance.now()*.001;for(const o of bubbleRoot.children){if(o.userData.smoke){o.position.y+=.03;o.position.x+=Math.sin(t+o.userData.phase)*.015}else if(o.userData.bird){o.position.x+=Math.sin(t*.8+o.userData.phase)*.12;o.position.z+=Math.cos(t*.7+o.userData.phase)*.1}else if(o.userData.phase!=null)o.rotation.y=t*.3+o.userData.phase}}let pts=weatherRoot.children[0];if(pts){pts.position.x=camera.userData.target.x;pts.position.z=camera.userData.target.z;pts.position.y-=world.season==='Winter'?.5:1.7;if(pts.position.y<-220)pts.position.y=0}}
function renderingSummary(){return{band:ambientBand,bands:{...LOD_BANDS},lightLimit:AMBIENT_LIGHT_LIMIT,activeLights:ambientLights.length,particleLimit:AMBIENT_PARTICLE_LIMIT,weatherParticles:weatherRoot?.children[0]?.geometry?.attributes?.position?.count||0,objects:{far:farRoot?.children.length||0,near:nearRoot?.children.length||0,bubble:bubbleRoot?.children.length||0},drawCalls:renderer?.info?.render?.calls||0,triangles:renderer?.info?.render?.triangles||0,season:world.season,weather:world.weather}}
