;function cameraPickRadius(data){if(data?.kind==='dragon')return 110;if(data?.kind==='army')return 64;if(data?.kind==='trade')return 58;return 66}
function markCameraFollowRoot(root,data){if(!root)return root;root.userData.cameraFollow=data;if(typeof THREE!=='undefined'&&!root.userData.cameraPickProxy){let proxy=new THREE.Mesh(new THREE.SphereBufferGeometry(cameraPickRadius(data),10,8),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,color:0xffffff}));proxy.name='camera-follow-pick-proxy';proxy.userData.cameraFollow=data;root.add(proxy);root.userData.cameraPickProxy=proxy}root.traverse?.(o=>{o.userData.cameraFollow=data});return root}
function cameraFollowData(kind,id,name,extra={}){return{kind,id,name,...extra}}
const cameraPickBaseEnsureTradeMarkers=ensureTradeMarkers;
ensureTradeMarkers=function(){cameraPickBaseEnsureTradeMarkers();for(const t of economyState().trades.filter(x=>x.status==='travelling')){let marker=tradeMarkerMeshes.get(t.id);markCameraFollowRoot(marker,cameraFollowData('trade',t.id,`${t.good} ${t.mode==='cog'?'cog':'caravan'}`))}}
const cameraPickBaseRefreshWarMarkers=refreshWarMarkers;
refreshWarMarkers=function(){cameraPickBaseRefreshWarMarkers();if(!warMarkerGroup)return;for(const child of warMarkerGroup.children){if(child.userData.armyId){let a=warState().armies.find(x=>x.id===child.userData.armyId);markCameraFollowRoot(child,cameraFollowData('army',child.userData.armyId,`${a?.side||'field'} army`))}else if(child.userData.campaignId){let c=warState().campaigns.find(x=>x.id===child.userData.campaignId);markCameraFollowRoot(child,cameraFollowData('incident',child.userData.campaignId,c?.name||'siege camp',{incidentType:'siege'}))}}}
const cameraPickBaseRefreshThreatMarkers=refreshThreatMarkers;
refreshThreatMarkers=function(){cameraPickBaseRefreshThreatMarkers();if(!threatMarkerGroup)return;let index=0;for(const s of world.settlements){let rate=(s.disease?.infected||0)/Math.max(1,s.pop);if(rate<.01)continue;markCameraFollowRoot(threatMarkerGroup.children[index++],cameraFollowData('incident',s.id,`plague at ${s.name}`,{incidentType:'plague'}))}for(const camp of threatState().banditCamps.filter(x=>x.status==='active'))markCameraFollowRoot(threatMarkerGroup.children[index++],cameraFollowData('incident',camp.id,'bandit camp',{incidentType:'bandit'}));let dragon=threatState().dragon;if(dragon.awake&&dragon.raids.length)markCameraFollowRoot(threatMarkerGroup.children[index],cameraFollowData('dragon','dragon','the dragon'))}
function wrapDisasterMarker(name,type){let base=window[name];if(typeof base!=='function')return;window[name]=function(record){let before=disasterMarkerGroup?.children.length||0,result=base(record);for(let i=before;i<(disasterMarkerGroup?.children.length||0);i++)markCameraFollowRoot(disasterMarkerGroup.children[i],cameraFollowData('incident',record.id,`${type} site`,{incidentType:type}));return result}}
wrapDisasterMarker('addFireMarker','fire');
wrapDisasterMarker('addFloodMarker','flood');
wrapDisasterMarker('addQuakeMarker','quake');
wrapDisasterMarker('addOmenMarker','omen');
function activateCameraFollow(data){if(!data)return false;if(data.kind==='trade')followTrade(data.id);else if(data.kind==='army')followArmy(data.id);else if(data.kind==='dragon')followDragon();else if(data.kind==='notable')followNotable(data.id);else if(data.kind==='incident')followIncident(data.incidentType,data.id,data.name);else return false;return cinematicState().mode==='follow'}
function cameraFollowRoots(){let roots=[];for(const group of [tradeMarkerGroup,warMarkerGroup,threatMarkerGroup,disasterMarkerGroup])if(group?.visible!==false)for(const child of group.children)if(child.userData.cameraFollow)roots.push(child);return roots}
function cameraPickRoots(){return[...new Set([...cameraFollowRoots(),...pickables].filter(Boolean))]}
function cameraAncestorData(object,key){let o=object;while(o){if(o.userData?.[key])return o.userData[key];o=o.parent}return null}
function cameraScreenSpaceFollow(e,maxPixels=76){let rect=renderer.domElement.getBoundingClientRect(),best=null;for(const root of cameraFollowRoots()){let p=new THREE.Vector3();root.getWorldPosition(p);let projected=p.project(camera);if(projected.z>=1||projected.z<=-1)continue;let x=rect.left+(projected.x*.5+.5)*rect.width,y=rect.top+(-projected.y*.5+.5)*rect.height,d=Math.hypot(e.clientX-x,e.clientY-y);if(d<=maxPixels&&(!best||d<best.distance))best={distance:d,data:root.userData.cameraFollow}}return best?.data||null}
handlePick=function(e){let s=completeCameraState();if(performance.now()<s.clickSuppressUntil)return false;let rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height*2-1)),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);let hits=ray.intersectObjects(cameraPickRoots(),true);for(const hit of hits){let follow=cameraAncestorData(hit.object,'cameraFollow');if(follow&&activateCameraFollow(follow))return true}let nearby=cameraScreenSpaceFollow(e);if(nearby&&activateCameraFollow(nearby))return true;for(const hit of hits){let pick=cameraAncestorData(hit.object,'pick');if(pick){showInspector(pick);director.suspend=clock.day+20;return true}}return false}
function installCameraPointerControls(){if(!renderer?.domElement||renderer.domElement.userData?.cameraControls)return;let canvas=renderer.domElement,s=completeCameraState();canvas.userData=canvas.userData||{};canvas.userData.cameraControls=true;canvas.tabIndex=0;canvas.style.touchAction='none';canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('click',e=>{if(handlePick(e)){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});canvas.addEventListener('wheel',e=>{e.preventDefault();e.stopImmediatePropagation();manualCameraInput();let state=completeCameraState();state.distance=clamp(state.distance*Math.exp(e.deltaY*.00115),120,5200)},{capture:true,passive:false});canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;s.drag={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,mode:e.button===2||e.shiftKey?'pan':'orbit',moved:false};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{let d=s.drag;if(!d||d.pointerId!==e.pointerId)return;let dx=e.clientX-d.lastX,dy=e.clientY-d.lastY,total=Math.hypot(e.clientX-d.startX,e.clientY-d.startY);d.lastX=e.clientX;d.lastY=e.clientY;if(total<4&&!d.moved)return;if(!d.moved){d.moved=true;manualCameraInput()}if(d.mode==='orbit'){s.yaw-=dx*.006;s.pitchOffset=clamp(s.pitchOffset-dy*.004,-.34,.38)}else{let scale=clamp(s.distance/900,.25,4.5),rightX=Math.cos(s.yaw),rightZ=-Math.sin(s.yaw),forwardX=-Math.sin(s.yaw),forwardZ=-Math.cos(s.yaw),target=camera.userData.target;target.x-=rightX*dx*scale+forwardX*dy*scale;target.z-=rightZ*dx*scale+forwardZ*dy*scale;target.y=hWorld(target.x,target.z)+20}});let finish=e=>{let d=s.drag;if(!d||d.pointerId!==e.pointerId)return;if(d.moved)s.clickSuppressUntil=performance.now()+180;s.drag=null;canvas.releasePointerCapture?.(e.pointerId)};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish)}
const cameraPickBaseSetupScene=setupScene;
setupScene=function(){cameraPickBaseSetupScene();installCameraPointerControls()};
function cameraMarkerScreenTarget(kind){let root=cameraFollowRoots().find(x=>x.userData.cameraFollow?.kind===kind);if(!root)return null;let p=new THREE.Vector3();root.getWorldPosition(p);let projected=p.clone().project(camera),rect=renderer.domElement.getBoundingClientRect();return{kind,x:rect.left+(projected.x*.5+.5)*rect.width,y:rect.top+(-projected.y*.5+.5)*rect.height,id:root.userData.cameraFollow?.id||null}}
if(typeof window!=='undefined'){window.ANNALS_CAMERA={...(window.ANNALS_CAMERA||{}),activateFollow:activateCameraFollow,markerScreenTarget:cameraMarkerScreenTarget}}