;let disasterMarkerGroup=null,disasterMarkerKey='';
function clearDisasterMarkers(){if(!disasterMarkerGroup)return;while(disasterMarkerGroup.children.length){let child=disasterMarkerGroup.children.pop();child.traverse?.(o=>{o.geometry?.dispose?.();if(o.material&&!o.material.userData?.shared)o.material.dispose?.()})}}
function disasterMaterial(colour,opacity=0.72){let m=new THREE.MeshLambertMaterial({color:colour,transparent:opacity<1,opacity,depthWrite:opacity>=1});m.userData.shared=false;return m}
function addFireMarker(fire){if(clock.day>fire.activeUntil)return;let s=world.settlements[fire.settlementId],lot=s?.layout?.lots?.find(l=>l.id===fire.originLotId),g=new THREE.Group(),count=Math.min(6,Math.max(2,fire.damagedLotIds.length));for(let i=0;i<count;i++){let flame=new THREE.Mesh(new THREE.ConeBufferGeometry(5+i*0.4,18+i*2,6),disasterMaterial(i%2?0xff8a2b:0xd84322,0.82)),smoke=new THREE.Mesh(new THREE.SphereBufferGeometry(7+i,8,6),disasterMaterial(0x4f4b49,0.28));flame.position.set((i-count/2)*11,10,(i%2)*8);smoke.position.set((i-count/2)*11,27+i*7,(i%2)*8);g.add(flame,smoke)}g.position.set(lot?.x||s.x,(lot?.y||s.y)+3,lot?.z||s.z);disasterMarkerGroup.add(g)}
function addFloodMarker(flood){let s=world.settlements[flood.settlementId];if(!s)return;let disc=new THREE.Mesh(new THREE.CylinderBufferGeometry(110+flood.severity*35,145+flood.severity*45,3,28),disasterMaterial(0x416f8c,0.35));disc.position.set(s.x,s.y+5,s.z);disasterMarkerGroup.add(disc);for(const ref of flood.bridges||[]){let b=world.roads[ref.roadIndex]?.bridges?.[ref.bridgeIndex];if(!b)continue;let mark=new THREE.Mesh(new THREE.BoxBufferGeometry(34,5,12),disasterMaterial(0x24536e,0.75));mark.position.set(b.x,b.y+6,b.z);mark.rotation.y=Math.PI/4;disasterMarkerGroup.add(mark)}}
function addQuakeMarker(quake){let ring=new THREE.Mesh(new THREE.RingBufferGeometry(Math.max(45,quake.radius*0.18),Math.max(52,quake.radius*0.18+11),48),new THREE.MeshBasicMaterial({color:0xa66d3d,transparent:true,opacity:0.58,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.set(quake.x,hWorld(quake.x,quake.z)+8,quake.z);disasterMarkerGroup.add(ring)}
function addOmenMarker(omen){let s=world.settlements[omen.settlementId];if(!s)return;let high=omen.level==='high',g=new THREE.Group(),beam=new THREE.Mesh(new THREE.CylinderBufferGeometry(high?3:2,high?8:5,high?120:70,8),disasterMaterial(high?0x9f63c7:0xbba36c,high?0.45:0.3)),star=new THREE.Mesh(new THREE.OctahedronBufferGeometry(high?14:9),disasterMaterial(high?0xe1b7ff:0xe2cf91,0.8));beam.position.y=high?60:35;star.position.y=high?126:78;g.add(beam,star);g.position.set(s.x+70,s.y+5,s.z-55);disasterMarkerGroup.add(g)}
function refreshDisasterMarkers(){if(!disasterMarkerGroup||typeof THREE==='undefined')return;clearDisasterMarkers();let state=disasterState();for(const fire of state.fires.slice(-4))addFireMarker(fire);for(const flood of state.floods.slice(-3))if(clock.day-flood.day<240)addFloodMarker(flood);for(const quake of state.quakes.slice(-3))if(clock.day-quake.day<180)addQuakeMarker(quake);for(const omen of state.omens.slice(-4))if(clock.day-omen.day<240)addOmenMarker(omen)}
const disasterRenderBaseSetupScene=setupScene;
setupScene=function(){disasterRenderBaseSetupScene();disasterMarkerGroup=new THREE.Group();scene.add(disasterMarkerGroup)};
const disasterRenderBaseUpdateThreatMarkers=updateThreatMarkers;
updateThreatMarkers=function(){disasterRenderBaseUpdateThreatMarkers();if(!disasterMarkerGroup)return;let s=disasterState(),key=[Math.floor(clock.day/4),s.fires.map(x=>`${x.id}:${x.damagedLotIds.length}`).join(','),s.floods.map(x=>`${x.id}:${x.damagedLotIds.length}`).join(','),s.quakes.map(x=>`${x.id}:${x.damagedLotIds.length}`).join(','),s.omens.map(x=>`${x.id}:${x.level}`).join(',')].join('|');disasterMarkerGroup.visible=!camera||camera.position.y<2800;if(key!==disasterMarkerKey){disasterMarkerKey=key;refreshDisasterMarkers()}};
