;const sigilCanvasCache=new Map(),sigilDataCache=new Map(),sigilTextureCache=new Map(),sigilMaterialCache=new Map();
let settlementHeraldryGroup=null,settlementHeraldryStamp='';
function sigilKey(house,size=64){return`${house?.sigil?.signature||house?.id||'unknown'}:${size}`}
function drawSigilField(ctx,sigil,size){ctx.fillStyle=sigil.field;ctx.fillRect(0,0,size,size);ctx.fillStyle=sigil.secondary;if(sigil.division==='per-pale')ctx.fillRect(size/2,0,size/2,size);else if(sigil.division==='per-fess')ctx.fillRect(0,size/2,size,size/2);else if(sigil.division==='bend'){ctx.beginPath();ctx.moveTo(0,size*.15);ctx.lineTo(size*.15,0);ctx.lineTo(size,size*.85);ctx.lineTo(size*.85,size);ctx.closePath();ctx.fill()}else if(sigil.division==='chevron'){ctx.beginPath();ctx.moveTo(0,size*.72);ctx.lineTo(size*.5,size*.34);ctx.lineTo(size,size*.72);ctx.lineTo(size,size*.92);ctx.lineTo(size*.5,size*.55);ctx.lineTo(0,size*.92);ctx.closePath();ctx.fill()}}
function drawSigilCharge(ctx,charge,colour,size){let s=size/64;ctx.save();ctx.strokeStyle=colour;ctx.fillStyle=colour;ctx.lineWidth=4*s;ctx.lineCap='round';ctx.lineJoin='round';if(charge==='stag'){ctx.beginPath();ctx.arc(32*s,36*s,10*s,0,TAU);ctx.fill();ctx.beginPath();ctx.moveTo(25*s,27*s);ctx.lineTo(18*s,15*s);ctx.lineTo(12*s,9*s);ctx.moveTo(18*s,15*s);ctx.lineTo(9*s,17*s);ctx.moveTo(39*s,27*s);ctx.lineTo(46*s,15*s);ctx.lineTo(52*s,9*s);ctx.moveTo(46*s,15*s);ctx.lineTo(55*s,17*s);ctx.stroke();ctx.fillRect(27*s,43*s,10*s,10*s)}else if(charge==='tower'){ctx.fillRect(20*s,21*s,24*s,30*s);for(let i=0;i<3;i++)ctx.fillRect((18+i*12)*s,15*s,8*s,10*s);ctx.fillStyle=sigilContrast(colour);ctx.fillRect(29*s,38*s,6*s,13*s)}else if(charge==='wave'){for(let y of [22,32,42]){ctx.beginPath();ctx.moveTo(9*s,y*s);ctx.bezierCurveTo(18*s,(y-8)*s,26*s,(y+8)*s,34*s,y*s);ctx.bezierCurveTo(42*s,(y-8)*s,50*s,(y+8)*s,57*s,y*s);ctx.stroke()}}else if(charge==='oak'){ctx.fillRect(29*s,31*s,6*s,22*s);for(const [x,y,r] of [[32,20,13],[22,28,10],[42,28,10]]){ctx.beginPath();ctx.arc(x*s,y*s,r*s,0,TAU);ctx.fill()}}else if(charge==='wolf'){ctx.beginPath();ctx.moveTo(16*s,21*s);ctx.lineTo(24*s,9*s);ctx.lineTo(29*s,21*s);ctx.lineTo(43*s,21*s);ctx.lineTo(50*s,11*s);ctx.lineTo(52*s,35*s);ctx.lineTo(40*s,52*s);ctx.lineTo(25*s,49*s);ctx.lineTo(14*s,34*s);ctx.closePath();ctx.fill();ctx.fillStyle=sigilContrast(colour);ctx.beginPath();ctx.arc(27*s,31*s,2.5*s,0,TAU);ctx.arc(41*s,31*s,2.5*s,0,TAU);ctx.fill()}else if(charge==='comet'){ctx.beginPath();ctx.moveTo(10*s,48*s);ctx.lineTo(34*s,31*s);ctx.lineTo(14*s,38*s);ctx.closePath();ctx.fill();ctx.beginPath();ctx.arc(41*s,24*s,12*s,0,TAU);ctx.fill()}else if(charge==='key'){ctx.beginPath();ctx.arc(24*s,25*s,10*s,0,TAU);ctx.stroke();ctx.fillRect(31*s,22*s,22*s,6*s);ctx.fillRect(45*s,27*s,6*s,10*s);ctx.fillRect(37*s,27*s,6*s,7*s)}else{ctx.beginPath();ctx.arc(32*s,32*s,10*s,0,TAU);ctx.fill();for(let i=0;i<12;i++){let a=i*TAU/12;ctx.beginPath();ctx.moveTo(32*s+Math.cos(a)*14*s,32*s+Math.sin(a)*14*s);ctx.lineTo(32*s+Math.cos(a)*24*s,32*s+Math.sin(a)*24*s);ctx.stroke()}}ctx.restore()}
function sigilContrast(colour){let value=String(colour||'#000').replace('#',''),r=parseInt(value.slice(0,2),16)||0,g=parseInt(value.slice(2,4),16)||0,b=parseInt(value.slice(4,6),16)||0;return r+g+b>430?'#2b2118':'#f4e3b3'}
function houseSigilCanvas(house,size=64){if(typeof document==='undefined'||!house?.sigil)return null;let key=sigilKey(house,size);if(sigilCanvasCache.has(key))return sigilCanvasCache.get(key);let canvas=document.createElement('canvas');canvas.width=canvas.height=size;let ctx=canvas.getContext('2d');drawSigilField(ctx,house.sigil,size);drawSigilCharge(ctx,house.sigil.charge,sigilContrast(house.sigil.field),size);ctx.strokeStyle='#2a2118';ctx.lineWidth=Math.max(2,size/32);ctx.strokeRect(1,1,size-2,size-2);sigilCanvasCache.set(key,canvas);return canvas}
function houseSigilDataUrl(house,size=64){let key=sigilKey(house,size);if(sigilDataCache.has(key))return sigilDataCache.get(key);let canvas=houseSigilCanvas(house,size),url=canvas?canvas.toDataURL('image/png'):'';sigilDataCache.set(key,url);return url}
function houseSigilTexture(house){let key=sigilKey(house,64);if(sigilTextureCache.has(key))return sigilTextureCache.get(key);let canvas=houseSigilCanvas(house,64);if(!canvas||typeof THREE==='undefined')return null;let texture=new THREE.CanvasTexture(canvas);texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.needsUpdate=true;sigilTextureCache.set(key,texture);return texture}
function houseSigilMaterial(house){let key=sigilKey(house,64);if(sigilMaterialCache.has(key))return sigilMaterialCache.get(key);let material=new THREE.MeshBasicMaterial({map:houseSigilTexture(house),side:THREE.DoubleSide,transparent:false});sigilMaterialCache.set(key,material);return material}
function addHouseBanner(parent,house,width=30,height=42,poleHeight=54){let group=new THREE.Group(),pole=new THREE.Mesh(new THREE.CylinderBufferGeometry(1.7,1.7,poleHeight,6),getMat('heraldry-pole',0x3b2a1c)),flag=new THREE.Mesh(new THREE.PlaneBufferGeometry(width,height),houseSigilMaterial(house));pole.position.y=poleHeight/2;flag.position.set(width*.48,poleHeight-height*.42,0);flag.userData.kind='house-sigil';flag.userData.houseId=house.id;flag.userData.sigilSignature=house.sigil.signature;group.add(pole,flag);parent.add(group);return group}
function clearSettlementHeraldry(){if(!settlementHeraldryGroup)return;while(settlementHeraldryGroup.children.length){let child=settlementHeraldryGroup.children.pop();child.traverse?.(o=>{if(o.geometry)o.geometry.dispose()})}}
function refreshSettlementHeraldry(){if(!settlementHeraldryGroup)return;clearSettlementHeraldry();for(const settlement of world.settlements){let house=world.houses[settlement.owner]||world.houses[0],banner=addHouseBanner(settlementHeraldryGroup,house,settlement.type==='capital'?42:30,settlement.type==='capital'?56:40,settlement.type==='capital'?74:58);banner.position.set(settlement.x,settlement.y+(settlement.type==='capital'?105:72),settlement.z);banner.rotation.y=(settlement.id%4)*Math.PI/7;banner.userData.settlementId=settlement.id;banner.userData.owner=settlement.owner}}
const heraldryBaseSetupScene=setupScene;
setupScene=function(){heraldryBaseSetupScene();settlementHeraldryGroup=new THREE.Group();settlementHeraldryGroup.name='settlement-heraldry';scene.add(settlementHeraldryGroup);refreshSettlementHeraldry()};
function updateHeraldry(){if(!settlementHeraldryGroup)return;settlementHeraldryGroup.visible=!camera||camera.position.y<2800;let stamp=world.settlements.map(s=>`${s.id}:${s.owner}`).join('|');if(stamp!==settlementHeraldryStamp){settlementHeraldryStamp=stamp;refreshSettlementHeraldry()}}
function armySigilEvidence(){let signatures=[];if(typeof warMarkerGroup!=='undefined'&&warMarkerGroup)warMarkerGroup.traverse(o=>{if(o.userData?.kind==='house-sigil'&&o.userData.sigilSignature)signatures.push(o.userData.sigilSignature)});return signatures}
function heraldrySummary(){let armySignatures=armySigilEvidence();return{worldBanners:settlementHeraldryGroup?.children.length||0,signatures:world.houses.map(h=>h.sigil?.signature||null),charges:world.houses.map(h=>h.sigil?.charge||null),materials:sigilMaterialCache.size,textures:sigilTextureCache.size,armyBanners:armySignatures.length,armySignatures}}
