;const OVERLAY_TYPES=['none','territories','trade','prosperity','plague','unrest','terrain'];
let overlayRoot=null,overlayStamp='',overlayLegend=null;
function overlayState(){return world.overlayState||(world.overlayState={active:'none',lastBuildDay:-1,builds:0})}
function setOverlay(type){let s=overlayState();s.active=OVERLAY_TYPES.includes(type)?type:'none';overlayStamp='';updateOverlayWorld(true);if(typeof document!=='undefined'){drawer();hud()}return s.active}
function disposeOverlayObject(o){o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material&&!Object.values(mats||{}).includes(n.material))n.material.dispose?.()})}
function clearOverlayRoot(){if(!overlayRoot)return;while(overlayRoot.children.length){let o=overlayRoot.children.pop();disposeOverlayObject(o)}}
function overlayMaterial(colour,opacity=.42){return new THREE.MeshBasicMaterial({color:colour,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide})}
function overlayDisk(s,radius,colour,opacity=.42,y=12){let m=new THREE.Mesh(new THREE.CircleBufferGeometry(radius,32),overlayMaterial(colour,opacity));m.rotation.x=-Math.PI/2;m.position.set(s.x,hWorld(s.x,s.z)+y,s.z);m.renderOrder=20;overlayRoot.add(m);return m}
function overlayRing(s,radius,colour,opacity=.9){let m=new THREE.Mesh(new THREE.RingBufferGeometry(radius*.82,radius,32),overlayMaterial(colour,opacity));m.rotation.x=-Math.PI/2;m.position.set(s.x,hWorld(s.x,s.z)+15,s.z);m.renderOrder=21;overlayRoot.add(m);return m}
function heatColour(value,invert=false){let v=clamp(value/100,0,1);if(invert)v=1-v;return new THREE.Color().setHSL(.33*v,.76,.46)}
function buildTerritoryOverlay(){for(const s of world.settlements){let radius=s.type==='capital'?540:s.type==='town'?390:280,colour=world.houses[s.owner]?.colour||0x8c7655;overlayDisk(s,radius,colour,.22);overlayRing(s,radius*.58,colour,.92)}}
function routeTradeStats(r){let state=economyState(),records=state.trades.filter(t=>((t.fromId===r.a&&t.toId===r.b)||(t.fromId===r.b&&t.toId===r.a))&&(t.status==='travelling'||clock.day-(t.arrivalDay||0)<360));let volume=records.reduce((n,t)=>n+(t.amount||0),0),active=records.filter(t=>t.status==='travelling').length;return{volume,active,value:records.reduce((n,t)=>n+(t.amount||0)*(world.settlements[t.toId]?.prices?.[t.good]||1),0)}}
function roadRibbon(r,radius,colour,opacity){let pts=r.pts.map(p=>new THREE.Vector3(p.x,p.y+18,p.z));if(pts.length<2)return;let curve=new THREE.CatmullRomCurve3(pts),g=new THREE.TubeBufferGeometry(curve,Math.max(8,pts.length*2),radius,4,false),m=new THREE.Mesh(g,overlayMaterial(colour,opacity));m.renderOrder=22;overlayRoot.add(m)}
function buildTradeOverlay(){for(const r of world.roads){let stats=routeTradeStats(r),active=!!(stats.volume||stats.active);roadRibbon(r,active?3+Math.min(13,stats.volume/18+stats.active*2):1.6,active?0xd4a83b:0x8b7654,active?.35+Math.min(.55,stats.value/700):.13)}for(const s of world.settlements){let inbound=economyState().trades.filter(t=>t.toId===s.id&&t.status==='travelling').reduce((n,t)=>n+t.amount,0);if(inbound)overlayRing(s,85+Math.min(90,inbound),0xf4cf67,.85)}}
function buildProsperityOverlay(){for(const s of world.settlements){let v=clamp(s.prosperity,0,100);overlayDisk(s,150+v*2.4,heatColour(v),.24+.003*v);overlayRing(s,88+v*.5,heatColour(v),.8)}}
function plagueRate(s){return s.disease?s.disease.infected/Math.max(1,s.pop):0}
function buildPlagueOverlay(){for(const s of world.settlements){let rate=plagueRate(s),pct=clamp(rate*600,0,100);overlayDisk(s,120+pct*2.8,new THREE.Color().setHSL(.02,.82,.42),rate>0?.26+.004*pct:.08);if(s.disease?.quarantined)overlayRing(s,150+pct,0x5b1720,.96)}for(const r of world.roads){let a=world.settlements[r.a],b=world.settlements[r.b],risk=Math.max(plagueRate(a),plagueRate(b));if(risk>.002)roadRibbon(r,4+Math.min(12,risk*180),0xa3313b,.25+Math.min(.65,risk*6))}}
function buildUnrestOverlay(){for(const s of world.settlements){let v=clamp(s.unrest,0,100),colour=new THREE.Color().setHSL(.12-.12*(v/100),.85,.48);overlayDisk(s,140+v*2.5,colour,.22+.004*v);if(v>=70)overlayRing(s,120+v,0xb51f28,.96)}}
function terrainColour(x,z){let b=biome(x,z),h=hWorld(x,z),sl=slope(x,z),base={water:0x2f6f91,stone:0x8e8780,forest:0x315c3a,farmland:0xa6b65d,'dry steppe':0xa89d61,grassland:0x67a05a}[b]||0x77906a,c=new THREE.Color(base);c.offsetHSL(0,-Math.min(.25,sl*.18),clamp((h-160)/1800,-.1,.16));return c}
function buildTerrainOverlay(){let seg=24,g=new THREE.PlaneBufferGeometry(W,W,seg,seg);g.rotateX(-Math.PI/2);let p=g.attributes.position,cols=[];for(let i=0;i<p.count;i++){let x=p.getX(i),z=p.getZ(i),c=terrainColour(x,z);p.setY(i,hWorld(x,z)+10);cols.push(c.r,c.g,c.b)}g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));g.computeVertexNormals();let m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.52,depthWrite:false,side:THREE.DoubleSide}));m.renderOrder=19;overlayRoot.add(m);let positions=[],colours=[];for(const r of world.resources.slice(0,180)){positions.push(r.x,hWorld(r.x,r.z)+24,r.z);let c=new THREE.Color({farmland:0xe4d568,forest:0x316d42,ore:0xb9b2aa,fishing:0x58b8d1,harbour:0xf0a85a}[r.type]||0xffffff);colours.push(c.r,c.g,c.b)}if(positions.length){let pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));pg.setAttribute('color',new THREE.Float32BufferAttribute(colours,3));let pts=new THREE.Points(pg,new THREE.PointsMaterial({size:16,vertexColors:true,transparent:true,opacity:.88,depthWrite:false}));pts.renderOrder=23;overlayRoot.add(pts)}}
function overlaySignature(){let a=overlayState().active;if(a==='territories')return`${a}:${world.settlements.map(s=>s.owner).join(',')}`;if(a==='trade')return`${a}:${Math.floor(clock.day/15)}:${economyState().trades.map(t=>`${t.id}:${t.status}:${Math.round(t.amount)}`).join('|')}`;if(a==='prosperity')return`${a}:${world.settlements.map(s=>Math.round(s.prosperity/5)).join(',')}`;if(a==='plague')return`${a}:${world.settlements.map(s=>`${Math.round(plagueRate(s)*1000)}:${s.disease?.quarantined?1:0}`).join(',')}`;if(a==='unrest')return`${a}:${world.settlements.map(s=>Math.round(s.unrest/5)).join(',')}`;return a}
function updateOverlayLegend(){if(typeof document==='undefined')return;if(!overlayLegend){overlayLegend=document.createElement('div');overlayLegend.id='overlay-legend';overlayLegend.className='panel';overlayLegend.style.cssText='left:50%;top:64px;transform:translateX(-50%);pointer-events:none;max-width:560px;text-align:center;background:#17130fdd;color:#eadcc0;border-color:#c9a227;display:none';document.body.appendChild(overlayLegend)}let a=overlayState().active,labels={territories:'House colours and settlement ownership',trade:'Recent and active caravan route intensity',prosperity:'Red low → green high prosperity',plague:'Infection intensity, quarantine rings and connected roads',unrest:'Low unrest → revolt-risk red',terrain:'Elevation, slope, biome and resource points'};overlayLegend.style.display=a==='none'?'none':'block';if(a!=='none')overlayLegend.innerHTML=`<b>${safeName(a[0].toUpperCase()+a.slice(1))}</b><div class="small">${safeName(labels[a])}</div>`}
function rebuildOverlay(){clearOverlayRoot();let a=overlayState().active;if(a==='territories')buildTerritoryOverlay();else if(a==='trade')buildTradeOverlay();else if(a==='prosperity')buildProsperityOverlay();else if(a==='plague')buildPlagueOverlay();else if(a==='unrest')buildUnrestOverlay();else if(a==='terrain')buildTerrainOverlay();overlayRoot.visible=a!=='none';overlayState().lastBuildDay=Math.floor(clock.day);overlayState().builds++;updateOverlayLegend()}
function setupOverlayWorld(){overlayRoot=new THREE.Group();overlayRoot.name='realm-overlays';scene.add(overlayRoot);rebuildOverlay()}
const overlayBaseSetupScene=setupScene;setupScene=function(){overlayBaseSetupScene();setupOverlayWorld()};
function updateOverlayWorld(force=false){if(!overlayRoot||!camera)return;let sig=overlaySignature();if(force||sig!==overlayStamp){overlayStamp=sig;rebuildOverlay()}overlayRoot.visible=overlayState().active!=='none'&&camera.position.y>350;updateOverlayLegend()}
const overlayBaseLoop=loop;loop=function(t){overlayBaseLoop(t);if(typeof updateAmbientWorld==='function')updateAmbientWorld();updateOverlayWorld()};
function overlaySummary(){let a=overlayState().active;return{active:a,types:[...OVERLAY_TYPES],singleActive:true,visible:!!overlayRoot?.visible,objects:overlayRoot?.children.length||0,builds:overlayState().builds,lastBuildDay:overlayState().lastBuildDay,owners:world.settlements.map(s=>s.owner),tradeRoutes:world.roads.filter(r=>routeTradeStats(r).volume>0).length,prosperity:world.settlements.map(s=>Math.round(s.prosperity)),plague:world.settlements.map(s=>Math.round(plagueRate(s)*10000)/100),unrest:world.settlements.map(s=>Math.round(s.unrest))}}
if(typeof window!=='undefined')window.ANNALS_OVERLAYS={set:setOverlay,summary:overlaySummary,types:[...OVERLAY_TYPES]};