;const PERFORMANCE_DRAW_CALL_BUDGET=250,PERFORMANCE_TRIANGLE_BUDGET=350000,PERFORMANCE_OBJECT_BUDGET=2400;
const PERFORMANCE_QUALITY_ORDER=['minimal','low','balanced','high'];
const PERFORMANCE_PROFILES={
minimal:{pixelRatio:1,lights:0,particles:0,citizens:0,sheep:0,birds:0,smoke:0,stalls:0,carts:0,districtFactor:.45,detailBand:'none',overlaySegments:10,terrainSegments:8,resources:36,curveFactor:.7},
low:{pixelRatio:1.15,lights:3,particles:32,citizens:6,sheep:3,birds:3,smoke:2,stalls:3,carts:2,districtFactor:.6,detailBand:'bubble',overlaySegments:14,terrainSegments:12,resources:72,curveFactor:1},
balanced:{pixelRatio:1.5,lights:6,particles:64,citizens:12,sheep:6,birds:5,smoke:4,stalls:4,carts:3,districtFactor:.8,detailBand:'near',overlaySegments:22,terrainSegments:18,resources:120,curveFactor:1.4},
high:{pixelRatio:2,lights:8,particles:96,citizens:18,sheep:8,birds:7,smoke:5,stalls:6,carts:4,districtFactor:1,detailBand:'mid',overlaySegments:32,terrainSegments:24,resources:180,curveFactor:2}
};
let performanceMeter=null;
function inferredPerformanceQuality(){let memory=typeof navigator!=='undefined'&&Number.isFinite(navigator.deviceMemory)?navigator.deviceMemory:4,cores=typeof navigator!=='undefined'&&Number.isFinite(navigator.hardwareConcurrency)?navigator.hardwareConcurrency:4;if(memory>=8&&cores>=8)return'high';if(memory>=4&&cores>=4)return'balanced';return'low'}
function performanceState(){return world.performanceState||(world.performanceState={quality:inferredPerformanceQuality(),forced:false,fps:60,frameMs:16.7,samples:[],lastFrame:0,lastEvaluation:0,badSeconds:0,goodSeconds:0,drawCalls:0,triangles:0,sceneObjects:0,baselineObjects:0,maxObjectGrowth:0,degradedReason:'',qualityChanges:0,meterVisible:false})}
function currentQualityBudget(){return PERFORMANCE_PROFILES[performanceState().quality]||PERFORMANCE_PROFILES.balanced}
function qualityIndex(q){return PERFORMANCE_QUALITY_ORDER.indexOf(q)}
function setPerformanceQuality(level,forced=true,reason='manual'){let state=performanceState(),next=PERFORMANCE_PROFILES[level]?level:'balanced';if(state.quality!==next){state.quality=next;state.qualityChanges++;state.degradedReason=reason;ambientStamp='';overlayStamp=''}state.forced=forced;applyPerformanceQuality();return state.quality}
function applyPerformanceQuality(){if(!renderer)return;let budget=currentQualityBudget(),ratio=typeof devicePixelRatio==='number'?devicePixelRatio:1;renderer.setPixelRatio(Math.min(ratio,budget.pixelRatio));renderer.shadowMap.enabled=false}
function downgradePerformance(reason){let state=performanceState(),i=qualityIndex(state.quality);if(i>0)setPerformanceQuality(PERFORMANCE_QUALITY_ORDER[i-1],false,reason)}
function upgradePerformance(){let state=performanceState(),i=qualityIndex(state.quality);if(i<PERFORMANCE_QUALITY_ORDER.length-1)setPerformanceQuality(PERFORMANCE_QUALITY_ORDER[i+1],false,'sustained frame headroom')}
function countSceneObjects(){let count=0;if(scene)scene.traverse(()=>count++);return count}
function performanceCollections(){let chars=world?.characterState?.registry?.length||0,econ=world?.economyState,war=world?.warState,threat=world?.threatState;return{chronicle:world?.events?.length||0,structuredEvents:typeof structuredEvents!=='undefined'?structuredEvents.length:0,characters:chars,trades:econ?.trades?.length||0,armies:war?.armies?.length||0,campaigns:war?.campaigns?.length||0,banditCamps:threat?.banditCamps?.length||0,dragonRaids:threat?.dragon?.raids?.length||0,scars:world?.scarState?.registry?.length||0,memories:world?.memoryState?.registry?.length||0}}
function evaluatePerformance(now){let state=performanceState();if(now-state.lastEvaluation<1000)return;state.lastEvaluation=now;let avg=state.samples.length?state.samples.reduce((a,b)=>a+b,0)/state.samples.length:16.7;state.frameMs=Math.round(avg*10)/10;state.fps=Math.round(10000/Math.max(1,avg))/10;state.samples=[];state.drawCalls=renderer?.info?.render?.calls||0;state.triangles=renderer?.info?.render?.triangles||0;state.sceneObjects=countSceneObjects();if(!state.baselineObjects&&state.sceneObjects)state.baselineObjects=state.sceneObjects;state.maxObjectGrowth=Math.max(state.maxObjectGrowth,state.sceneObjects-state.baselineObjects);let overBudget=state.drawCalls>PERFORMANCE_DRAW_CALL_BUDGET||state.triangles>PERFORMANCE_TRIANGLE_BUDGET||state.sceneObjects>PERFORMANCE_OBJECT_BUDGET,slow=state.fps<42;if(overBudget||slow){state.badSeconds++;state.goodSeconds=0}else{state.goodSeconds++;state.badSeconds=0}if(!state.forced&&state.badSeconds>=2){downgradePerformance(overBudget?'render budget exceeded':'frame rate below floor');state.badSeconds=0}else if(!state.forced&&state.goodSeconds>=10&&state.fps>56&&state.drawCalls<PERFORMANCE_DRAW_CALL_BUDGET*.72){upgradePerformance();state.goodSeconds=0}}
function performanceSummary(){let state=performanceState(),budget=currentQualityBudget();return{quality:state.quality,forced:state.forced,fps:state.fps,frameMs:state.frameMs,drawCalls:state.drawCalls,triangles:state.triangles,sceneObjects:state.sceneObjects,baselineObjects:state.baselineObjects,maxObjectGrowth:state.maxObjectGrowth,degradedReason:state.degradedReason,qualityChanges:state.qualityChanges,budgets:{drawCalls:PERFORMANCE_DRAW_CALL_BUDGET,triangles:PERFORMANCE_TRIANGLE_BUDGET,sceneObjects:PERFORMANCE_OBJECT_BUDGET,...budget},breaches:{drawCalls:state.drawCalls>PERFORMANCE_DRAW_CALL_BUDGET,triangles:state.triangles>PERFORMANCE_TRIANGLE_BUDGET,sceneObjects:state.sceneObjects>PERFORMANCE_OBJECT_BUDGET},collections:performanceCollections()}}
function ensurePerformanceMeter(){if(typeof document==='undefined')return null;if(!performanceMeter){performanceMeter=document.createElement('div');performanceMeter.id='performance-meter';performanceMeter.className='panel';performanceMeter.style.cssText='right:16px;top:64px;min-width:190px;background:#17130fee;color:#eadcc0;border-color:#c9a227;font:12px system-ui;display:none;pointer-events:none';document.body.appendChild(performanceMeter)}return performanceMeter}
function togglePerformanceMeter(force){let state=performanceState();state.meterVisible=typeof force==='boolean'?force:!state.meterVisible;renderPerformanceMeter();return state.meterVisible}
function renderPerformanceMeter(){let el=ensurePerformanceMeter();if(!el)return;let state=performanceState(),show=state.meterVisible||location.hash.includes('debug=1');el.style.display=show?'block':'none';if(!show)return;let s=performanceSummary();el.innerHTML=`<b>Performance · ${safeName(s.quality)}</b><div>${s.fps.toFixed(1)} fps · ${s.frameMs.toFixed(1)} ms</div><div>${s.drawCalls}/${s.budgets.drawCalls} calls · ${s.triangles.toLocaleString()} tris</div><div>${s.sceneObjects}/${s.budgets.sceneObjects} scene objects</div><div>${s.collections.characters} notables · ${s.collections.chronicle} Chronicle</div>`}
const performanceBaseDistrictMasses=districtMasses;
districtMasses=function(){clearGroup(farRoot);let budget=currentQualityBudget();for(const s of world.settlements){let radius=s.type==='capital'?150:s.type==='town'?105:72,colour=world.houses[s.owner]?.colour||'#8c7655',count=Math.max(1,Math.ceil(s.layout.districts.length*budget.districtFactor));for(let i=0;i<count;i++){let a=i/count*TAU,r=radius*.58,m=new THREE.Mesh(new THREE.CylinderBufferGeometry(radius*.28,radius*.34,18,8),getMat(`district-${s.owner}-${i}`,colour));m.position.set(s.x+Math.cos(a)*r,s.y+10,s.z+Math.sin(a)*r);farRoot.add(m)}}};
addNearProps=function(s){clearGroup(nearRoot);let budget=currentQualityBudget(),market=s.layout.market;for(let i=0;i<budget.stalls;i++){let g=new THREE.Group(),base=new THREE.Mesh(new THREE.BoxBufferGeometry(18,8,12),getMat('stall-base',0x6c4d32)),cloth=new THREE.Mesh(new THREE.BoxBufferGeometry(22,2,15),getMat(`stall-cloth-${i%3}`,[0xa9573f,0x577b6b,0xc0a34b][i%3]));base.position.y=4;cloth.position.y=13;g.add(base,cloth);g.position.set(market.x+(i-(budget.stalls-1)/2)*24,market.y+2,market.z+28);nearRoot.add(g)}for(let i=0;i<budget.carts;i++){let cart=new THREE.Mesh(new THREE.BoxBufferGeometry(24,10,14),getMat('cart',0x704d2f));cart.position.set(market.x-45+i*30,market.y+6,market.z-34);nearRoot.add(cart)}};
addBubbleLife=function(s){clearGroup(bubbleRoot);let budget=currentQualityBudget(),market=s.layout.market;for(let i=0;i<budget.citizens;i++){let p=new THREE.Mesh(new THREE.CylinderBufferGeometry(2.5,3.2,12,5),getMat(`citizen-${i%4}`,[0x6c3b35,0x335d6c,0x7b693f,0x4f4a67][i%4]));p.position.set(market.x+Math.sin(i*2.1)*55,market.y+6,market.z+Math.cos(i*1.7)*45);p.userData.phase=i*.7;bubbleRoot.add(p)}for(let i=0;i<budget.sheep;i++){let sheep=new THREE.Mesh(new THREE.SphereBufferGeometry(5,8,6),getMat('sheep',0xd8d3c4));sheep.scale.set(1.5,.8,1);sheep.position.set(s.x+110+Math.sin(i)*42,s.y+7,s.z+90+Math.cos(i*1.3)*36);bubbleRoot.add(sheep)}for(let i=0;i<budget.smoke;i++){let smoke=new THREE.Mesh(new THREE.SphereBufferGeometry(5+i,8,6),new THREE.MeshLambertMaterial({color:0x8b8b83,transparent:true,opacity:.22}));smoke.position.set(s.x+18,s.y+55+i*14,s.z+12);smoke.userData.smoke=true;smoke.userData.phase=i;bubbleRoot.add(smoke)}for(let i=0;i<budget.birds;i++){let bird=new THREE.Mesh(new THREE.ConeBufferGeometry(2,10,3),getMat('bird',0x2f2d29));bird.rotation.z=Math.PI/2;bird.position.set(s.x+Math.sin(i)*90,s.y+110+i*5,s.z+Math.cos(i)*85);bird.userData.bird=true;bird.userData.phase=i;bubbleRoot.add(bird)}};
configureSettlementLights=function(s){for(const l of ambientLights)scene.remove(l);ambientLights=[];for(const lot of s.layout.lots.slice(0,currentQualityBudget().lights)){let p=new THREE.PointLight(0xffb45c,.45,130,2);p.position.set(lot.building.x,lot.building.y+28,lot.building.z);scene.add(p);ambientLights.push(p)}};
weatherParticles=function(){clearGroup(weatherRoot);let snow=world.season==='Winter',wet=['Rain','Storm'].includes(world.weather),limit=currentQualityBudget().particles;if((!snow&&!wet)||!limit)return;let count=Math.min(limit,snow?72:48),positions=[];for(let i=0;i<count;i++)positions.push((hisR()-.5)*900,hisR()*500+100,(hisR()-.5)*900);let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));weatherRoot.add(new THREE.Points(g,new THREE.PointsMaterial({color:snow?0xffffff:0x8db7cf,size:snow?7:4,transparent:true,opacity:.7})))};
overlayDisk=function(s,radius,colour,opacity=.42,y=12){let m=new THREE.Mesh(new THREE.CircleBufferGeometry(radius,currentQualityBudget().overlaySegments),overlayMaterial(colour,opacity));m.rotation.x=-Math.PI/2;m.position.set(s.x,hWorld(s.x,s.z)+y,s.z);m.renderOrder=20;overlayRoot.add(m);return m};
overlayRing=function(s,radius,colour,opacity=.9){let m=new THREE.Mesh(new THREE.RingBufferGeometry(radius*.82,radius,currentQualityBudget().overlaySegments),overlayMaterial(colour,opacity));m.rotation.x=-Math.PI/2;m.position.set(s.x,hWorld(s.x,s.z)+15,s.z);m.renderOrder=21;overlayRoot.add(m);return m};
roadRibbon=function(r,radius,colour,opacity){let pts=r.pts.map(p=>new THREE.Vector3(p.x,p.y+18,p.z));if(pts.length<2)return;let curve=new THREE.CatmullRomCurve3(pts),g=new THREE.TubeBufferGeometry(curve,Math.max(6,Math.ceil(pts.length*currentQualityBudget().curveFactor)),radius,4,false),m=new THREE.Mesh(g,overlayMaterial(colour,opacity));m.renderOrder=22;overlayRoot.add(m)};
buildTerrainOverlay=function(){let budget=currentQualityBudget(),seg=budget.terrainSegments,g=new THREE.PlaneBufferGeometry(W,W,seg,seg);g.rotateX(-Math.PI/2);let p=g.attributes.position,cols=[];for(let i=0;i<p.count;i++){let x=p.getX(i),z=p.getZ(i),c=terrainColour(x,z);p.setY(i,hWorld(x,z)+10);cols.push(c.r,c.g,c.b)}g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));g.computeVertexNormals();let m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.52,depthWrite:false,side:THREE.DoubleSide}));m.renderOrder=19;overlayRoot.add(m);let positions=[],colours=[];for(const r of world.resources.slice(0,budget.resources)){positions.push(r.x,hWorld(r.x,r.z)+24,r.z);let c=new THREE.Color({farmland:0xe4d568,forest:0x316d42,ore:0xb9b2aa,fishing:0x58b8d1,harbour:0xf0a85a}[r.type]||0xffffff);colours.push(c.r,c.g,c.b)}if(positions.length){let pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));pg.setAttribute('color',new THREE.Float32BufferAttribute(colours,3));let pts=new THREE.Points(pg,new THREE.PointsMaterial({size:16,vertexColors:true,transparent:true,opacity:.88,depthWrite:false}));pts.renderOrder=23;overlayRoot.add(pts)}};
const performanceBaseUpdateAmbientWorld=updateAmbientWorld;
updateAmbientWorld=function(){performanceBaseUpdateAmbientWorld();let budget=currentQualityBudget(),band=ambientBand,detail=budget.detailBand,allow=detail==='mid'?band!=='far':detail==='near'?(band==='near'||band==='bubble'):detail==='bubble'?band==='bubble':false;if(settlementDetailGroup)settlementDetailGroup.visible=allow;farRoot.visible=band==='far'||!allow;nearRoot.visible=allow&&(band==='near'||band==='bubble')&&budget.stalls>0;bubbleRoot.visible=allow&&band==='bubble'&&budget.citizens+budget.sheep+budget.birds+budget.smoke>0};
const performanceBaseSetupScene=setupScene;
setupScene=function(){performanceBaseSetupScene();applyPerformanceQuality();performanceState().sceneObjects=countSceneObjects()};
const performanceBaseLoop=loop;
loop=function(t){let state=performanceState(),delta=state.lastFrame?Math.min(250,t-state.lastFrame):16.7;state.lastFrame=t;state.samples.push(delta);if(state.samples.length>180)state.samples.shift();performanceBaseLoop(t);evaluatePerformance(t);renderPerformanceMeter()};
if(typeof window!=='undefined')window.ANNALS_PERFORMANCE={summary:performanceSummary,setQuality:setPerformanceQuality,toggleMeter:togglePerformanceMeter,profiles:PERFORMANCE_PROFILES};