function setupScene(){if(typeof THREE==='undefined')throw Error('Three.js r128 did not load');scene=new THREE.Scene();scene.fog=new THREE.Fog(0xa8b8c4,1500,7600);camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,12000);camera.position.set(0,1750,2650);camera.userData.target=new THREE.Vector3(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));app.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xd9ecff,0x4b3423,1.2));let sun=new THREE.DirectionalLight(0xfff1c2,1.5);sun.position.set(-1200,2300,900);scene.add(sun);terrainMesh();waterMesh();roadMeshes();settlementMeshes();labelsRefresh();if(typeof document!=='undefined'){drawer();hud()}}
function mat(c){return new THREE.MeshLambertMaterial({color:c})}
const mats={};function getMat(k,c){return mats[k]||(mats[k]=mat(c))}
function terrainMesh(){let g=new THREE.PlaneBufferGeometry(W,W,46,46);g.rotateX(-Math.PI/2);let p=g.attributes.position,cols=[];for(let i=0;i<p.count;i++){let x=p.getX(i),z=p.getZ(i),h=hWorld(x,z),b=biome(x,z),c=new THREE.Color(b==='water'?0x315f7a:b==='stone'?0x8e8780:b==='forest'?0x355b3c:b==='farmland'?0xa4b35d:b==='dry steppe'?0x9ca260:0x73a85b);p.setY(i,h);c.multiplyScalar(.8+h/3600);cols.push(c.r,c.g,c.b)}g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));g.computeVertexNormals();scene.add(new THREE.Mesh(g,new THREE.MeshLambertMaterial({vertexColors:true})))}
function waterMesh(){let m=new THREE.LineBasicMaterial({color:0x4e91b0});for(const p of world.riverPaths)scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p.map(q=>new THREE.Vector3(q.x,hWorld(q.x,q.z)+4,q.z))),m));for(const l of world.hydrology.lakes){let o=new THREE.Mesh(new THREE.CircleBufferGeometry(l.r,24),new THREE.MeshLambertMaterial({color:0x477fa0,transparent:true,opacity:.45}));o.rotation.x=-Math.PI/2;o.position.set(l.x,2,l.z);scene.add(o)}}
function roadMeshes(){let m=new THREE.LineBasicMaterial({color:0x755a38});for(const r of world.roads){scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(r.pts.map(p=>new THREE.Vector3(p.x,p.y+2,p.z))),m));for(const b of r.bridges){let o=new THREE.Mesh(new THREE.BoxBufferGeometry(90,10,28),new THREE.MeshLambertMaterial({color:0x6a5a3d}));o.position.set(b.x,b.y,b.z);scene.add(o)}}}
function addPick(o,data){o.userData.pick=data;pickables.push(o);return o}
function settlementMeshes(){settlementDetailGroup=new THREE.Group();scene.add(settlementDetailGroup);for(const s of world.settlements){let group=new THREE.Group,rad=s.type==='capital'?76:s.type==='town'?52:34,base=new THREE.Mesh(new THREE.CylinderBufferGeometry(rad,rad,22,16),getMat(s.site.harbour?'settle-harbour':'settle',s.site.harbour?0xd8c48c:0xbfa785)),keep=new THREE.Mesh(new THREE.ConeBufferGeometry(.5*rad,90,6),getMat('banner'+s.owner,world.houses[s.owner].colour));base.position.y=12;keep.position.y=68;group.add(base,keep);group.position.set(s.x,s.y+4,s.z);addPick(base,{kind:'settlement',settlement:s});addPick(keep,{kind:'settlement',settlement:s});scene.add(group);selectables.push({data:s,pos:group.position});addSettlementDetail(s)}}
function lineFrom(pts,color=0x6a5134){let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts.map(p=>new THREE.Vector3(p.x,p.y+3,p.z))),new THREE.LineBasicMaterial({color,transparent:true,opacity:.75}));settlementDetailGroup.add(line);return line}
function addSettlementDetail(s){for(const st of s.layout.streets)lineFrom(st.pts,st.kind==='ring'?0x8a6a42:0x6f5330);if(s.type==='village')addWell(s.layout.market.x,s.layout.market.y,s.layout.market.z);for(const lot of s.layout.lots)addBuildingMesh(lot)}
function addWell(x,y,z){let g=new THREE.Group,ring=new THREE.Mesh(new THREE.CylinderBufferGeometry(13,13,8,12),getMat('stone',0x968b7a)),roof=new THREE.Mesh(new THREE.ConeBufferGeometry(20,18,4),getMat('roof',0x6b2f24));ring.position.y=4;roof.position.y=25;g.add(ring,roof);g.position.set(x,y,z);settlementDetailGroup.add(g)}
function box(w,h,d,c){let m=new THREE.Mesh(new THREE.BoxBufferGeometry(w,h,d),c);m.position.y=h/2;return m}
function roof(w,h,d,c){let r=new THREE.Mesh(new THREE.ConeBufferGeometry(Math.max(w,d)*.68,h,4),c);r.rotation.y=Math.PI/4;r.position.y=h/2;return r}
function cyl(r,h,c,n=12){let m=new THREE.Mesh(new THREE.CylinderBufferGeometry(r,r,h,n),c);m.position.y=h/2;return m}
function buildingDims(b){let base={house:[28,26,24],longhouse:[62,24,26],shop:[34,24,30],smithy:[38,22,32],mill:[30,50,30],granary:[44,32,30],tavern:[54,30,38],temple:[46,48,42],warehouse:[76,30,38],tower:[30,72,30],wall:[72,22,12],gate:[68,42,20],keep:[84,90,76]}[b.type]||[30,25,25],scale=b.tier==='stone'?1.12:b.tier==='hovel'?.82:1;return base.map(v=>v*scale)}
function addBuildingMesh(lot){let b=lot.building,g=new THREE.Group,[w,h,d]=buildingDims(b),wall=b.state==='ruin'?getMat('ruin',0x3b352e):b.tier==='stone'?getMat('stonewall',0xa49c8b):b.tier==='timber'?getMat('timberwall',0xb48b5d):getMat('hovelwall',0x8d7659),roofMat=b.state==='ruin'?getMat('char',0x211b17):getMat('redroof',b.type==='temple'?0x8e8a7a:b.type==='warehouse'?0x69523a:0x743228);let body=(b.type==='tower'||b.type==='mill')?cyl(w/2,h,wall,12):box(w,h,d,wall);g.add(addPick(body,{kind:'building',building:b,lot}));if(!['wall','gate'].includes(b.type)){let rf=roof(w,h*.42,d,roofMat);rf.position.y=h+h*.2;g.add(addPick(rf,{kind:'building',building:b,lot}))}if(b.type==='keep'||b.type==='temple'){let sp=cyl(w*.11,h*.6,getMat('spire',0xd7d1bc),8);sp.position.y=h*1.02;g.add(sp)}if(b.type==='smithy'||b.type==='tavern'||b.type==='house'){let ch=box(6,h*.58,6,getMat('chimney',0x3d3128));ch.position.set(w*.28,h*.75,d*.16);g.add(ch)}if(b.type==='shop'||b.type==='tavern'){let sign=box(6,12,18,getMat('sign',0xd6bb73));sign.position.set(w*.55,h*.55,0);g.add(sign)}if(b.type==='mill'){let sail=new THREE.Mesh(new THREE.BoxBufferGeometry(4,76,6),getMat('sail',0xd8d0bd));sail.position.set(0,h*.74,d*.58);sail.rotation.z=Math.PI/4;g.add(sail);let sail2=sail.clone();sail2.rotation.z=-Math.PI/4;g.add(sail2)}if(b.type==='granary'){for(let i=-1;i<=1;i+=2){let st=box(5,18,5,getMat('post',0x4a3424));st.position.set(i*w*.25,9,d*.35);g.add(st)}}if(b.type==='gate'){let gap=box(w*.32,h*.72,d*1.2,getMat('gatewood',0x3d2a1d));gap.position.y=h*.36;g.add(gap)}if(b.tier==='timber'&&b.state!=='ruin'&&!['wall','gate'].includes(b.type)){for(const sx of [-.3,.3]){let beam=box(3,h*.9,3,getMat('beam',0x3b271a));beam.position.set(sx*w,h*.45,d*.52);g.add(beam)}}if(b.state==='rebuilding'){let frame=box(w*1.12,4,d*1.12,getMat('frame',0xd8c070));frame.position.y=h+10;g.add(frame)}g.position.set(b.x,b.y,b.z);g.rotation.y=b.angle||0;settlementDetailGroup.add(g);b.mesh=g}
function refreshSettlementDetails(){if(!scene||!settlementDetailGroup)return;scene.remove(settlementDetailGroup);pickables=[];settlementDetailGroup=new THREE.Group();scene.add(settlementDetailGroup);for(const s of world.settlements)addSettlementDetail(s)}
function labelsRefresh(){if(typeof document==='undefined')return;if(!labels.length)for(const s of world.settlements){let el=document.createElement('div');el.className='label';document.body.appendChild(el);labels.push({el,s})}for(const l of labels)l.el.innerHTML=l.s.name+(l.s.site.harbour?' ⚓':'')}
function drawLabels(){for(const l of labels){let v=new THREE.Vector3(l.s.x,l.s.y+125,l.s.z).project(camera);l.el.style.left=(v.x*.5+.5)*innerWidth+'px';l.el.style.top=(-v.y*.5+.5)*innerHeight+'px';l.el.style.display=v.z<1&&camera.position.y>120?'block':'none'}}
